// src/lib/intelligence/nxt-entities-elpaso.ts
// Extended El Paso vendor entity registry — 30 new vendors added March 2026
// Appended to NXT_ENTITIES in nxt-entities.ts via spread

import type { NxtEntity } from './nxt-entities';

export const NXT_ENTITIES_ELPASO: NxtEntity[] = [

  // ── Additional Defense Contractors ────────────────────────────────────────
  {
    id: 'ep-northrop',
    name: 'Northrop Grumman',
    category: 'Defense Tech',
    aliases: ['northrop grumman', 'northrop', 'ngc', 'northrop grumman corp', 'ibcs northrop'],
    keywords: ['ibcs integrated battle command', 'air missile defense c2', 'c2 architecture', 'ibcs program', 'sensor fusion air defense'],
    naicsCodes: ['336411', '334511', '541330'],
    ikerScore: 90,
  },
  {
    id: 'ep-lockheed',
    name: 'Lockheed Martin Missiles & Fire Control',
    category: 'Defense Tech',
    aliases: ['lockheed martin', 'lockheed', 'lmt', 'lockheed mfc', 'lockheed fire control'],
    keywords: ['thaad interceptor', 'terminal high altitude area defense', 'himars', 'pac-3 mse', 'fort bliss thaad', 'guided mlrs'],
    naicsCodes: ['336414', '336411', '541330'],
    ikerScore: 93,
  },
  {
    id: 'ep-generaldynamics',
    name: 'General Dynamics Land Systems',
    category: 'Defense Tech',
    aliases: ['general dynamics land systems', 'gdls', 'gdls corp', 'm1 abrams contractor'],
    keywords: ['m1a2 sepv3', 'abrams tank', 'abrams depot', 'land systems fort bliss', 'armored vehicle depot'],
    naicsCodes: ['336992', '541512', '334511'],
    ikerScore: 89,
  },
  {
    id: 'ep-bae',
    name: 'BAE Systems El Paso',
    category: 'Defense Tech',
    aliases: ['bae systems', 'bae', 'bae systems inc', 'bae bradley'],
    keywords: ['bradley m2a4', 'electronic warfare bae', 'envg-b night vision', 'soldier systems bae', 'bradley upgrade'],
    naicsCodes: ['334511', '336992', '541330'],
    ikerScore: 85,
  },
  {
    id: 'ep-accenturefed',
    name: 'Accenture Federal Services',
    category: 'Defense Tech',
    aliases: ['accenture federal', 'accenture federal services', 'accenture dod', 'afs'],
    keywords: ['gcss army s4hana', 'army erp modernization', 'army sap upgrade', 'azure govcloud migration', 'army ai center excellence'],
    naicsCodes: ['541611', '541512', '541519'],
    ikerScore: 84,
  },
  {
    id: 'ep-deloitte',
    name: 'Deloitte Government & Public Services',
    category: 'Defense Tech',
    aliases: ['deloitte', 'deloitte government', 'deloitte gps', 'deloitte consulting federal'],
    keywords: ['army audit readiness', 'cbp it modernization', 'defense financial management', 'cleared personnel consulting'],
    naicsCodes: ['541611', '541512', '541219'],
    ikerScore: 82,
  },
  {
    id: 'ep-caci-ep',
    name: 'CACI International El Paso',
    category: 'Defense Tech',
    aliases: ['caci international', 'caci', 'caci inc', 'caci intelligence'],
    keywords: ['sigint processing', 'army intelligence systems', 'wsmr it services', 'intelligence brigade it', 'cyber operations dod'],
    naicsCodes: ['541512', '541519', '541690'],
    ikerScore: 81,
  },
  {
    id: 'ep-vectrus-ep',
    name: 'V2X (Vectrus) Fort Bliss',
    category: 'Defense Tech',
    aliases: ['vectrus', 'v2x', 'v2x gov', 'vectrus fort bliss', 'logcap v vectrus'],
    keywords: ['logcap v fort bliss', 'base operations fort bliss', 'facilities management military', 'installation support contract'],
    naicsCodes: ['561210', '237990', '541330'],
    ikerScore: 77,
  },

  // ── Cybersecurity ──────────────────────────────────────────────────────────
  {
    id: 'ep-palantir',
    name: 'Palantir Technologies (Army)',
    category: 'Defense Tech',
    aliases: ['palantir army', 'palantir aip', 'palantir gotham army', 'army aip'],
    keywords: ['army aip platform', 'palantir foundry army', 'gotham intelligence', 'titan ground station', 'army ai platform'],
    naicsCodes: ['541511', '541715', '541512'],
    ikerScore: 89,
  },
  {
    id: 'ep-crowdstrike',
    name: 'CrowdStrike Federal',
    category: 'Defense Tech',
    aliases: ['crowdstrike', 'crowdstrike federal', 'falcon platform dod', 'crowdstrike disa'],
    keywords: ['falcon endpoint dod', 'disa hbss replacement', 'cbp network security', 'army arcyber threat intel', 'edr federal'],
    naicsCodes: ['541512', '541519'],
    ikerScore: 83,
  },
  {
    id: 'ep-sievert',
    name: 'Sievert Larson Cyber',
    category: 'Defense Tech',
    aliases: ['sievert larson', 'sievert larson cyber', 'slc cyber'],
    keywords: ['fort bliss cyber range', 'red team military', 'ics security el paso', 'cisa assessment team', 'ot security utilities'],
    naicsCodes: ['541512', '541519', '541690'],
    ikerScore: 65,
  },
  {
    id: 'ep-irontower',
    name: 'Iron Tower Security',
    category: 'Defense Tech',
    aliases: ['iron tower security', 'iron tower', 'irontower'],
    keywords: ['zero trust maquiladora', 'cross border network security', 'bi-national zero trust', 'maquiladora cybersecurity'],
    naicsCodes: ['541512', '541519'],
    ikerScore: 55,
  },

  // ── Healthcare IT ──────────────────────────────────────────────────────────
  {
    id: 'ep-elpaso-childrens',
    name: "El Paso Children's Hospital",
    category: 'Health Tech',
    aliases: ["el paso children's hospital", 'epch', 'ep childrens', 'el paso pediatric'],
    keywords: ['pediatric sepsis ai', 'childrens telehealth west texas', 'pediatric remote monitoring', 'mychart bilingual pediatric'],
    naicsCodes: ['622110', '541512'],
    ikerScore: 72,
  },
  {
    id: 'ep-wbamc',
    name: 'William Beaumont Army Medical Center',
    category: 'Health Tech',
    aliases: ['wbamc', 'william beaumont', 'william beaumont army', 'beaumont army medical'],
    keywords: ['mhs genesis wbamc', 'military health ehr', 'combat casualty simulation', 'army medical readiness data'],
    naicsCodes: ['622110', '541512', '611430'],
    ikerScore: 76,
  },
  {
    id: 'ep-caremore',
    name: 'CareMore Health El Paso',
    category: 'Health Tech',
    aliases: ['caremore', 'caremore health', 'caremore el paso'],
    keywords: ['medicare advantage care management', 'remote cardiac monitoring', 'hedis quality el paso', 'hispanic medicare care management'],
    naicsCodes: ['621498', '541512'],
    ikerScore: 68,
  },

  // ── Energy ─────────────────────────────────────────────────────────────────
  {
    id: 'ep-gridworks',
    name: 'GridWorks Energy',
    category: 'Energy Tech',
    aliases: ['gridworks energy', 'gridworks ep', 'gridworks'],
    keywords: ['epe derms', 'fort bliss microgrid', 'grid edge management', 'battery storage el paso', 'solar plus storage military'],
    naicsCodes: ['221122', '238210', '541330'],
    ikerScore: 62,
  },
  {
    id: 'ep-abengoa',
    name: 'Abengoa Solar El Paso',
    category: 'Energy Tech',
    aliases: ['abengoa', 'abengoa solar', 'abengoa el paso'],
    keywords: ['csp west texas', 'epe solar ppa', 'crez renewable compliance', 'utility solar epe'],
    naicsCodes: ['221114', '237130'],
    ikerScore: 66,
  },

  // ── Manufacturing ──────────────────────────────────────────────────────────
  {
    id: 'ep-borgwarner',
    name: 'BorgWarner El Paso',
    category: 'Manufacturing Tech',
    aliases: ['borgwarner', 'borg warner', 'borgwarner el paso', 'borgwarner juarez'],
    keywords: ['ev thermal management juarez', 'gm ultium borgwarner', 'emoctor components', 'ev components maquiladora'],
    naicsCodes: ['336390', '336300'],
    ikerScore: 70,
  },
  {
    id: 'ep-commscope',
    name: 'CommScope El Paso',
    category: 'Manufacturing Tech',
    aliases: ['commscope', 'commscope el paso', 'commscope juarez'],
    keywords: ['fiber optic assembly el paso', '5g hardware manufacturing', 'rf connectivity defense', 'telecom components maquiladora'],
    naicsCodes: ['335921', '334220'],
    ikerScore: 69,
  },
  {
    id: 'ep-sanmina',
    name: 'Sanmina Corporation El Paso',
    category: 'Manufacturing Tech',
    aliases: ['sanmina', 'sanmina corporation', 'sanmina el paso', 'sanmina juarez'],
    keywords: ['medical device assembly juarez', 'ipc class iii pcb', 'defense electronics ems', 'medtronic subcontract'],
    naicsCodes: ['334418', '334419'],
    ikerScore: 73,
  },

  // ── Logistics ──────────────────────────────────────────────────────────────
  {
    id: 'ep-ontrac',
    name: 'OnTrac El Paso',
    category: 'Logistics',
    aliases: ['ontrac', 'lasership el paso', 'ontrac el paso'],
    keywords: ['last mile el paso', 'regional parcel carrier west texas', 'amazon sfp carrier', 'cross border last mile'],
    naicsCodes: ['492110'],
    ikerScore: 64,
  },
  {
    id: 'ep-globaltranz',
    name: 'GlobalTranz El Paso',
    category: 'Logistics',
    aliases: ['globaltranz', 'global tranz', 'globaltranz el paso'],
    keywords: ['cross border freight brokerage', 'us mexico truckload', 'cold chain el paso', 'bnsf intermodal el paso'],
    naicsCodes: ['488510', '541614'],
    ikerScore: 67,
  },
  {
    id: 'ep-nuvocargo',
    name: 'Nuvocargo',
    category: 'Border Tech',
    aliases: ['nuvocargo', 'nuvo cargo', 'nuvocargo freight'],
    keywords: ['digital freight us mexico', 'pedimento automation', 'cross border working capital', 'a16z freight forwarder'],
    naicsCodes: ['488510', '541511'],
    ikerScore: 72,
  },
  {
    id: 'ep-samsara-ep',
    name: 'Samsara Border Fleet Intelligence',
    category: 'Logistics',
    aliases: ['samsara border', 'samsara fleet el paso', 'samsara cross border'],
    keywords: ['c-tpat gps tracking', 'cross border eld compliance', 'trusted shipper telematics', 'border carrier fleet management'],
    naicsCodes: ['334290', '541511'],
    ikerScore: 71,
  },

  // ── AI / R&D ───────────────────────────────────────────────────────────────
  {
    id: 'ep-palantir-local',
    name: 'Palantir Technologies (Local)',
    category: 'Defense Tech',
    aliases: ['palantir local', 'palantir el paso office', 'palantir foundry local'],
    keywords: ['army aip fort bliss', 'foundry logistics army', 'titan palantir integration', 'operational planning ai army'],
    naicsCodes: ['541511', '541715'],
    ikerScore: 89,
  },
  {
    id: 'ep-cogility',
    name: 'Cogility Corp',
    category: 'AI / R&D',
    aliases: ['cogility', 'cogility corp', 'cobweb cogility'],
    keywords: ['cobweb platform army', 'army g-4 readiness analytics', 'defense logistics ai', 'sbir dod readiness', 'logsa integration'],
    naicsCodes: ['541715', '541512'],
    ikerScore: 62,
  },
  {
    id: 'ep-kpmg',
    name: 'KPMG El Paso',
    category: 'Defense Tech',
    aliases: ['kpmg el paso', 'kpmg juarez', 'kpmg maquiladora'],
    keywords: ['usmca advisory kpmg', 'maquiladora compliance consulting', 'digital transformation maquiladora', 'critical infrastructure advisory'],
    naicsCodes: ['541611', '541219', '541512'],
    ikerScore: 72,
  },
  {
    id: 'ep-elpasoinnovation',
    name: 'El Paso Innovation Hub (Entrada)',
    category: 'AI / R&D',
    aliases: ['entrada el paso', 'el paso innovation hub', 'ep innovation hub', 'entrada startup'],
    keywords: ['sbir el paso startup', 'border tech incubator', 'utep tech transfer', 'defense dual use startup', 'dhs sbir el paso'],
    naicsCodes: ['926150', '541715'],
    ikerScore: 55,
  },

  // ── Construction/Infrastructure ────────────────────────────────────────────
  {
    id: 'ep-fluor',
    name: 'Fluor Corporation',
    category: 'Defense Tech',
    aliases: ['fluor', 'fluor corp', 'fluor government'],
    keywords: ['logcap fort bliss', 'base operations construction', 'military construction'],
    naicsCodes: ['237990', '236220'],
    ikerScore: 85,
  },
  {
    id: 'ep-aecom',
    name: 'AECOM',
    category: 'Defense Tech',
    aliases: ['aecom', 'aecom technical services'],
    keywords: ['environmental remediation fort bliss', 'military engineering', 'range modernization'],
    naicsCodes: ['541330', '562910'],
    ikerScore: 84,
  },
  {
    id: 'ep-kiewit',
    name: 'Kiewit Corporation',
    category: 'Defense Tech',
    aliases: ['kiewit', 'kiewit infrastructure'],
    keywords: ['border infrastructure', 'highway construction el paso', 'bridge construction'],
    naicsCodes: ['237310', '237990'],
    ikerScore: 82,
  },
  {
    id: 'ep-hensel-phelps',
    name: 'Hensel Phelps',
    category: 'Defense Tech',
    aliases: ['hensel phelps', 'hensel-phelps'],
    keywords: ['military construction fort bliss', 'dod facilities', 'army barracks construction'],
    naicsCodes: ['236220', '236210'],
    ikerScore: 80,
  },
  {
    id: 'ep-sundt',
    name: 'Sundt Construction',
    category: 'Defense Tech',
    aliases: ['sundt', 'sundt construction'],
    keywords: ['el paso construction', 'infrastructure southwest', 'transportation construction'],
    naicsCodes: ['237310', '236220'],
    ikerScore: 76,
  },

  // ── Professional Services ──────────────────────────────────────────────────
  {
    id: 'ep-pwc',
    name: 'PricewaterhouseCoopers',
    category: 'Border Tech',
    aliases: ['pwc', 'pricewaterhousecoopers', 'pwc el paso'],
    keywords: ['maquiladora tax advisory', 'usmca compliance', 'cross border transfer pricing'],
    naicsCodes: ['541211', '541219'],
    ikerScore: 83,
  },
  {
    id: 'ep-ey',
    name: 'Ernst & Young',
    category: 'Border Tech',
    aliases: ['ey', 'ernst young', 'ernst & young'],
    keywords: ['usmca customs advisory', 'maquiladora audit', 'cross border supply chain tax'],
    naicsCodes: ['541211', '541219'],
    ikerScore: 83,
  },
  {
    id: 'ep-icf',
    name: 'ICF International',
    category: 'Defense Tech',
    aliases: ['icf', 'icf international', 'icf consulting'],
    keywords: ['dhs consulting', 'border security analytics', 'cbp program management'],
    naicsCodes: ['541611', '541690'],
    ikerScore: 78,
  },
  {
    id: 'ep-maxar',
    name: 'Maxar Technologies',
    category: 'Defense Tech',
    aliases: ['maxar', 'maxar technologies', 'digitalglobe'],
    keywords: ['geospatial intelligence', 'satellite imagery fort bliss', 'geoint defense'],
    naicsCodes: ['334511', '541715'],
    ikerScore: 82,
  },
  {
    id: 'ep-peraton',
    name: 'Peraton (formerly Perspecta)',
    category: 'Defense Tech',
    aliases: ['peraton', 'perspecta', 'peraton defense'],
    keywords: ['defense it services', 'army network enterprise', 'disa support'],
    naicsCodes: ['541512', '541519'],
    ikerScore: 80,
  },

  // ── Transport/Freight ──────────────────────────────────────────────────────
  {
    id: 'ep-bnsf',
    name: 'BNSF Railway',
    category: 'Logistics',
    aliases: ['bnsf', 'bnsf railway', 'burlington northern'],
    keywords: ['intermodal el paso', 'rail freight border', 'bnsf juarez rail'],
    naicsCodes: ['482111'],
    ikerScore: 88,
  },
  {
    id: 'ep-ups',
    name: 'UPS',
    category: 'Logistics',
    aliases: ['ups', 'united parcel service', 'ups el paso'],
    keywords: ['package logistics el paso', 'ups customs brokerage', 'cross border parcel'],
    naicsCodes: ['492110', '488510'],
    ikerScore: 87,
  },
  {
    id: 'ep-werner',
    name: 'Werner Enterprises',
    category: 'Logistics',
    aliases: ['werner', 'werner enterprises', 'werner trucking'],
    keywords: ['cross border trucking', 'us mexico ltl', 'truckload freight'],
    naicsCodes: ['484121', '484122'],
    ikerScore: 78,
  },
  {
    id: 'ep-jbhunt',
    name: 'J.B. Hunt Transport',
    category: 'Logistics',
    aliases: ['jb hunt', 'j.b. hunt', 'jbhunt'],
    keywords: ['intermodal freight', 'dedicated contract carriage', 'cross border drayage'],
    naicsCodes: ['484121', '488510'],
    ikerScore: 82,
  },
  {
    id: 'ep-odfl',
    name: 'Old Dominion Freight Line',
    category: 'Logistics',
    aliases: ['old dominion', 'odfl', 'old dominion freight'],
    keywords: ['ltl carrier el paso', 'less than truckload', 'freight consolidation'],
    naicsCodes: ['484122'],
    ikerScore: 80,
  },

  // ── Government/Military ────────────────────────────────────────────────────
  {
    id: 'ep-micc',
    name: 'Fort Bliss MICC',
    category: 'Defense Tech',
    aliases: ['micc', 'mission installation contracting command', 'fort bliss contracting'],
    keywords: ['army contracting fort bliss', 'military procurement', 'installation support'],
    naicsCodes: ['928110'],
    ikerScore: 78,
  },
  {
    id: 'ep-dea-epic',
    name: 'DEA EPIC',
    category: 'Defense Tech',
    aliases: ['dea epic', 'el paso intelligence center', 'epic dea'],
    keywords: ['drug intelligence', 'border interdiction analytics', 'cartel intelligence'],
    naicsCodes: ['922130'],
    ikerScore: 74,
  },
  {
    id: 'ep-cbp-sector',
    name: 'CBP El Paso Sector',
    category: 'Border Tech',
    aliases: ['cbp el paso', 'border patrol el paso', 'cbp sector'],
    keywords: ['border enforcement technology', 'surveillance border', 'cbp autonomous systems'],
    naicsCodes: ['922120'],
    ikerScore: 76,
  },
  {
    id: 'ep-usace',
    name: 'US Army Corps of Engineers',
    category: 'Defense Tech',
    aliases: ['usace', 'army corps engineers', 'corps of engineers'],
    keywords: ['military construction management', 'range modernization', 'environmental compliance'],
    naicsCodes: ['237990', '541330'],
    ikerScore: 78,
  },
  {
    id: 'ep-wsmr',
    name: 'White Sands Missile Range',
    category: 'Defense Tech',
    aliases: ['wsmr', 'white sands', 'white sands missile range'],
    keywords: ['missile testing', 'directed energy testing', 'hypersonic test range'],
    naicsCodes: ['928110', '927110'],
    ikerScore: 80,
  },

  // ── Local Tech/Startups ────────────────────────────────────────────────────
  {
    id: 'ep-strangeworks',
    name: 'Strangeworks',
    category: 'AI / R&D',
    aliases: ['strangeworks', 'strangeworks quantum'],
    keywords: ['quantum computing army', 'quantum sdk', 'quantum as a service'],
    naicsCodes: ['541715', '511210'],
    ikerScore: 62,
  },
  {
    id: 'ep-evolv',
    name: 'Evolv Technology',
    category: 'Border Tech',
    aliases: ['evolv', 'evolv technology', 'evolv weapons detection'],
    keywords: ['ai weapons detection', 'touchless security screening', 'border port screening'],
    naicsCodes: ['334290', '561621'],
    ikerScore: 65,
  },
  {
    id: 'ep-blackhorse',
    name: 'Black Horse Group',
    category: 'Defense Tech',
    aliases: ['black horse group', 'blackhorse defense'],
    keywords: ['defense consulting el paso', 'army advisory', 'military transition'],
    naicsCodes: ['541611', '541690'],
    ikerScore: 58,
  },
  {
    id: 'ep-smartrosetta',
    name: 'Smart Rosetta',
    category: 'AI / R&D',
    aliases: ['smart rosetta', 'smartrosetta'],
    keywords: ['bilingual nlp', 'spanish english ai', 'cross border translation ai'],
    naicsCodes: ['541715', '511210'],
    ikerScore: 55,
  },
  {
    id: 'ep-teksynap',
    name: 'TekSynap',
    category: 'Defense Tech',
    aliases: ['teksynap', 'tek synap'],
    keywords: ['defense it managed services', 'army network operations', 'disa support'],
    naicsCodes: ['541512', '541519'],
    ikerScore: 70,
  },

  // ── Business/Institutions ──────────────────────────────────────────────────
  {
    id: 'ep-helenoftroy',
    name: 'Helen of Troy',
    category: 'Manufacturing Tech',
    aliases: ['helen of troy', 'helen troy', 'hot'],
    keywords: ['consumer goods el paso hq', 'housewares manufacturing', 'otc health products'],
    naicsCodes: ['335210', '339994'],
    ikerScore: 75,
  },
  {
    id: 'ep-delek',
    name: 'Delek US Holdings',
    category: 'Energy Tech',
    aliases: ['delek', 'delek us', 'western refining'],
    keywords: ['el paso refinery', 'petroleum refining', 'fuel logistics border'],
    naicsCodes: ['324110', '424710'],
    ikerScore: 74,
  },
  {
    id: 'ep-borderplex',
    name: 'Borderplex Alliance',
    category: 'Border Tech',
    aliases: ['borderplex', 'borderplex alliance', 'ep economic development'],
    keywords: ['el paso economic development', 'border region investment', 'business attraction'],
    naicsCodes: ['926150', '813910'],
    ikerScore: 68,
  },
  {
    id: 'ep-utep-kiran',
    name: 'UTEP Kiran Research Institute',
    category: 'University',
    aliases: ['kiran research', 'utep kiran', 'utep research institute'],
    keywords: ['utep research', 'border health research', 'environmental research el paso'],
    naicsCodes: ['611310', '541715'],
    ikerScore: 70,
  },
  {
    id: 'ep-ttuhsc-ep',
    name: 'Texas Tech HSC El Paso',
    category: 'Health Tech',
    aliases: ['ttuhsc el paso', 'texas tech health el paso', 'paul foster school medicine'],
    keywords: ['medical education el paso', 'clinical research border', 'hispanic health disparities'],
    naicsCodes: ['611310', '621111'],
    ikerScore: 73,
  },

];
