// src/lib/intelligence/nxt-entities.ts
// NXT LINK entity registry — El Paso defense/border/supply-chain tech ecosystem.
// Used by the signal engine to match news headlines to known vendors,
// detect contract awards, and correlate market signals.

import { NXT_ENTITIES_ELPASO } from './nxt-entities-elpaso';

export type EntityCategory =
  | 'Defense Tech'
  | 'Border Tech'
  | 'Logistics'
  | 'Water Tech'
  | 'Energy Tech'
  | 'Health Tech'
  | 'AI / R&D'
  | 'University'
  | 'Robotics & Automation'
  | 'Warehouse Automation'
  | 'Manufacturing Tech'
  | 'Industrial AI'
  | 'Logistics Platform'
  | 'Supply Chain Software';

export type NxtEntity = {
  id: string;                   // Matches entity_id in el-paso-vendors.ts
  name: string;
  category: EntityCategory;
  aliases: string[];            // All lowercased name variants for matching
  keywords: string[];           // Topic keywords linked to this entity
  naicsCodes?: string[];        // For SAM.gov contract matching
  ikerScore?: number;           // Baseline IKER score (0–100)
};

// ─── Vendor Entities ─────────────────────────────────────────────────────────

export const NXT_ENTITIES: NxtEntity[] = [
  // ── Defense Tech ────────────────────────────────────────────────────────────
  {
    id: 'l3harris',
    name: 'L3Harris',
    category: 'Defense Tech',
    aliases: ['l3harris', 'l3 harris', 'harris corporation', 'l3 technologies', 'l3t'],
    keywords: ['c4isr', 'tactical radio', 'communication systems', 'electronic warfare', 'fort bliss c4isr', 'patriot', 'antennas'],
    naicsCodes: ['334511', '334220', '541330'],
    ikerScore: 88,
  },
  {
    id: 'raytheon',
    name: 'Raytheon',
    category: 'Defense Tech',
    aliases: ['raytheon', 'rtx', 'raytheon technologies', 'collins aerospace', 'pratt whitney', 'raytheon missiles'],
    keywords: ['patriot missile', 'air defense', 'missile systems', 'guided munitions', 'radar systems', 'hypersonic'],
    naicsCodes: ['336414', '334511', '541330'],
    ikerScore: 91,
  },
  {
    id: 'saic',
    name: 'SAIC',
    category: 'Defense Tech',
    aliases: ['saic', 'science applications international', 'science applications'],
    keywords: ['gcss-army', 'army modernization', 'logistics it', 'enterprise it', 'defense it', 'army erp'],
    naicsCodes: ['541512', '541519', '541330'],
    ikerScore: 84,
  },
  {
    id: 'leidos',
    name: 'Leidos',
    category: 'Defense Tech',
    aliases: ['leidos', 'leidos holdings', 'saic leidos'],
    keywords: ['defense analytics', 'health it', 'civilian it', 'airport security', 'intelligence solutions'],
    naicsCodes: ['541512', '541330', '611430'],
    ikerScore: 82,
  },
  {
    id: 'booz-allen',
    name: 'Booz Allen Hamilton',
    category: 'Defense Tech',
    aliases: ['booz allen', 'booz allen hamilton', 'bah', 'booz hamilton'],
    keywords: ['ai ml defense', 'cleared personnel', 'digital transformation', 'cyber analytics', 'mission analytics'],
    naicsCodes: ['541611', '541512', '541690'],
    ikerScore: 85,
  },
  {
    id: 'boeing',
    name: 'Boeing Defense',
    category: 'Defense Tech',
    aliases: ['boeing', 'boeing defense', 'boeing military'],
    keywords: ['apache helicopter', 'ah-64', 'chinook', 'helicopter simulator', 'rotary wing', 'unmanned systems'],
    naicsCodes: ['336411', '336413', '541330'],
    ikerScore: 79,
  },
  {
    id: 'mantech',
    name: 'ManTech',
    category: 'Defense Tech',
    aliases: ['mantech', 'man tech international'],
    keywords: ['cyber readiness', 'army cyber', 'it modernization', 'mission solutions'],
    naicsCodes: ['541512', '541519'],
    ikerScore: 76,
  },
  {
    id: 'gdit',
    name: 'GDIT',
    category: 'Defense Tech',
    aliases: ['gdit', 'general dynamics it', 'general dynamics information technology'],
    keywords: ['cloud migration', 'digital modernization', 'enterprise cloud', 'dod cloud'],
    naicsCodes: ['541512', '541519', '541330'],
    ikerScore: 80,
  },
  {
    id: 'mesaai',
    name: 'MesaAI',
    category: 'AI / R&D',
    aliases: ['mesaai', 'mesa ai', 'mesa artificial intelligence'],
    keywords: ['battlefield ai', 'edge ai', 'autonomous systems', 'computer vision defense'],
    naicsCodes: ['541715', '541512'],
    ikerScore: 71,
  },

  // ── Border Tech ─────────────────────────────────────────────────────────────
  {
    id: 'crossingiq',
    name: 'CrossingIQ',
    category: 'Border Tech',
    aliases: ['crossingiq', 'crossing iq', 'crossiq'],
    keywords: ['wait time prediction', 'port of entry ai', 'cbp ai', 'border wait', 'paso del norte'],
    naicsCodes: ['541511', '541519'],
    ikerScore: 83,
  },
  {
    id: 'tradesync',
    name: 'TradeSync Border',
    category: 'Border Tech',
    aliases: ['tradesync', 'trade sync border', 'tradesync border'],
    keywords: ['usmca certificate', 'maquiladora compliance', 'customs software', 'ace platform', 'certificate of origin'],
    naicsCodes: ['541511', '561499'],
    ikerScore: 77,
  },
  {
    id: 'cbpass',
    name: 'CBPASS Systems',
    category: 'Border Tech',
    aliases: ['cbpass', 'cb pass', 'cbpass systems'],
    keywords: ['facial recognition border', 'cbp biometric', 'gsa schedule border', 'biometric screening'],
    naicsCodes: ['334519', '541512'],
    ikerScore: 74,
  },
  {
    id: 'bordertech',
    name: 'BorderTech',
    category: 'Border Tech',
    aliases: ['bordertech', 'border tech'],
    keywords: ['rfid border', 'fast program', 'trusted traveler', 'border rfid credentialing'],
    naicsCodes: ['334519', '541512'],
    ikerScore: 70,
  },
  {
    id: 'portlogic',
    name: 'PortLogic',
    category: 'Border Tech',
    aliases: ['portlogic', 'port logic'],
    keywords: ['ace integration', 'customs processing', 'commercial lane', 'port efficiency'],
    naicsCodes: ['541511', '488510'],
    ikerScore: 68,
  },

  // ── Logistics & Supply Chain ────────────────────────────────────────────────
  {
    id: 'fedex',
    name: 'FedEx',
    category: 'Logistics',
    aliases: ['fedex', 'federal express', 'fedex ground', 'fedex freight'],
    keywords: ['last mile delivery', 'freight network', 'supply chain el paso', 'cross-border freight'],
    naicsCodes: ['492110', '488510'],
    ikerScore: 75,
  },
  {
    id: 'cargonerve',
    name: 'CargoNerve',
    category: 'Logistics',
    aliases: ['cargonerve', 'cargo nerve'],
    keywords: ['cross-border eta', 'customs delay forecast', 'freight risk', 'delay prediction'],
    naicsCodes: ['541511', '488510'],
    ikerScore: 72,
  },

  // ── Water Technology ────────────────────────────────────────────────────────
  {
    id: 'elpaso-water',
    name: 'El Paso Water',
    category: 'Water Tech',
    aliases: ['el paso water', 'epwu', 'el paso water utilities', 'el paso water utility'],
    keywords: ['desalination', 'desal', 'water reuse', 'aquifer', 'water treatment', 'brackish water'],
    naicsCodes: ['221310', '237110'],
    ikerScore: 86,
  },
  {
    id: 'aridtech',
    name: 'AridTech',
    category: 'Water Tech',
    aliases: ['aridtech', 'arid tech'],
    keywords: ['atmospheric water', 'water from air', 'field water', 'sbir water', 'dod water'],
    naicsCodes: ['333318', '541715'],
    ikerScore: 78,
  },

  // ── Energy Technology ────────────────────────────────────────────────────────
  {
    id: 'elpaso-electric',
    name: 'El Paso Electric',
    category: 'Energy Tech',
    aliases: ['el paso electric', 'epe', 'el paso electric company', 'epelectric'],
    keywords: ['grid modernization', 'capex electric', 'smart grid', 'transmission upgrade', 'ercot'],
    naicsCodes: ['221122', '237130'],
    ikerScore: 81,
  },
  {
    id: 'nextera',
    name: 'NextEra Energy',
    category: 'Energy Tech',
    aliases: ['nextera', 'nextera energy', 'next era', 'fpl group'],
    keywords: ['battery storage', 'solar west texas', 'renewable energy', 'wind energy', 'ercot storage'],
    naicsCodes: ['221114', '221115'],
    ikerScore: 83,
  },
  {
    id: 'sunpower',
    name: 'SunPower',
    category: 'Energy Tech',
    aliases: ['sunpower', 'sun power', 'sunpower solar'],
    keywords: ['residential solar', 'commercial solar', 'solar installation', 'maquiladora solar', 'pv panels'],
    naicsCodes: ['221114', '238210'],
    ikerScore: 74,
  },

  // ── Health Technology ────────────────────────────────────────────────────────
  {
    id: 'umc',
    name: 'UMC El Paso',
    category: 'Health Tech',
    aliases: ['umc', 'university medical center', 'umc el paso', 'umc health system'],
    keywords: ['ehr modernization', 'hospital it', 'telemedicine', 'health informatics', 'medical center'],
    naicsCodes: ['622110', '541512'],
    ikerScore: 79,
  },

  // ── University / R&D ────────────────────────────────────────────────────────
  {
    id: 'utep',
    name: 'UTEP',
    category: 'University',
    aliases: ['utep', 'university of texas el paso', 'ut el paso', 'utep research'],
    keywords: ['nsf grant', 'research grant', 'tech transfer', 'university research', 'stem border', 'utep ai lab'],
    naicsCodes: ['611310'],
    ikerScore: 88,
  },

  // ── Additional Defense Tech ──────────────────────────────────────────────────
  {
    id: 'northrop-grumman',
    name: 'Northrop Grumman',
    category: 'Defense Tech',
    aliases: ['northrop grumman', 'northrop', 'ngc', 'northrop grumman corp'],
    keywords: ['b-21 raider', 'space systems', 'cyber defense', 'autonomous systems', 'missile defense', 'c2 systems'],
    naicsCodes: ['336411', '334511', '541330'],
    ikerScore: 90,
  },
  {
    id: 'lockheed-martin',
    name: 'Lockheed Martin',
    category: 'Defense Tech',
    aliases: ['lockheed martin', 'lockheed', 'lmt', 'lockheed martin corp'],
    keywords: ['f-35', 'thaad', 'sikorsky', 'skunk works', 'space systems', 'hypersonic weapons', 'battlefield management'],
    naicsCodes: ['336411', '336414', '334511'],
    ikerScore: 93,
  },
  {
    id: 'general-dynamics',
    name: 'General Dynamics',
    category: 'Defense Tech',
    aliases: ['general dynamics', 'gd', 'gdls', 'general dynamics land systems', 'general dynamics mission systems'],
    keywords: ['m1 abrams', 'stryker', 'land systems', 'mission systems', 'nuclear submarines', 'armored vehicles'],
    naicsCodes: ['336992', '334511', '541512'],
    ikerScore: 89,
  },
  {
    id: 'bae-systems',
    name: 'BAE Systems',
    category: 'Defense Tech',
    aliases: ['bae systems', 'bae', 'bae systems inc'],
    keywords: ['electronic systems', 'intelligence surveillance', 'electronic warfare', 'armored vehicles', 'cyber intelligence'],
    naicsCodes: ['334511', '336992', '541330'],
    ikerScore: 85,
  },
  {
    id: 'textron',
    name: 'Textron Systems',
    category: 'Defense Tech',
    aliases: ['textron', 'textron systems', 'bell textron', 'textron defense'],
    keywords: ['bell helicopter', 'v-22 osprey', 'unmanned ground vehicle', 'shadow uav', 'aerosonde'],
    naicsCodes: ['336413', '336411', '541330'],
    ikerScore: 82,
  },
  {
    id: 'caci',
    name: 'CACI International',
    category: 'Defense Tech',
    aliases: ['caci', 'caci international', 'caci inc'],
    keywords: ['intelligence solutions', 'cyber operations', 'signals intelligence', 'enterprise it defense', 'it services dod'],
    naicsCodes: ['541512', '541519', '541690'],
    ikerScore: 80,
  },
  {
    id: 'l3-oma',
    name: 'L3 OMA',
    category: 'Defense Tech',
    aliases: ['l3 oma', 'l3 aviation', 'l3 technologies oma'],
    keywords: ['aviation maintenance', 'helicopter maintenance', 'fleet support', 'rotary wing maintenance'],
    naicsCodes: ['488190', '336413'],
    ikerScore: 75,
  },
  {
    id: 'drs-technologies',
    name: 'DRS Technologies',
    category: 'Defense Tech',
    aliases: ['drs technologies', 'drs', 'leonardo drs', 'drs defense'],
    keywords: ['vetronics', 'power electronics defense', 'thermal sights', 'network systems defense'],
    naicsCodes: ['334511', '335311', '541330'],
    ikerScore: 78,
  },
  {
    id: 'cubic-defense',
    name: 'Cubic Defense',
    category: 'Defense Tech',
    aliases: ['cubic defense', 'cubic corporation', 'cubic'],
    keywords: ['live training', 'combat training centers', 'iess', 'training systems', 'force on force'],
    naicsCodes: ['611699', '334511', '541512'],
    ikerScore: 77,
  },
  {
    id: 'vectrus',
    name: 'Vectrus',
    category: 'Defense Tech',
    aliases: ['vectrus', 'v2x', 'vectrus systems'],
    keywords: ['base operations', 'facilities management military', 'infrastructure support', 'converge v2x'],
    naicsCodes: ['561210', '237990', '541330'],
    ikerScore: 74,
  },
  {
    id: 'amentum',
    name: 'Amentum',
    category: 'Defense Tech',
    aliases: ['amentum', 'aecom management services', 'amentum services'],
    keywords: ['nuclear operations', 'defense program management', 'technical services government', 'environmental remediation'],
    naicsCodes: ['541330', '541690', '562910'],
    ikerScore: 76,
  },
  {
    id: 'perspecta',
    name: 'Perspecta',
    category: 'Defense Tech',
    aliases: ['perspecta', 'dxc government', 'perspecta inc'],
    keywords: ['dod it modernization', 'cloud services government', 'intelligence community it'],
    naicsCodes: ['541512', '541519'],
    ikerScore: 73,
  },
  {
    id: 'elbit-systems',
    name: 'Elbit Systems of America',
    category: 'Defense Tech',
    aliases: ['elbit', 'elbit systems', 'elbit systems of america'],
    keywords: ['night vision', 'helmet mounted display', 'ivas competing', 'soldier systems', 'uas'],
    naicsCodes: ['334511', '334519', '541330'],
    ikerScore: 79,
  },

  // ── Robotics & Automation ────────────────────────────────────────────────────
  {
    id: 'boston-dynamics',
    name: 'Boston Dynamics',
    category: 'Robotics & Automation',
    aliases: ['boston dynamics', 'boston dynamics inc', 'spot robot'],
    keywords: ['spot robot', 'atlas humanoid', 'stretch robot', 'legged robot', 'mobile manipulation', 'autonomous inspection'],
    naicsCodes: ['333249', '541715'],
    ikerScore: 82,
  },
  {
    id: 'kuka',
    name: 'KUKA',
    category: 'Robotics & Automation',
    aliases: ['kuka', 'kuka robotics', 'kuka ag', 'kuka systems'],
    keywords: ['industrial robot arm', 'welding robot', 'collaborative robot', 'kuka kr', 'robot integration'],
    naicsCodes: ['333249', '333514'],
    ikerScore: 80,
  },
  {
    id: 'abb-robotics',
    name: 'ABB Robotics',
    category: 'Robotics & Automation',
    aliases: ['abb robotics', 'abb', 'abb inc', 'abb group robotics'],
    keywords: ['irb robot', 'cobot', 'power and automation', 'robot arm', 'yumi robot', 'motion control'],
    naicsCodes: ['333249', '335313', '541330'],
    ikerScore: 83,
  },
  {
    id: 'fanuc',
    name: 'FANUC',
    category: 'Robotics & Automation',
    aliases: ['fanuc', 'fanuc america', 'fanuc corporation', 'fanuc robotics'],
    keywords: ['cnc machine', 'robot arm manufacturing', 'servo motor', 'roboshot', 'collaborative robot fanuc'],
    naicsCodes: ['333249', '333514'],
    ikerScore: 84,
  },
  {
    id: 'yaskawa',
    name: 'Yaskawa',
    category: 'Robotics & Automation',
    aliases: ['yaskawa', 'yaskawa electric', 'yaskawa motoman', 'motoman'],
    keywords: ['motoman robot', 'servo drives', 'ac drives', 'robot welding', 'arc welding robot'],
    naicsCodes: ['333249', '335312'],
    ikerScore: 81,
  },
  {
    id: 'universal-robots',
    name: 'Universal Robots',
    category: 'Robotics & Automation',
    aliases: ['universal robots', 'ur robots', 'ur5', 'ur10', 'ur3', 'universal robots as'],
    keywords: ['cobot', 'collaborative robot', 'easy programming robot', 'small robot arm', 'ur series'],
    naicsCodes: ['333249'],
    ikerScore: 79,
  },
  {
    id: 'omron-robotics',
    name: 'Omron Robotics',
    category: 'Robotics & Automation',
    aliases: ['omron robotics', 'omron', 'omron automation', 'adept technologies'],
    keywords: ['mobile robot', 'ld series robot', 'autonomous mobile robot', 'plc automation', 'vision systems'],
    naicsCodes: ['333249', '334515'],
    ikerScore: 77,
  },
  {
    id: 'locus-robotics',
    name: 'Locus Robotics',
    category: 'Robotics & Automation',
    aliases: ['locus robotics', 'locus robot', 'locusbots'],
    keywords: ['warehouse robot', 'order picking robot', 'amr picking', 'human robot collaboration warehouse'],
    naicsCodes: ['333249', '493110'],
    ikerScore: 72,
  },
  {
    id: 'greyorange',
    name: 'GreyOrange',
    category: 'Robotics & Automation',
    aliases: ['greyorange', 'grey orange', 'greyorange inc'],
    keywords: ['ranger amr', 'fulfillment robot', 'sortation robot', 'goods to person', 'warehouse ai robot'],
    naicsCodes: ['333249', '493110'],
    ikerScore: 71,
  },
  {
    id: 'fetch-robotics',
    name: 'Fetch Robotics',
    category: 'Robotics & Automation',
    aliases: ['fetch robotics', 'fetch robot', 'fetchcore'],
    keywords: ['freight robot', 'mobile robot platform', 'amr logistics', 'robot as a service'],
    naicsCodes: ['333249', '493110'],
    ikerScore: 68,
  },
  {
    id: 'geek-plus',
    name: 'Geek+',
    category: 'Robotics & Automation',
    aliases: ['geek+', 'geek plus', 'geekplus', 'geek+ robotics'],
    keywords: ['goods to person robot', 'p series robot', 'sorting robot', 'smart logistics robot'],
    naicsCodes: ['333249', '493110'],
    ikerScore: 70,
  },
  {
    id: 'covariant',
    name: 'Covariant',
    category: 'Robotics & Automation',
    aliases: ['covariant', 'covariant ai', 'covariant robotics'],
    keywords: ['robotic picking ai', 'robotic brain', 'unstructured picking', 'depalletizing robot ai'],
    naicsCodes: ['333249', '541715'],
    ikerScore: 69,
  },
  {
    id: 'agility-robotics',
    name: 'Agility Robotics',
    category: 'Robotics & Automation',
    aliases: ['agility robotics', 'digit robot', 'agility robot'],
    keywords: ['humanoid robot', 'digit humanoid', 'bipedal robot', 'warehouse humanoid'],
    naicsCodes: ['333249', '541715'],
    ikerScore: 67,
  },
  {
    id: 'mir-robots',
    name: 'MiR (Mobile Industrial Robots)',
    category: 'Robotics & Automation',
    aliases: ['mir robots', 'mobile industrial robots', 'mir amr', 'mir250', 'mir500'],
    keywords: ['autonomous mobile robot', 'internal logistics robot', 'mir fleet', 'intralogistics amr'],
    naicsCodes: ['333249'],
    ikerScore: 74,
  },
  {
    id: 'otto-motors',
    name: 'OTTO Motors',
    category: 'Robotics & Automation',
    aliases: ['otto motors', 'otto amr', 'clearpath robotics'],
    keywords: ['industrial amr', 'otto 100', 'otto 1500', 'heavy payload amr', 'factory amr'],
    naicsCodes: ['333249'],
    ikerScore: 71,
  },
  {
    id: 'seegrid',
    name: 'Seegrid',
    category: 'Robotics & Automation',
    aliases: ['seegrid', 'seegrid corp', 'seegrid robotics'],
    keywords: ['vision guided vehicle', 'vgv', 'autonomous tugger', 'pallet transport robot'],
    naicsCodes: ['333249', '493110'],
    ikerScore: 70,
  },
  {
    id: 'vecna-robotics',
    name: 'Vecna Robotics',
    category: 'Robotics & Automation',
    aliases: ['vecna robotics', 'vecna', 'vecna technologies'],
    keywords: ['pallet jack robot', 'tugger amr', 'hospital robot', 'healthcare logistics robot'],
    naicsCodes: ['333249', '622110'],
    ikerScore: 66,
  },
  {
    id: 'mujin',
    name: 'Mujin',
    category: 'Robotics & Automation',
    aliases: ['mujin', 'mujin inc', 'mujin robot'],
    keywords: ['robot intelligence platform', 'mujin controller', 'depalletizing', 'bin picking'],
    naicsCodes: ['333249', '541715'],
    ikerScore: 68,
  },
  {
    id: 'righthand-robotics',
    name: 'RightHand Robotics',
    category: 'Robotics & Automation',
    aliases: ['righthand robotics', 'right hand robotics', 'rhr'],
    keywords: ['robotic piece picking', 'gripper robot', 'e-commerce fulfillment robot', 'rh series'],
    naicsCodes: ['333249', '493110'],
    ikerScore: 65,
  },
  {
    id: 'iam-robotics',
    name: 'IAM Robotics',
    category: 'Robotics & Automation',
    aliases: ['iam robotics', 'iam robot', 'swift robot'],
    keywords: ['swift robotic picking', 'autonomous picking robot', 'mobile manipulation'],
    naicsCodes: ['333249', '493110'],
    ikerScore: 62,
  },
  {
    id: 'brightpick',
    name: 'Brightpick',
    category: 'Robotics & Automation',
    aliases: ['brightpick', 'bright pick', 'brightpick autopicker'],
    keywords: ['autopicker robot', 'goods to robot picking', 'shuttle robot', 'cube storage picking'],
    naicsCodes: ['333249', '493110'],
    ikerScore: 61,
  },
  {
    id: 'hai-robotics',
    name: 'Hai Robotics',
    category: 'Robotics & Automation',
    aliases: ['hai robotics', 'hai robot', 'haipick'],
    keywords: ['haipick system', 'case handling robot', 'acr robot', 'high bay robot'],
    naicsCodes: ['333249', '493110'],
    ikerScore: 63,
  },
  {
    id: 'attabotics',
    name: 'Attabotics',
    category: 'Robotics & Automation',
    aliases: ['attabotics', 'attabotics inc', 'attabotics 3d fulfillment'],
    keywords: ['3d fulfillment', 'vertical robot storage', 'grid robot', 'attabotics system'],
    naicsCodes: ['333249', '493110'],
    ikerScore: 60,
  },
  {
    id: 'sarcos-robotics',
    name: 'Sarcos Robotics',
    category: 'Robotics & Automation',
    aliases: ['sarcos', 'sarcos robotics', 'sarcos guardian'],
    keywords: ['exoskeleton', 'guardian xo', 'full body exoskeleton', 'industrial exosuit', 'dexterous robot'],
    naicsCodes: ['333249', '339113'],
    ikerScore: 64,
  },
  {
    id: 'vention',
    name: 'Vention',
    category: 'Robotics & Automation',
    aliases: ['vention', 'vention machine builder', 'machinebuilder.io'],
    keywords: ['machine design platform', 'robot cell builder', 'ml robot', 'custom robot cell'],
    naicsCodes: ['333249', '541512'],
    ikerScore: 59,
  },
  {
    id: 'robust-ai',
    name: 'Robust.AI',
    category: 'Robotics & Automation',
    aliases: ['robust ai', 'robust.ai', 'carter robot'],
    keywords: ['carter warehouse robot', 'cognitive robot', 'ros robot', 'adaptive warehouse robot'],
    naicsCodes: ['333249', '541715'],
    ikerScore: 58,
  },
  {
    id: 'realtime-robotics',
    name: 'Realtime Robotics',
    category: 'Robotics & Automation',
    aliases: ['realtime robotics', 'real time robotics', 'rtr motion planning'],
    keywords: ['robot motion planning', 'collision avoidance', 'rtr processor', 'multi robot coordination'],
    naicsCodes: ['541715', '333249'],
    ikerScore: 61,
  },
  {
    id: 'kawasaki-robotics',
    name: 'Kawasaki Robotics',
    category: 'Robotics & Automation',
    aliases: ['kawasaki robotics', 'kawasaki robot', 'kawasaki rs series'],
    keywords: ['painting robot', 'welding robot kawasaki', 'heavy payload robot', 'pharma robot'],
    naicsCodes: ['333249'],
    ikerScore: 76,
  },
  {
    id: 'nachi-robotics',
    name: 'Nachi Robotics',
    category: 'Robotics & Automation',
    aliases: ['nachi robotics', 'nachi', 'nachi fujikoshi'],
    keywords: ['spot welding robot', 'arc welding robot nachi', 'painting robot nachi'],
    naicsCodes: ['333249'],
    ikerScore: 72,
  },
  {
    id: 'staubli-robotics',
    name: 'Staubli Robotics',
    category: 'Robotics & Automation',
    aliases: ['staubli', 'staubli robotics', 'st\u00e4ubli'],
    keywords: ['fast robot', 'cleanroom robot', 'medical robot', 'textiles robot', 'staubli rx'],
    naicsCodes: ['333249'],
    ikerScore: 74,
  },
  {
    id: 'denso-robotics',
    name: 'Denso Robotics',
    category: 'Robotics & Automation',
    aliases: ['denso robotics', 'denso robot', 'denso wave'],
    keywords: ['small robot arm', 'vs series robot', 'cobotta cobot', 'qr code inventor robot'],
    naicsCodes: ['333249', '336390'],
    ikerScore: 73,
  },

  // ── Warehouse & Logistics Automation ────────────────────────────────────────
  {
    id: 'dematic',
    name: 'Dematic',
    category: 'Warehouse Automation',
    aliases: ['dematic', 'dematic corp', 'dematic group'],
    keywords: ['automated conveyor', 'goods to person', 'warehouse management system', 'sortation system', 'dematic multishuttle'],
    naicsCodes: ['333922', '493110', '541512'],
    ikerScore: 83,
  },
  {
    id: 'daifuku',
    name: 'Daifuku',
    category: 'Warehouse Automation',
    aliases: ['daifuku', 'daifuku co', 'daifuku americas'],
    keywords: ['automated storage retrieval', 'asrs', 'conveyor system', 'airport baggage handling', 'cleanroom automation'],
    naicsCodes: ['333922', '488119'],
    ikerScore: 82,
  },
  {
    id: 'honeywell-intelligrated',
    name: 'Honeywell Intelligrated',
    category: 'Warehouse Automation',
    aliases: ['honeywell intelligrated', 'intelligrated', 'honeywell warehouse'],
    keywords: ['integrated conveyor', 'voice directed picking', 'warehouse execution system', 'scan tunnel'],
    naicsCodes: ['333922', '493110', '541512'],
    ikerScore: 84,
  },
  {
    id: 'ssi-schaefer',
    name: 'SSI Schaefer',
    category: 'Warehouse Automation',
    aliases: ['ssi schaefer', 'schaefer', 'ssi sch\u00e4fer', 'ssi systems'],
    keywords: ['shuttle system', 'weasel amr', 'robot system wamas', 'bin system', 'vertical lift module'],
    naicsCodes: ['333922', '332439'],
    ikerScore: 81,
  },
  {
    id: 'autostore',
    name: 'AutoStore',
    category: 'Warehouse Automation',
    aliases: ['autostore', 'auto store', 'autostore system'],
    keywords: ['cube storage robot', 'autostore grid', 'autostore robot', 'high density storage'],
    naicsCodes: ['333922', '493110'],
    ikerScore: 79,
  },
  {
    id: 'symbotic',
    name: 'Symbotic',
    category: 'Warehouse Automation',
    aliases: ['symbotic', 'symbotic inc', 'coborgt'],
    keywords: ['warehouse automation ai', 'symbotic bot', 'walmart automation', 'autonomous case handling'],
    naicsCodes: ['333249', '493110', '541715'],
    ikerScore: 78,
  },
  {
    id: 'exotec',
    name: 'Exotec',
    category: 'Warehouse Automation',
    aliases: ['exotec', 'exotec solutions', 'skypod system'],
    keywords: ['skypod robot', '3d warehouse robot', 'high speed picking', 'rack climbing robot'],
    naicsCodes: ['333249', '493110'],
    ikerScore: 73,
  },
  {
    id: 'swisslog',
    name: 'Swisslog',
    category: 'Warehouse Automation',
    aliases: ['swisslog', 'swisslog healthcare', 'swisslog automation', 'kardex remstar'],
    keywords: ['carousel automated', 'pharmacy automation', 'vertical lift module', 'asrs healthcare'],
    naicsCodes: ['333922', '622110', '541512'],
    ikerScore: 77,
  },
  {
    id: 'vanderlande',
    name: 'Vanderlande',
    category: 'Warehouse Automation',
    aliases: ['vanderlande', 'vanderlande industries'],
    keywords: ['baggage handling airport', 'parcel sorting', 'warehouse conveyor', 'hls airport', 'pharma automation'],
    naicsCodes: ['333922', '488119'],
    ikerScore: 80,
  },
  {
    id: 'beumer-group',
    name: 'BEUMER Group',
    category: 'Warehouse Automation',
    aliases: ['beumer', 'beumer group', 'crisplant'],
    keywords: ['cross belt sorter', 'baggage handling', 'bulk conveying', 'packaging system', 'loading system'],
    naicsCodes: ['333922', '488119'],
    ikerScore: 76,
  },
  {
    id: 'mecalux',
    name: 'Mecalux',
    category: 'Warehouse Automation',
    aliases: ['mecalux', 'mecalux sa', 'easy wms'],
    keywords: ['pallet rack', 'wms software', 'automated warehouse software', 'miniload', 'shuttle rack'],
    naicsCodes: ['332311', '493110', '541512'],
    ikerScore: 71,
  },
  {
    id: 'bastian-solutions',
    name: 'Bastian Solutions',
    category: 'Warehouse Automation',
    aliases: ['bastian solutions', 'bastian', 'toyota bastian'],
    keywords: ['material handling integrator', 'conveyor integration', 'warehouse software wcs', 'robotic integration'],
    naicsCodes: ['333922', '541512'],
    ikerScore: 72,
  },
  {
    id: 'fortna',
    name: 'FORTNA',
    category: 'Warehouse Automation',
    aliases: ['fortna', 'fortna inc', 'fortna group'],
    keywords: ['distribution center design', 'fulfillment automation', 'warehouse strategy consulting', 'wms selection'],
    naicsCodes: ['541614', '493110'],
    ikerScore: 74,
  },
  {
    id: 'witron',
    name: 'Witron',
    category: 'Warehouse Automation',
    aliases: ['witron', 'witron logistik', 'witron automation'],
    keywords: ['com system', 'automated grocery dc', 'retail warehouse automation', 'order management system'],
    naicsCodes: ['333922', '493110'],
    ikerScore: 75,
  },
  {
    id: 'hytrol',
    name: 'Hytrol',
    category: 'Warehouse Automation',
    aliases: ['hytrol', 'hytrol conveyor', 'hytrol conveyor co'],
    keywords: ['conveyor belt', 'zero pressure accumulation', 'incline conveyor', 'warehouse conveyor system'],
    naicsCodes: ['333922'],
    ikerScore: 68,
  },
  {
    id: 'knapp',
    name: 'Knapp',
    category: 'Warehouse Automation',
    aliases: ['knapp', 'knapp ag', 'knapp logistics'],
    keywords: ['open shuttle', 'pharmacy warehouse', 'osr shuttle', 'pick it easy', 'automated pharmacy'],
    naicsCodes: ['333922', '541512'],
    ikerScore: 77,
  },
  {
    id: 'tgw-systems',
    name: 'TGW Systems',
    category: 'Warehouse Automation',
    aliases: ['tgw systems', 'tgw logistics', 'tgw'],
    keywords: ['fulfillment center automation', 'conveyor technology', 'goods to person tgw', 'automated picking tgw'],
    naicsCodes: ['333922', '493110'],
    ikerScore: 73,
  },
  {
    id: 'kardex',
    name: 'Kardex',
    category: 'Warehouse Automation',
    aliases: ['kardex', 'kardex remstar', 'kardex ag'],
    keywords: ['vertical carousel', 'horizontal carousel', 'compact lift', 'automated storage unit'],
    naicsCodes: ['333922', '332439'],
    ikerScore: 70,
  },
  {
    id: 'murata-machinery',
    name: 'Murata Machinery',
    category: 'Warehouse Automation',
    aliases: ['murata machinery', 'muratec', 'murata asrs'],
    keywords: ['stacker crane', 'asrs system', 'semiconductor fab automation', 'automated transport system'],
    naicsCodes: ['333922', '333242'],
    ikerScore: 74,
  },
  {
    id: 'system-logistics',
    name: 'System Logistics',
    category: 'Warehouse Automation',
    aliases: ['system logistics', 'system logistics spa'],
    keywords: ['miniload system', 'unit load asrs', 'pallet handling', 'tote shuttle'],
    naicsCodes: ['333922'],
    ikerScore: 67,
  },
  {
    id: 'intelligrated',
    name: 'Intelligrated',
    category: 'Warehouse Automation',
    aliases: ['intelligrated', 'honeywell robotics'],
    keywords: ['picking robot', 'slam dunk robot', 'robotic sortation', 'depalletizer'],
    naicsCodes: ['333249', '333922'],
    ikerScore: 72,
  },

  // ── Manufacturing Technology ─────────────────────────────────────────────────
  {
    id: 'siemens-industry',
    name: 'Siemens Industry',
    category: 'Manufacturing Tech',
    aliases: ['siemens', 'siemens industry', 'siemens ag', 'siemens usa', 'siemens plm', 'siemens digital industries'],
    keywords: ['plc automation', 'simatic', 'totally integrated automation', 'scada', 'digital twin factory', 'mindsphere', 'opcenter mes'],
    naicsCodes: ['335313', '334515', '541330'],
    ikerScore: 87,
  },
  {
    id: 'rockwell-automation',
    name: 'Rockwell Automation',
    category: 'Manufacturing Tech',
    aliases: ['rockwell automation', 'rockwell', 'allen bradley', 'allen-bradley', 'factorytalk'],
    keywords: ['allen bradley plc', 'logix controller', 'factorytalk scada', 'smart manufacturing', 'mes manufacturing'],
    naicsCodes: ['335313', '334515', '541512'],
    ikerScore: 86,
  },
  {
    id: 'schneider-electric',
    name: 'Schneider Electric',
    category: 'Manufacturing Tech',
    aliases: ['schneider electric', 'schneider', 'square d', 'aveva', 'schneider electric se'],
    keywords: ['ecostruxure', 'energy management', 'switchgear', 'industrial automation', 'data center power', 'scada had'],
    naicsCodes: ['335313', '335999', '541330'],
    ikerScore: 85,
  },
  {
    id: 'emerson-electric',
    name: 'Emerson Electric',
    category: 'Manufacturing Tech',
    aliases: ['emerson electric', 'emerson', 'emerson automation', 'fisher controls', 'deltav'],
    keywords: ['deltav dcs', 'process control', 'control valve', 'measurement instrumentation', 'aspentech', 'ovation dcs'],
    naicsCodes: ['334515', '335314', '541330'],
    ikerScore: 84,
  },
  {
    id: 'keyence',
    name: 'Keyence',
    category: 'Manufacturing Tech',
    aliases: ['keyence', 'keyence corp', 'keyence corporation'],
    keywords: ['vision system', 'barcode reader', 'laser sensor', 'measurement sensor', 'inspection system'],
    naicsCodes: ['334515', '334519'],
    ikerScore: 80,
  },
  {
    id: 'festo',
    name: 'Festo',
    category: 'Manufacturing Tech',
    aliases: ['festo', 'festo ag', 'festo didactic'],
    keywords: ['pneumatic automation', 'electric actuator', 'process automation valve', 'festo handling', 'bionic robot'],
    naicsCodes: ['332912', '333249'],
    ikerScore: 78,
  },
  {
    id: 'sick-ag',
    name: 'SICK',
    category: 'Manufacturing Tech',
    aliases: ['sick', 'sick ag', 'sick sensor', 'sick inc'],
    keywords: ['safety sensor', 'lidar sensor', 'barcode scanner industrial', '2d vision', '3d vision inspection'],
    naicsCodes: ['334515', '334519'],
    ikerScore: 76,
  },
  {
    id: 'cognex',
    name: 'Cognex',
    category: 'Manufacturing Tech',
    aliases: ['cognex', 'cognex corporation', 'in-sight', 'dataman'],
    keywords: ['machine vision', 'in-sight camera', 'dataman barcode reader', 'surface inspection', 'vision job'],
    naicsCodes: ['334515', '334519'],
    ikerScore: 81,
  },
  {
    id: 'hexagon-manufacturing',
    name: 'Hexagon Manufacturing Intelligence',
    category: 'Manufacturing Tech',
    aliases: ['hexagon', 'hexagon manufacturing', 'hexagon mi', 'leica geosystems hexagon', 'creaform'],
    keywords: ['cmm measurement', 'metrology', '3d scanning', 'quality control manufacturing', 'digital reality'],
    naicsCodes: ['334519', '541380'],
    ikerScore: 79,
  },
  {
    id: 'beckhoff',
    name: 'Beckhoff Automation',
    category: 'Manufacturing Tech',
    aliases: ['beckhoff', 'beckhoff automation', 'twincat'],
    keywords: ['twincat plc', 'pc-based control', 'ethercat', 'motion control beckhoff', 'industrial pc'],
    naicsCodes: ['334515', '333249'],
    ikerScore: 74,
  },
  {
    id: 'br-automation',
    name: 'B&R Automation',
    category: 'Manufacturing Tech',
    aliases: ['b&r automation', 'b and r automation', 'br automation', 'b&r industrial'],
    keywords: ['powerlink', 'acopos drive', 'x90 controller', 'machine-centric robotics', 'openrobotics'],
    naicsCodes: ['334515', '333249'],
    ikerScore: 73,
  },
  {
    id: 'bosch-rexroth',
    name: 'Bosch Rexroth',
    category: 'Manufacturing Tech',
    aliases: ['bosch rexroth', 'rexroth', 'bosch rexroth ag'],
    keywords: ['hydraulics industrial', 'electric drives', 'linear motion', 'ctrlx automation', 'industrial hydraulics'],
    naicsCodes: ['333996', '333249'],
    ikerScore: 80,
  },
  {
    id: 'mitsubishi-electric',
    name: 'Mitsubishi Electric Automation',
    category: 'Manufacturing Tech',
    aliases: ['mitsubishi electric', 'mitsubishi automation', 'melsec', 'melfa robot'],
    keywords: ['melsec plc', 'melfa industrial robot', 'inverter drive', 'servo system', 'vision sensor'],
    naicsCodes: ['335313', '333249'],
    ikerScore: 79,
  },
  {
    id: 'omron-automation',
    name: 'Omron Industrial Automation',
    category: 'Manufacturing Tech',
    aliases: ['omron industrial', 'omron plc', 'omron sysmac'],
    keywords: ['sysmac plc', 'safety component', 'temperature controller', 'encoder industrial', 'vision inspection omron'],
    naicsCodes: ['334515', '334519'],
    ikerScore: 78,
  },
  {
    id: 'ifm-electronic',
    name: 'ifm Electronic',
    category: 'Manufacturing Tech',
    aliases: ['ifm', 'ifm electronic', 'ifm efector'],
    keywords: ['position sensor', 'io-link sensor', 'condition monitoring', 'flow sensor', 'process sensor'],
    naicsCodes: ['334515'],
    ikerScore: 70,
  },
  {
    id: 'balluff',
    name: 'Balluff',
    category: 'Manufacturing Tech',
    aliases: ['balluff', 'balluff gmbh'],
    keywords: ['inductive sensor', 'rfid industrial', 'io-link network', 'vision sensor balluff'],
    naicsCodes: ['334515'],
    ikerScore: 68,
  },
  {
    id: 'turck',
    name: 'Turck',
    category: 'Manufacturing Tech',
    aliases: ['turck', 'turck inc', 'banner engineering turck'],
    keywords: ['proximity sensor', 'fieldbus interface', 'industrial rfid', 'inductive coupler'],
    naicsCodes: ['334515'],
    ikerScore: 67,
  },
  {
    id: 'ptc-inc',
    name: 'PTC',
    category: 'Manufacturing Tech',
    aliases: ['ptc', 'ptc inc', 'creo', 'windchill', 'thingworx'],
    keywords: ['creo cad', 'windchill plm', 'thingworx iot', 'kepware', 'augmented reality manufacturing'],
    naicsCodes: ['541511', '541512'],
    ikerScore: 83,
  },
  {
    id: 'dassault-systemes',
    name: 'Dassault Systemes',
    category: 'Manufacturing Tech',
    aliases: ['dassault systemes', 'dassault', 'solidworks', '3dexperience', 'catia'],
    keywords: ['solidworks cad', 'catia design', '3dexperience platform', 'simulia simulation', 'virtual twin'],
    naicsCodes: ['541511', '541715'],
    ikerScore: 84,
  },
  {
    id: 'ansys',
    name: 'Ansys',
    category: 'Manufacturing Tech',
    aliases: ['ansys', 'ansys inc', 'fluent simulation'],
    keywords: ['finite element analysis', 'cfd simulation', 'digital twin simulation', 'structural simulation'],
    naicsCodes: ['541511', '541715'],
    ikerScore: 80,
  },

  // ── Industrial AI ────────────────────────────────────────────────────────────
  {
    id: 'palantir',
    name: 'Palantir Technologies',
    category: 'Industrial AI',
    aliases: ['palantir', 'palantir technologies', 'foundry', 'gotham palantir', 'aip palantir'],
    keywords: ['foundry platform', 'gotham intelligence', 'aip ai platform', 'data integration', 'defense analytics palantir', 'ai decision making'],
    naicsCodes: ['541511', '541512', '541715'],
    ikerScore: 89,
  },
  {
    id: 'c3-ai',
    name: 'C3.ai',
    category: 'Industrial AI',
    aliases: ['c3 ai', 'c3.ai', 'c3 inc', 'c3 enterprise ai'],
    keywords: ['enterprise ai application', 'predictive maintenance c3', 'ai crm', 'ai supply chain', 'c3 aiot'],
    naicsCodes: ['541511', '541715'],
    ikerScore: 77,
  },
  {
    id: 'sparkcognition',
    name: 'SparkCognition',
    category: 'Industrial AI',
    aliases: ['sparkcognition', 'spark cognition', 'sparkcognition inc'],
    keywords: ['industrial ai', 'predictive maintenance ai', 'wind farm ai', 'oil gas ai', 'darwin ai'],
    naicsCodes: ['541715', '541512'],
    ikerScore: 72,
  },
  {
    id: 'datarobot',
    name: 'DataRobot',
    category: 'Industrial AI',
    aliases: ['datarobot', 'data robot', 'datarobot inc'],
    keywords: ['automated machine learning', 'automl', 'mlops', 'ai cloud enterprise', 'model deployment'],
    naicsCodes: ['541511', '541715'],
    ikerScore: 74,
  },
  {
    id: 'uptake',
    name: 'Uptake',
    category: 'Industrial AI',
    aliases: ['uptake', 'uptake technologies'],
    keywords: ['asset performance management', 'locomotive ai', 'equipment health monitoring', 'industrial analytics'],
    naicsCodes: ['541715', '541512'],
    ikerScore: 68,
  },
  {
    id: 'sight-machine',
    name: 'Sight Machine',
    category: 'Industrial AI',
    aliases: ['sight machine', 'sightmachine'],
    keywords: ['factory analytics', 'oee manufacturing ai', 'production data platform', 'shopfloor analytics'],
    naicsCodes: ['541715', '541512'],
    ikerScore: 64,
  },
  {
    id: 'augury',
    name: 'Augury',
    category: 'Industrial AI',
    aliases: ['augury', 'augury inc', 'augury ai'],
    keywords: ['machine health', 'vibration monitoring ai', 'predictive maintenance iot', 'pump health monitoring'],
    naicsCodes: ['541715', '334515'],
    ikerScore: 66,
  },
  {
    id: 'tulip-interfaces',
    name: 'Tulip',
    category: 'Industrial AI',
    aliases: ['tulip', 'tulip interfaces', 'tulip platform'],
    keywords: ['frontline operations platform', 'no-code manufacturing app', 'connected worker', 'digital work instructions'],
    naicsCodes: ['541511', '541715'],
    ikerScore: 63,
  },
  {
    id: 'symphonyai',
    name: 'SymphonyAI',
    category: 'Industrial AI',
    aliases: ['symphonyai', 'symphony ai', 'symphony ai industrial', 'savantis'],
    keywords: ['industrial ai suite', 'sap companion ai', 'predictive quality', 'oil gas ai symphony'],
    naicsCodes: ['541715', '541511'],
    ikerScore: 71,
  },
  {
    id: 'aspentech',
    name: 'AspenTech',
    category: 'Industrial AI',
    aliases: ['aspentech', 'aspen technology', 'aspenone'],
    keywords: ['process optimization', 'refinery optimization', 'aspen plus', 'mtell predictive', 'process simulation'],
    naicsCodes: ['541511', '541715'],
    ikerScore: 78,
  },
  {
    id: 'aveva',
    name: 'AVEVA',
    category: 'Industrial AI',
    aliases: ['aveva', 'aveva group', 'aveva scada', 'wonderware'],
    keywords: ['wonderware scada', 'pi system', 'industrial data ops', 'digital twin process', 'asset lifecycle'],
    naicsCodes: ['541511', '541715'],
    ikerScore: 79,
  },
  {
    id: 'seeq',
    name: 'Seeq',
    category: 'Industrial AI',
    aliases: ['seeq', 'seeq corporation'],
    keywords: ['process intelligence', 'industrial analytics saas', 'pi system analytics', 'manufacturing analytics cloud'],
    naicsCodes: ['541511', '541715'],
    ikerScore: 62,
  },
  {
    id: 'foghorn-systems',
    name: 'FogHorn Systems',
    category: 'Industrial AI',
    aliases: ['foghorn', 'foghorn systems', 'foghorn lightning'],
    keywords: ['edge ai industrial', 'lightning ml', 'edge analytics', 'iot edge intelligence'],
    naicsCodes: ['541715', '541512'],
    ikerScore: 60,
  },
  {
    id: 'neurala',
    name: 'Neurala',
    category: 'Industrial AI',
    aliases: ['neurala', 'neurala inc', 'brain builder'],
    keywords: ['visual inspection ai', 'defect detection ai', 'brain builder platform', 'visual quality control'],
    naicsCodes: ['541715'],
    ikerScore: 58,
  },
  {
    id: 'instrumental',
    name: 'Instrumental',
    category: 'Industrial AI',
    aliases: ['instrumental', 'instrumental inc'],
    keywords: ['manufacturing intelligence', 'anomaly detection manufacturing', 'traceability manufacturing ai'],
    naicsCodes: ['541715'],
    ikerScore: 57,
  },
  {
    id: 'vanti-analytics',
    name: 'Vanti Analytics',
    category: 'Industrial AI',
    aliases: ['vanti', 'vanti analytics'],
    keywords: ['self-optimizing manufacturing', 'process parameter optimization', 'yield improvement ai'],
    naicsCodes: ['541715'],
    ikerScore: 55,
  },
  {
    id: 'ms-azure-iot',
    name: 'Microsoft Azure Industrial IoT',
    category: 'Industrial AI',
    aliases: ['azure iot', 'microsoft azure iot', 'azure industrial iot', 'azure digital twins'],
    keywords: ['azure iot hub', 'azure digital twins', 'azure time series insights', 'industrial iot cloud'],
    naicsCodes: ['541511', '541519'],
    ikerScore: 85,
  },
  {
    id: 'aws-iot',
    name: 'AWS IoT',
    category: 'Industrial AI',
    aliases: ['aws iot', 'amazon iot', 'aws industrial', 'amazon web services iot'],
    keywords: ['aws iot core', 'aws greengrass', 'aws lookout equipment', 'industrial cloud aws'],
    naicsCodes: ['541511', '541519'],
    ikerScore: 86,
  },
  {
    id: 'google-cloud-manufacturing',
    name: 'Google Cloud Manufacturing',
    category: 'Industrial AI',
    aliases: ['google cloud manufacturing', 'google manufacturing ai', 'visual inspection ai google'],
    keywords: ['manufacturing data cloud', 'visual inspection google', 'vertex ai manufacturing'],
    naicsCodes: ['541511', '541715'],
    ikerScore: 82,
  },

  // ── Logistics Platforms ──────────────────────────────────────────────────────
  {
    id: 'flexport',
    name: 'Flexport',
    category: 'Logistics Platform',
    aliases: ['flexport', 'flexport inc'],
    keywords: ['digital freight forwarding', 'supply chain visibility', 'customs brokerage digital', 'ocean freight tech'],
    naicsCodes: ['488510', '541512'],
    ikerScore: 78,
  },
  {
    id: 'project44',
    name: 'Project44',
    category: 'Logistics Platform',
    aliases: ['project44', 'project 44', 'p44'],
    keywords: ['freight visibility platform', 'real-time tracking freight', 'eld integration logistics', 'carrier api'],
    naicsCodes: ['488510', '541511'],
    ikerScore: 74,
  },
  {
    id: 'fourkites',
    name: 'FourKites',
    category: 'Logistics Platform',
    aliases: ['fourkites', 'four kites', 'fourkites inc'],
    keywords: ['supply chain visibility saas', 'real-time eta freight', 'dynamic eta', 'freight intelligence'],
    naicsCodes: ['488510', '541511'],
    ikerScore: 73,
  },
  {
    id: 'uber-freight',
    name: 'Uber Freight',
    category: 'Logistics Platform',
    aliases: ['uber freight', 'uberfreight'],
    keywords: ['digital brokerage', 'spot market freight', 'shipper tech', 'carrier marketplace'],
    naicsCodes: ['488510'],
    ikerScore: 71,
  },
  {
    id: 'manhattan-associates',
    name: 'Manhattan Associates',
    category: 'Logistics Platform',
    aliases: ['manhattan associates', 'manhattan wms', 'manh'],
    keywords: ['warehouse management system', 'order management system', 'supply chain commerce', 'wms cloud'],
    naicsCodes: ['541511', '493110'],
    ikerScore: 82,
  },
  {
    id: 'blue-yonder',
    name: 'Blue Yonder',
    category: 'Logistics Platform',
    aliases: ['blue yonder', 'jda software', 'blueyonder', 'panasonic blue yonder'],
    keywords: ['demand planning', 'supply chain planning', 'wms blue yonder', 'logistics fulfillment platform'],
    naicsCodes: ['541511', '541512'],
    ikerScore: 80,
  },
  {
    id: 'descartes',
    name: 'Descartes Systems',
    category: 'Logistics Platform',
    aliases: ['descartes', 'descartes systems', 'descartes systems group'],
    keywords: ['customs filing', 'route optimization software', 'fleet routing', 'global trade content', 'denied party screening'],
    naicsCodes: ['488510', '541511'],
    ikerScore: 76,
  },
  {
    id: 'e2open',
    name: 'E2open',
    category: 'Logistics Platform',
    aliases: ['e2open', 'e2 open', 'e2open inc'],
    keywords: ['supply chain network', 'channel data management', 'global trade management', 'transportation management'],
    naicsCodes: ['541511', '488510'],
    ikerScore: 74,
  },
  {
    id: 'kinaxis',
    name: 'Kinaxis',
    category: 'Logistics Platform',
    aliases: ['kinaxis', 'kinaxis inc', 'rapidresponse'],
    keywords: ['supply chain planning saas', 'rapidresponse platform', 'concurrent planning', 'supply chain risk kinaxis'],
    naicsCodes: ['541511'],
    ikerScore: 76,
  },
  {
    id: 'trimble-transportation',
    name: 'Trimble Transportation',
    category: 'Logistics Platform',
    aliases: ['trimble transportation', 'trimble', 'tmw systems', 'tms trimble'],
    keywords: ['tms software', 'eld compliance', 'driver workflow', 'fleet management trimble'],
    naicsCodes: ['541511', '517911'],
    ikerScore: 74,
  },
  {
    id: 'samsara',
    name: 'Samsara',
    category: 'Logistics Platform',
    aliases: ['samsara', 'samsara inc'],
    keywords: ['fleet telematics', 'eld mandate', 'video safety', 'asset tracking saas', 'connected operations'],
    naicsCodes: ['334290', '541511'],
    ikerScore: 73,
  },
  {
    id: 'platform-science',
    name: 'Platform Science',
    category: 'Logistics Platform',
    aliases: ['platform science', 'platform science inc'],
    keywords: ['open fleet platform', 'truck telematics os', 'third party app trucking'],
    naicsCodes: ['541511', '517911'],
    ikerScore: 65,
  },
  {
    id: 'motive-fleet',
    name: 'Motive (KeepTruckin)',
    category: 'Logistics Platform',
    aliases: ['motive', 'keeptruckin', 'keep truckin', 'motive fleet'],
    keywords: ['eld fleet', 'dash cam fleet', 'fleet card', 'driver safety ai'],
    naicsCodes: ['541511', '517911'],
    ikerScore: 67,
  },
  {
    id: 'transplace',
    name: 'Transplace',
    category: 'Logistics Platform',
    aliases: ['transplace', 'transplace llc', 'uber freight transplace'],
    keywords: ['managed transportation', 'freight brokerage managed', 'tms outsourcing', 'mexico freight'],
    naicsCodes: ['488510', '541614'],
    ikerScore: 71,
  },
  {
    id: 'coyote-logistics',
    name: 'Coyote Logistics',
    category: 'Logistics Platform',
    aliases: ['coyote logistics', 'coyote', 'upg coyote'],
    keywords: ['freight brokerage', 'spot freight', 'shipper network', 'coyote go app'],
    naicsCodes: ['488510'],
    ikerScore: 70,
  },

  // ── Supply Chain Software ────────────────────────────────────────────────────
  {
    id: 'sap-scm',
    name: 'SAP',
    category: 'Supply Chain Software',
    aliases: ['sap', 'sap se', 'sap erp', 'sap s4hana', 'sap ariba', 'sap scm'],
    keywords: ['sap s/4hana', 'sap ariba', 'sap integrated business planning', 'sap extended warehouse', 'ewm sap', 'supply chain erp'],
    naicsCodes: ['541511', '541512'],
    ikerScore: 90,
  },
  {
    id: 'oracle-scm',
    name: 'Oracle SCM',
    category: 'Supply Chain Software',
    aliases: ['oracle scm', 'oracle', 'oracle cloud scm', 'oracle supply chain'],
    keywords: ['oracle fusion scm', 'oracle planning', 'oracle manufacturing', 'oracle logistics', 'netsuite supply'],
    naicsCodes: ['541511', '541512'],
    ikerScore: 89,
  },
  {
    id: 'infor',
    name: 'Infor',
    category: 'Supply Chain Software',
    aliases: ['infor', 'infor inc', 'infor scm', 'infor cloud suite'],
    keywords: ['infor cloud suite', 'infor wms', 'infor m3', 'lx erp', 'infor ln', 'infor supply chain'],
    naicsCodes: ['541511', '541512'],
    ikerScore: 77,
  },
  {
    id: 'celonis',
    name: 'Celonis',
    category: 'Supply Chain Software',
    aliases: ['celonis', 'celonis se'],
    keywords: ['process mining', 'execution management', 'process intelligence celonis', 'procurement mining'],
    naicsCodes: ['541511', '541715'],
    ikerScore: 74,
  },
  {
    id: 'uipath',
    name: 'UiPath',
    category: 'Supply Chain Software',
    aliases: ['uipath', 'ui path', 'uipath inc'],
    keywords: ['rpa automation', 'robotic process automation', 'enterprise automation', 'document understanding'],
    naicsCodes: ['541511', '541519'],
    ikerScore: 79,
  },
  {
    id: 'coupa',
    name: 'Coupa Software',
    category: 'Supply Chain Software',
    aliases: ['coupa', 'coupa software', 'coupa bsm'],
    keywords: ['business spend management', 'procurement software', 'supplier management', 'coupa pay'],
    naicsCodes: ['541511'],
    ikerScore: 76,
  },
  {
    id: 'anaplan',
    name: 'Anaplan',
    category: 'Supply Chain Software',
    aliases: ['anaplan', 'anaplan inc'],
    keywords: ['connected planning', 'sales planning', 'supply chain planning anaplan', 'workforce planning'],
    naicsCodes: ['541511'],
    ikerScore: 75,
  },
  {
    id: 'o9-solutions',
    name: 'o9 Solutions',
    category: 'Supply Chain Software',
    aliases: ['o9 solutions', 'o9', 'o9 platform'],
    keywords: ['integrated business planning', 'demand sensing', 'supply planning o9', 'revenue planning'],
    naicsCodes: ['541511', '541715'],
    ikerScore: 71,
  },
  {
    id: 'llamasoft',
    name: 'LLamasoft (Coupa)',
    category: 'Supply Chain Software',
    aliases: ['llamasoft', 'llama soft', 'llamasoft coupa'],
    keywords: ['supply chain design', 'network design software', 'supply chain simulation', 'scenario modeling'],
    naicsCodes: ['541511', '541715'],
    ikerScore: 70,
  },
  {
    id: 'nulogy',
    name: 'Nulogy',
    category: 'Supply Chain Software',
    aliases: ['nulogy', 'nulogy corp'],
    keywords: ['contract packaging software', 'co-packer collaboration', 'secondary packaging platform'],
    naicsCodes: ['541511'],
    ikerScore: 59,
  },
  {
    id: 'logility',
    name: 'Logility',
    category: 'Supply Chain Software',
    aliases: ['logility', 'logility supply chain'],
    keywords: ['demand planning software', 'inventory optimization', 'supplier management platform', 'voyager solutions'],
    naicsCodes: ['541511'],
    ikerScore: 65,
  },
  {
    id: 'jda-software',
    name: 'JDA Software',
    category: 'Supply Chain Software',
    aliases: ['jda software', 'jda supply chain'],
    keywords: ['category management', 'retail planning', 'workforce management retail', 'markdown optimization'],
    naicsCodes: ['541511'],
    ikerScore: 68,
  },
  {
    id: 'gep-worldwide',
    name: 'GEP',
    category: 'Supply Chain Software',
    aliases: ['gep', 'gep worldwide', 'gep smart'],
    keywords: ['smart procurement platform', 'spend analysis', 'sourcing software', 'contract management software'],
    naicsCodes: ['541511', '541614'],
    ikerScore: 67,
  },
  {
    id: 'ivalua',
    name: 'Ivalua',
    category: 'Supply Chain Software',
    aliases: ['ivalua', 'ivalua inc'],
    keywords: ['supplier relationship management', 'source to pay', 'procurement ai', 'contract lifecycle'],
    naicsCodes: ['541511'],
    ikerScore: 66,
  },
  {
    id: 'jaggaer',
    name: 'JAGGAER',
    category: 'Supply Chain Software',
    aliases: ['jaggaer', 'sciquest', 'pool4tool'],
    keywords: ['direct spend procurement', 'research procurement', 'supplier collaboration', 'advanced sourcing'],
    naicsCodes: ['541511'],
    ikerScore: 65,
  },
  {
    id: 'veritiv',
    name: 'Veritiv',
    category: 'Supply Chain Software',
    aliases: ['veritiv', 'veritiv corp'],
    keywords: ['packaging distribution', 'facility supplies', 'print distribution', 'supply chain outsourcing'],
    naicsCodes: ['424130', '541614'],
    ikerScore: 62,
  },
  {
    id: 'roper-technologies',
    name: 'Roper Technologies',
    category: 'Supply Chain Software',
    aliases: ['roper technologies', 'roper', 'roper industries'],
    keywords: ['software industrial', 'niche software acquisitions', 'freight match', 'loadlink technologies'],
    naicsCodes: ['541511', '334519'],
    ikerScore: 76,
  },
  {
    id: 'gains-systems',
    name: 'GAINS Systems',
    category: 'Supply Chain Software',
    aliases: ['gains systems', 'gains', 'gains supply chain'],
    keywords: ['inventory policy', 'supply chain performance', 'replenishment optimization', 'service level optimization'],
    naicsCodes: ['541511'],
    ikerScore: 58,
  },
  {
    id: 'llamasoft-supply-chain',
    name: 'ToolsGroup',
    category: 'Supply Chain Software',
    aliases: ['toolsgroup', 'tools group', 'so99+'],
    keywords: ['demand sensing toolsgroup', 'probabilistic forecasting', 'inventory optimization toolsgroup'],
    naicsCodes: ['541511'],
    ikerScore: 60,
  },

  // ── El Paso Extension Entities (March 2026) ──────────────────────────────────
  {
    id: 'ep-northrop',
    name: 'Northrop Grumman (El Paso)',
    category: 'Defense Tech',
    aliases: ['northrop grumman ibcs', 'ibcs northrop', 'integrated battle command northrop'],
    keywords: ['ibcs integrated battle command', 'air missile defense c2', 'ibcs program', 'sensor fusion air defense fort bliss'],
    naicsCodes: ['336411', '334511', '541330'],
    ikerScore: 90,
  },
  {
    id: 'ep-lockheed',
    name: 'Lockheed Martin MFC (El Paso)',
    category: 'Defense Tech',
    aliases: ['lockheed mfc', 'lockheed fire control el paso', 'thaad lockheed'],
    keywords: ['thaad interceptor', 'terminal high altitude area defense', 'himars', 'pac-3 mse fort bliss', 'guided mlrs'],
    naicsCodes: ['336414', '336411', '541330'],
    ikerScore: 93,
  },
  {
    id: 'ep-generaldynamics',
    name: 'General Dynamics Land Systems (El Paso)',
    category: 'Defense Tech',
    aliases: ['gdls el paso', 'general dynamics land systems fort bliss', 'm1 abrams depot'],
    keywords: ['m1a2 sepv3 fort bliss', 'abrams tank depot', 'armored vehicle sustainment fort bliss'],
    naicsCodes: ['336992', '541512', '334511'],
    ikerScore: 89,
  },
  {
    id: 'ep-bae',
    name: 'BAE Systems (El Paso)',
    category: 'Defense Tech',
    aliases: ['bae systems el paso', 'bae bradley fort bliss', 'bae electronic warfare el paso'],
    keywords: ['bradley m2a4 upgrade', 'electronic warfare bae fort bliss', 'envg-b night vision bae', 'soldier systems bae'],
    naicsCodes: ['334511', '336992', '541330'],
    ikerScore: 85,
  },
  {
    id: 'ep-accenturefed',
    name: 'Accenture Federal Services (El Paso)',
    category: 'Defense Tech',
    aliases: ['accenture federal el paso', 'accenture federal dod el paso', 'afs army'],
    keywords: ['gcss army s4hana upgrade', 'army erp modernization accenture', 'azure govcloud army', 'army ai center excellence'],
    naicsCodes: ['541611', '541512', '541519'],
    ikerScore: 84,
  },
  {
    id: 'ep-deloitte',
    name: 'Deloitte Government El Paso',
    category: 'Defense Tech',
    aliases: ['deloitte el paso', 'deloitte government el paso', 'deloitte gps el paso'],
    keywords: ['army audit readiness deloitte', 'cbp it deloitte', 'defense financial management consulting', 'cleared consulting el paso'],
    naicsCodes: ['541611', '541512', '541219'],
    ikerScore: 82,
  },
  {
    id: 'ep-caci-ep',
    name: 'CACI International (El Paso)',
    category: 'Defense Tech',
    aliases: ['caci el paso', 'caci wsmr', 'caci fort bliss'],
    keywords: ['sigint processing el paso', 'army intelligence wsmr', 'intelligence brigade it fort bliss', 'cyber operations caci'],
    naicsCodes: ['541512', '541519', '541690'],
    ikerScore: 81,
  },
  {
    id: 'ep-vectrus-ep',
    name: 'V2X Vectrus (Fort Bliss)',
    category: 'Defense Tech',
    aliases: ['vectrus fort bliss', 'v2x fort bliss', 'logcap v fort bliss'],
    keywords: ['logcap v fort bliss', 'base operations fort bliss support', 'installation support contract fort bliss'],
    naicsCodes: ['561210', '237990', '541330'],
    ikerScore: 77,
  },
  {
    id: 'ep-palantir',
    name: 'Palantir Army AIP (El Paso)',
    category: 'Defense Tech',
    aliases: ['palantir army aip', 'palantir fort bliss', 'army aip el paso', 'palantir titan'],
    keywords: ['army aip platform fort bliss', 'palantir foundry army', 'titan ground station palantir', 'army ai platform operational'],
    naicsCodes: ['541511', '541715', '541512'],
    ikerScore: 89,
  },
  {
    id: 'ep-crowdstrike',
    name: 'CrowdStrike Federal (El Paso)',
    category: 'Defense Tech',
    aliases: ['crowdstrike federal el paso', 'crowdstrike cbp', 'crowdstrike dod el paso'],
    keywords: ['falcon endpoint dod el paso', 'disa hbss replacement crowdstrike', 'cbp network security crowdstrike', 'army arcyber threat intel'],
    naicsCodes: ['541512', '541519'],
    ikerScore: 83,
  },
  {
    id: 'ep-sievert',
    name: 'Sievert Larson Cyber',
    category: 'Defense Tech',
    aliases: ['sievert larson', 'sievert larson cyber', 'slc cyber el paso'],
    keywords: ['fort bliss cyber range red team', 'ics security el paso', 'cisa assessment critical infrastructure', 'ot security utilities el paso'],
    naicsCodes: ['541512', '541519', '541690'],
    ikerScore: 65,
  },
  {
    id: 'ep-irontower',
    name: 'Iron Tower Security',
    category: 'Defense Tech',
    aliases: ['iron tower security', 'iron tower', 'irontower el paso'],
    keywords: ['zero trust maquiladora network', 'cross border network security el paso', 'bi-national zero trust'],
    naicsCodes: ['541512', '541519'],
    ikerScore: 55,
  },
  {
    id: 'ep-elpaso-childrens',
    name: "El Paso Children's Hospital",
    category: 'Health Tech',
    aliases: ["el paso children's", 'epch', 'ep childrens hospital', 'el paso pediatric hospital'],
    keywords: ['pediatric sepsis ai el paso', 'childrens telehealth west texas', 'pediatric ehr bilingual', 'mychart childrens el paso'],
    naicsCodes: ['622110', '541512'],
    ikerScore: 72,
  },
  {
    id: 'ep-wbamc',
    name: 'William Beaumont Army Medical Center',
    category: 'Health Tech',
    aliases: ['wbamc', 'william beaumont army', 'beaumont army medical center'],
    keywords: ['mhs genesis wbamc', 'military health ehr fort bliss', 'combat casualty simulation army', 'army medical readiness data'],
    naicsCodes: ['622110', '541512', '611430'],
    ikerScore: 76,
  },
  {
    id: 'ep-caremore',
    name: 'CareMore Health El Paso',
    category: 'Health Tech',
    aliases: ['caremore el paso', 'caremore health el paso'],
    keywords: ['medicare advantage el paso', 'remote cardiac monitoring el paso', 'hedis care management hispanic', 'medicare care gap ai'],
    naicsCodes: ['621498', '541512'],
    ikerScore: 68,
  },
  {
    id: 'ep-gridworks',
    name: 'GridWorks Energy El Paso',
    category: 'Energy Tech',
    aliases: ['gridworks energy', 'gridworks ep', 'gridworks el paso'],
    keywords: ['epe derms pilot', 'fort bliss microgrid battery', 'grid edge el paso', 'solar storage military el paso'],
    naicsCodes: ['221122', '238210', '541330'],
    ikerScore: 62,
  },
  {
    id: 'ep-abengoa',
    name: 'Abengoa Solar El Paso',
    category: 'Energy Tech',
    aliases: ['abengoa solar el paso', 'abengoa el paso'],
    keywords: ['csp west texas epe', 'crez solar compliance texas', 'utility solar ppa el paso electric'],
    naicsCodes: ['221114', '237130'],
    ikerScore: 66,
  },
  {
    id: 'ep-borgwarner',
    name: 'BorgWarner El Paso',
    category: 'Manufacturing Tech',
    aliases: ['borgwarner el paso', 'borgwarner juarez', 'borg warner maquiladora'],
    keywords: ['ev thermal management juarez plant', 'gm ultium borgwarner supply', 'ev components maquiladora el paso'],
    naicsCodes: ['336390', '336300'],
    ikerScore: 70,
  },
  {
    id: 'ep-commscope',
    name: 'CommScope El Paso',
    category: 'Manufacturing Tech',
    aliases: ['commscope el paso', 'commscope juarez', 'commscope fiber el paso'],
    keywords: ['fiber optic assembly el paso juarez', '5g hardware manufacturing maquiladora', 'rf connectivity defense components'],
    naicsCodes: ['335921', '334220'],
    ikerScore: 69,
  },
  {
    id: 'ep-sanmina',
    name: 'Sanmina Corporation El Paso',
    category: 'Manufacturing Tech',
    aliases: ['sanmina el paso', 'sanmina juarez', 'sanmina ems el paso'],
    keywords: ['medical device assembly juarez el paso', 'ipc class iii pcb el paso', 'defense electronics ems maquiladora'],
    naicsCodes: ['334418', '334419'],
    ikerScore: 73,
  },
  {
    id: 'ep-ontrac',
    name: 'OnTrac El Paso',
    category: 'Logistics',
    aliases: ['ontrac el paso', 'lasership el paso', 'ontrac west texas'],
    keywords: ['last mile el paso delivery', 'regional parcel west texas', 'amazon sfp carrier el paso'],
    naicsCodes: ['492110'],
    ikerScore: 64,
  },
  {
    id: 'ep-globaltranz',
    name: 'GlobalTranz El Paso',
    category: 'Logistics',
    aliases: ['globaltranz el paso', 'global tranz el paso', 'globaltranz cross border'],
    keywords: ['cross border freight brokerage el paso', 'us mexico truckload globaltranz', 'cold chain el paso mexico'],
    naicsCodes: ['488510', '541614'],
    ikerScore: 67,
  },
  {
    id: 'ep-nuvocargo',
    name: 'Nuvocargo',
    category: 'Border Tech',
    aliases: ['nuvocargo', 'nuvo cargo', 'nuvocargo freight mexico'],
    keywords: ['digital freight us mexico', 'pedimento automation platform', 'cross border working capital freight', 'a16z us mexico freight'],
    naicsCodes: ['488510', '541511'],
    ikerScore: 72,
  },
  {
    id: 'ep-samsara-ep',
    name: 'Samsara Border Fleet',
    category: 'Logistics',
    aliases: ['samsara cross border', 'samsara border fleet', 'samsara el paso fleet'],
    keywords: ['c-tpat gps tracking cbp', 'cross border eld compliance', 'trusted shipper telematics el paso'],
    naicsCodes: ['334290', '541511'],
    ikerScore: 71,
  },
  {
    id: 'ep-palantir-local',
    name: 'Palantir Technologies (Local Office)',
    category: 'Defense Tech',
    aliases: ['palantir local el paso', 'palantir el paso office'],
    keywords: ['army aip fort bliss local', 'foundry logistics army el paso', 'titan palantir el paso'],
    naicsCodes: ['541511', '541715'],
    ikerScore: 89,
  },
  {
    id: 'ep-cogility',
    name: 'Cogility Corp',
    category: 'AI / R&D',
    aliases: ['cogility', 'cogility corp', 'cobweb cogility', 'cogility el paso'],
    keywords: ['cobweb platform army g4', 'army readiness analytics el paso', 'defense logistics ai sbir', 'logsa integration cogility'],
    naicsCodes: ['541715', '541512'],
    ikerScore: 62,
  },
  {
    id: 'ep-kpmg',
    name: 'KPMG El Paso',
    category: 'Defense Tech',
    aliases: ['kpmg el paso', 'kpmg juarez advisory', 'kpmg maquiladora'],
    keywords: ['usmca advisory kpmg el paso', 'maquiladora restructuring kpmg', 'digital transformation maquiladora kpmg'],
    naicsCodes: ['541611', '541219', '541512'],
    ikerScore: 72,
  },
  {
    id: 'ep-elpasoinnovation',
    name: 'El Paso Innovation Hub (Entrada)',
    category: 'AI / R&D',
    aliases: ['entrada el paso', 'el paso innovation hub', 'ep innovation hub', 'entrada startup incubator'],
    keywords: ['sbir el paso startup', 'border tech incubator utep', 'defense dual use startup el paso', 'dhs sbir el paso tech'],
    naicsCodes: ['926150', '541715'],
    ikerScore: 55,
  },
];

// ─── Topic / Sector Entities (not vendors, but tracked signals) ──────────────

export type SectorKeywords = {
  id: string;
  label: string;
  color: string;
  keywords: string[];
  contractKeywords: string[];    // SAM.gov / news contract signals
  securityKeywords: string[];    // Crime/incident keywords that affect this sector
};

export const SECTOR_KEYWORDS: SectorKeywords[] = [
  {
    id: 'defense',
    label: 'Defense Tech',
    color: '#ff6400',
    keywords: [
      'fort bliss', 'army', 'dod', 'defense contract', 'pentagon', 'ndaa',
      'c4isr', 'patriot', 'ivas', 'army futures', 'army modernization',
      'missile defense', 'electronic warfare', 'unmanned systems', 'drone',
    ],
    contractKeywords: [
      'idiq', 'task order', 'contract award', 'base contract', 'follow-on',
      'sbir phase', 'other transaction', 'gsa schedule', 'multiple award',
    ],
    securityKeywords: [
      'fort bliss incident', 'base security', 'classified breach', 'insider threat',
    ],
  },
  {
    id: 'border-trade',
    label: 'Border Trade',
    color: '#00d4ff',
    keywords: [
      'usmca', 'maquiladora', 'immex', 'cbp', 'customs', 'port of entry',
      'bridge of americas', 'ysleta', 'paso del norte', 'nearshoring',
      'cross-border', 'trade corridor', 'juarez', 'chihuahua manufacturing',
    ],
    contractKeywords: [
      'cbp contract', 'dhs award', 'customs modernization', 'ace platform award',
      'biometric contract', 'border technology contract',
    ],
    securityKeywords: [
      'border closure', 'port closure', 'bridge closure', 'crossing incident',
      'smuggling seizure', 'cartel interdiction', 'drug seizure',
    ],
  },
  {
    id: 'logistics',
    label: 'Supply Chain',
    color: '#a855f7',
    keywords: [
      'supply chain', 'logistics', 'freight', 'warehouse', 'distribution',
      'last mile', 'route optimization', 'fleet management', 'cold chain',
      'inventory management', 'procurement', 'fulfilment',
    ],
    contractKeywords: [
      'logistics contract', 'supply chain award', 'distribution contract',
      'freight contract', 'transportation award',
    ],
    securityKeywords: [
      'cargo theft', 'freight hijacking', 'supply chain disruption',
      'port congestion', 'bridge closure supply',
    ],
  },
  {
    id: 'water',
    label: 'Water Tech',
    color: '#00ffcc',
    keywords: [
      'desalination', 'water scarcity', 'water reuse', 'aquifer depletion',
      'brackish water', 'water treatment', 'water infrastructure', 'desal plant',
      'water recycling', 'drought', 'rio grande', 'water management',
    ],
    contractKeywords: [
      'water contract', 'desal contract', 'water infrastructure award',
      'water technology grant', 'epwu contract',
    ],
    securityKeywords: [
      'water contamination', 'infrastructure attack', 'water system breach',
    ],
  },
  {
    id: 'energy',
    label: 'Energy Tech',
    color: '#ffb800',
    keywords: [
      'solar energy', 'battery storage', 'grid modernization', 'ercot',
      'renewable energy', 'wind energy', 'energy storage', 'smart grid',
      'power infrastructure', 'energy efficiency', 'electric vehicle',
    ],
    contractKeywords: [
      'energy contract', 'doe award', 'grid contract', 'solar contract',
      'battery storage contract', 'energy grant',
    ],
    securityKeywords: [
      'grid attack', 'power outage attack', 'energy infrastructure threat',
      'substation incident',
    ],
  },
  {
    id: 'robotics',
    label: 'Robotics & Automation',
    color: '#a855f7',
    keywords: [
      'industrial robot', 'collaborative robot', 'cobot', 'autonomous mobile robot',
      'amr', 'automated guided vehicle', 'agv', 'humanoid robot', 'robotic arm',
      'warehouse robot', 'mobile manipulation', 'exoskeleton', 'pick and place robot',
    ],
    contractKeywords: [
      'robot contract', 'automation award', 'robotic system contract', 'amr deployment',
      'warehouse automation contract', 'robot integration award',
    ],
    securityKeywords: [
      'robot safety incident', 'autonomous system failure', 'automation disruption',
    ],
  },
  {
    id: 'warehouse-automation',
    label: 'Warehouse Automation',
    color: '#06b6d4',
    keywords: [
      'asrs', 'automated storage retrieval', 'goods to person', 'conveyor system',
      'sortation', 'warehouse management system', 'wms', 'pick and pass', 'fulfillment automation',
      'cube storage', 'shuttle system', 'vertical lift module', 'miniload',
    ],
    contractKeywords: [
      'warehouse automation contract', 'fulfillment center award', 'asrs contract',
      'distribution automation award', 'wms implementation award',
    ],
    securityKeywords: [
      'warehouse fire', 'fulfillment center incident', 'distribution disruption',
    ],
  },
  {
    id: 'manufacturing-tech',
    label: 'Manufacturing Tech',
    color: '#22c55e',
    keywords: [
      'plc', 'scada', 'mes', 'cnc', 'digital twin', 'machine vision', 'industrial iot',
      'smart factory', 'industry 4.0', 'additive manufacturing', '3d printing industrial',
      'quality control automation', 'machine tool', 'servo drive',
    ],
    contractKeywords: [
      'manufacturing contract', 'factory automation award', 'mes implementation',
      'digital factory award', 'smart manufacturing grant',
    ],
    securityKeywords: [
      'manufacturing plant incident', 'factory cyber attack', 'ot security breach',
      'scada attack', 'industrial control system incident',
    ],
  },
  {
    id: 'industrial-ai',
    label: 'Industrial AI',
    color: '#f59e0b',
    keywords: [
      'predictive maintenance', 'process optimization ai', 'industrial machine learning',
      'edge ai', 'iot analytics', 'anomaly detection industrial', 'digital twin ai',
      'computer vision manufacturing', 'foundation model industrial', 'generative ai manufacturing',
    ],
    contractKeywords: [
      'ai contract industrial', 'predictive analytics award', 'industrial ai grant',
      'iot platform contract', 'machine learning deployment',
    ],
    securityKeywords: [
      'ai system failure', 'model adversarial attack', 'data pipeline breach',
    ],
  },
  {
    id: 'supply-chain-software',
    label: 'Supply Chain Software',
    color: '#ec4899',
    keywords: [
      'erp supply chain', 'demand planning', 'inventory optimization', 'procurement software',
      'supplier management', 'spend analytics', 'source to pay', 'contract lifecycle management',
      'supply chain visibility', 'order management', 'global trade management',
    ],
    contractKeywords: [
      'erp implementation', 'scm software award', 'procurement platform contract',
      'supply chain software license', 'wms saas contract',
    ],
    securityKeywords: [
      'erp breach', 'supply chain software attack', 'ransomware supply chain',
      'data breach procurement',
    ],
  },
];

// ─── Merge extended El Paso entities ─────────────────────────────────────────
// NXT_ENTITIES_ELPASO adds 50+ EP-specific vendors (defense, cyber, health, etc.)
NXT_ENTITIES.push(...NXT_ENTITIES_ELPASO);

// ─── Lookups ──────────────────────────────────────────────────────────────────

// Build alias → entity map for O(1) lookup
const _aliasMap = new Map<string, NxtEntity>();
for (const entity of NXT_ENTITIES) {
  for (const alias of entity.aliases) {
    _aliasMap.set(alias.toLowerCase(), entity);
  }
}

export function findEntityByText(text: string): NxtEntity[] {
  const lower = text.toLowerCase();
  const found = new Map<string, NxtEntity>();
  for (const [alias, entity] of Array.from(_aliasMap.entries() as Iterable<[string, NxtEntity]>)) {
    if (lower.includes(alias)) {
      found.set(entity.id, entity);
    }
  }
  return [...found.values()];
}

export function findSectorsByText(text: string): SectorKeywords[] {
  const lower = text.toLowerCase();
  return SECTOR_KEYWORDS.filter((s) =>
    s.keywords.some((kw) => lower.includes(kw)) ||
    s.contractKeywords.some((kw) => lower.includes(kw)) ||
    s.securityKeywords.some((kw) => lower.includes(kw)),
  );
}

export function isContractSignal(text: string): boolean {
  const lower = text.toLowerCase();
  const contractPatterns = [
    /\$[\d,.]+\s*[mb]illion/i,
    /\$[\d,.]+[mb]/i,
    /idiq/i,
    /task order/i,
    /contract award/i,
    /sbir phase/i,
    /gsa schedule/i,
    /other transaction authority/i,
    /ota agreement/i,
    /sole source/i,
    /multiple award/i,
    /\bota\b/,
    /billion.*contract|contract.*billion/i,
    /million.*award|award.*million/i,
  ];
  return contractPatterns.some((re) => re.test(lower));
}

export function isSecuritySignal(text: string): boolean {
  const lower = text.toLowerCase();
  return SECTOR_KEYWORDS.some((s) =>
    s.securityKeywords.some((kw) => lower.includes(kw)),
  );
}

export function extractContractAmount(text: string): number | null {
  const billions = text.match(/\$?([\d,.]+)\s*billion/i);
  if (billions) return parseFloat(billions[1].replace(/,/g, '')) * 1000;
  const millions = text.match(/\$?([\d,.]+)\s*million/i);
  if (millions) return parseFloat(millions[1].replace(/,/g, ''));
  const shortM = text.match(/\$?([\d,.]+)M\b/i);
  if (shortM) return parseFloat(shortM[1].replace(/,/g, ''));
  const shortB = text.match(/\$?([\d,.]+)B\b/i);
  if (shortB) return parseFloat(shortB[1].replace(/,/g, '')) * 1000;
  return null;
}
