#!/usr/bin/env python3
"""
NXT LINK Industry Observer — Catalog Updater
Reads classified products and generates TypeScript data entries
for technology-catalog.ts. Outputs for human review before merging.
"""

import json
from pathlib import Path
from datetime import datetime

INPUT_PATH = Path(__file__).parent / "output" / "classified_products.json"
OUTPUT_DIR = Path(__file__).parent / "output"

# Map industry areas to TechCategory
AREA_TO_CATEGORY: dict[str, str] = {
    "AI Analytics":             "AI/ML",
    "Cybersecurity":            "Cybersecurity",
    "Defense Systems":          "Defense",
    "Border Technology":        "Border Tech",
    "Manufacturing Tech":       "Manufacturing",
    "Energy Management":        "Energy",
    "Water Management":         "Energy",
    "Healthcare Tech":          "Healthcare",
    "Route Optimization":       "Logistics",
    "Supply Chain Visibility":  "Logistics",
    "Warehouse Automation":     "Logistics",
    "Fleet Management":         "Logistics",
    "Workflow Automation":      "Manufacturing",
    "Predictive Maintenance":   "Manufacturing",
}


def generate_tech_entry(product: dict, category: str) -> str:
    """Generate a TypeScript Technology object literal."""
    company = product.get("companies", ["Unknown"])[0] if product.get("companies") else "Unknown"
    title = product.get("title", "").replace("'", "\\'")
    problems = product.get("problems_addressed", [])
    problem_text = problems[0][:150] if problems else "Industry solution"

    tech_id = f"tech-discovered-{company.lower().replace(' ', '-')[:30]}"

    return f"""  {{
    id: '{tech_id}',
    name: '{company} — {title[:60]}',
    category: '{category}',
    description: '{problem_text.replace("'", "\\'")}',
    maturityLevel: 'growing',
    relatedVendorCount: 1,
    procurementSignalKeywords: [{', '.join(f"'{kw}'" for kw in product.get('classified_areas', [{}])[:2] if isinstance(kw, str))}],
    elPasoRelevance: 'medium',
  }},"""


def run_update():
    """Generate TypeScript entries from classified products."""
    if not INPUT_PATH.exists():
        print(f"[!] No classified products at {INPUT_PATH}")
        print("    Run classify_products.py first.")
        return

    with open(INPUT_PATH) as f:
        data = json.load(f)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Generate TypeScript entries per industry
    all_entries: dict[str, list[str]] = {}
    total = 0

    for slug, products in data.get("industries", {}).items():
        entries = []
        # Only process high-confidence products with companies
        good_products = [
            p for p in products
            if p.get("confidence", 0) >= 0.4
            and p.get("companies")
            and p.get("classified_areas")
        ]

        print(f"  {slug}: {len(good_products)} products qualify (of {len(products)} total)")

        for product in good_products[:20]:  # cap at 20 per industry
            area = product["classified_areas"][0]["area"]
            category = AREA_TO_CATEGORY.get(area, "AI/ML")
            entry = generate_tech_entry(product, category)
            entries.append(entry)

        all_entries[slug] = entries
        total += len(entries)

    # Write TypeScript file for review
    ts_output = OUTPUT_DIR / "new_catalog_entries.ts"
    with open(ts_output, "w") as f:
        f.write("// AUTO-GENERATED by industry-observer/update_catalog.py\n")
        f.write(f"// Generated: {datetime.utcnow().isoformat()}\n")
        f.write("// REVIEW BEFORE MERGING into technology-catalog.ts\n\n")
        f.write("import type { Technology } from '@/lib/data/technology-catalog';\n\n")
        f.write("export const DISCOVERED_TECHNOLOGIES: Technology[] = [\n")

        for slug, entries in all_entries.items():
            if entries:
                f.write(f"\n  // ── {slug} ──\n")
                for entry in entries:
                    f.write(f"{entry}\n")

        f.write("];\n")

    # Write summary JSON
    summary_path = OUTPUT_DIR / "update_summary.json"
    with open(summary_path, "w") as f:
        json.dump({
            "generated_at": datetime.utcnow().isoformat(),
            "total_entries": total,
            "by_industry": {slug: len(entries) for slug, entries in all_entries.items()},
            "review_file": str(ts_output),
        }, f, indent=2)

    print(f"\nDone! {total} entries generated → {ts_output}")
    print(f"Review the file before merging into technology-catalog.ts")


if __name__ == "__main__":
    run_update()
