// src/lib/feeds/mega/ai-ml-sources.ts
import type { FeedCategory } from '@/lib/agents/feed-agent';

type TopicMatrix = {
  prefix: string;
  category: FeedCategory;
  tier: 1 | 2 | 3 | 4;
  region?: 'el-paso' | 'texas' | 'national' | 'global';
  entities: string[];
  contexts: string[];
};

const GN = (q: string) =>
  `https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=en-US&gl=US&ceid=US:en`;

type FeedSourceEntry = {
  id: string;
  name: string;
  url: string;
  category: FeedCategory;
  tags: string[];
  tier: 1 | 2 | 3 | 4;
  region?: 'el-paso' | 'texas' | 'national' | 'global';
};

function expandMatrix(m: TopicMatrix): FeedSourceEntry[] {
  const results: FeedSourceEntry[] = [];
  for (const entity of m.entities) {
    for (const context of m.contexts) {
      const slug = `${entity} ${context}`.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40);
      const id = `${m.prefix}-${slug}`;
      const query = `${entity} ${context}`;
      results.push({
        id,
        name: `GN: ${entity.slice(0, 18)} ${context.slice(0, 10)}`,
        url: GN(query),
        category: m.category,
        tags: query.toLowerCase().split(/\s+/).filter(w => w.length > 2),
        tier: m.tier,
        region: m.region ?? 'national',
      });
    }
  }
  return results;
}

// ---------------------------------------------------------------------------
// AI_COMPANIES_MEGA — 120 entities × 20 contexts = 2,400 sources
// ---------------------------------------------------------------------------
const AI_COMPANIES_MEGA: TopicMatrix = {
  prefix: 'aicomp',
  category: 'AI/ML',
  tier: 3,
  region: 'global',
  entities: [
    'OpenAI',
    'Anthropic',
    'Google DeepMind',
    'Meta AI',
    'Microsoft AI',
    'xAI Grok',
    'NVIDIA AI',
    'AMD AI',
    'Intel AI',
    'Cerebras Systems',
    'Groq chips',
    'SambaNova Systems',
    'Cohere AI',
    'Mistral AI',
    'Stability AI',
    'Hugging Face',
    'Scale AI',
    'Databricks AI',
    'Weights Biases',
    'Anyscale Ray',
    'Lightning AI',
    'Mosaic ML',
    'Adept AI',
    'Inflection AI',
    'Character AI',
    'Runway ML',
    'Jasper AI',
    'Copy AI',
    'Synthesia AI',
    'DeepL translator',
    'Otter AI',
    'Assembly AI',
    'Eleven Labs',
    'Midjourney',
    'Perplexity AI',
    'Glean AI',
    'Reka AI',
    'AI21 Labs',
    'Aleph Alpha',
    'Covariant robotics',
    'Figure AI',
    '1X Technologies',
    'Agility Robotics',
    'Boston Dynamics',
    'Waymo',
    'Cruise autonomous',
    'Aurora Innovation',
    'Motional autonomous',
    'Zoox Amazon',
    'Nuro delivery',
    'TuSimple',
    'Plus Trucking',
    'Gatik autonomous',
    'Kodiak Robotics',
    'Torc Robotics',
    'Embark Technology',
    'Pony AI',
    'WeRide autonomous',
    'Argo AI',
    'Applied Intuition',
    'Cognition AI Devin',
    'Magic AI',
    'Poolside AI',
    'Sakana AI',
    'Together AI',
    'Fireworks AI',
    'Modal cloud',
    'Replicate ML',
    'Banana ML',
    'Baseten ML',
    'Anduril Lattice AI',
    'Shield AI Hivemind',
    'Palantir AIP',
    'C3 AI',
    'DataRobot',
    'H2O AI',
    'SAS AI',
    'Alteryx',
    'Domino Data Lab',
    'Tecton AI',
    'Feast ML',
    'Pinecone vectors',
    'Weaviate vectors',
    'Qdrant vectors',
    'Milvus vectors',
    'Chroma vectors',
    'LangChain',
    'LlamaIndex',
    'Haystack deepset',
    'Semantic Kernel',
    'AutoGPT',
    'AgentGPT',
    'CrewAI',
    'SuperAGI',
    'Fixie AI',
    'Vectara search',
    'Algolia AI',
    'Elastic AI',
    'Writer AI',
    'Typeface AI',
    'Adobe Firefly',
    'Canva AI',
    'Figma AI',
    'Notion AI',
    'Coda AI',
    'Zapier AI',
    'Make AI',
    'UiPath AI',
    'Automation Anywhere AI',
    'Celonis process',
    'Instabase AI',
    'Docugami AI',
    'Eigen Technologies',
    'Hyperscience AI',
    'Moveworks AI',
    'Observe AI',
    'Gong AI',
    'Clari AI',
    'People AI',
    'Lattice AI HR',
    'Eightfold AI',
    'Phenom People',
    'Beamery AI',
    'HireVue AI',
  ],
  contexts: [
    'product launch',
    'funding round',
    'enterprise deal',
    'research paper',
    'partnership announcement',
    'API release',
    'model benchmark',
    'open source release',
    'developer conference',
    'pricing change',
    'team hiring',
    'acquisition merger',
    'regulatory compliance',
    'safety alignment',
    'government contract',
    'customer deployment',
    'performance milestone',
    'competitive analysis',
    'market expansion',
    'technology breakthrough',
  ],
};

// ---------------------------------------------------------------------------
// AI_RESEARCH_MEGA — 60 entities × 25 contexts = 1,500 sources
// ---------------------------------------------------------------------------
const AI_RESEARCH_MEGA: TopicMatrix = {
  prefix: 'aires',
  category: 'AI/ML',
  tier: 3,
  region: 'global',
  entities: [
    'large language model',
    'multimodal AI model',
    'vision language model',
    'text-to-image generation',
    'text-to-video generation',
    'text-to-3D model',
    'speech synthesis AI',
    'music generation AI',
    'code generation AI',
    'protein folding AI',
    'drug discovery AI',
    'materials science AI',
    'weather prediction AI',
    'climate modeling AI',
    'autonomous driving AI',
    'robotic manipulation AI',
    'natural language processing',
    'machine translation AI',
    'sentiment analysis AI',
    'question answering AI',
    'text summarization AI',
    'named entity recognition',
    'knowledge graph AI',
    'graph neural network',
    'transformer architecture',
    'mixture of experts',
    'state space model',
    'diffusion model',
    'generative adversarial network',
    'variational autoencoder',
    'reinforcement learning',
    'deep reinforcement learning',
    'multi-agent reinforcement',
    'imitation learning',
    'world model AI',
    'planning AI system',
    'neural architecture search',
    'automated machine learning',
    'federated learning',
    'differential privacy ML',
    'model compression quantization',
    'knowledge distillation',
    'pruning neural network',
    'edge AI inference',
    'neuromorphic computing',
    'spiking neural network',
    'brain-computer interface',
    'AI chip accelerator',
    'optical computing AI',
    'quantum machine learning',
    'explainable AI XAI',
    'AI fairness bias',
    'AI safety alignment',
    'AI governance policy',
    'AI regulation law',
    'synthetic data generation',
    'data augmentation AI',
    'active learning AI',
    'few-shot learning',
    'zero-shot learning',
    'in-context learning',
  ],
  contexts: [
    'breakthrough paper',
    'benchmark record',
    'open source release',
    'commercial application',
    'industry adoption',
    'safety concern',
    'ethical debate',
    'regulatory proposal',
    'conference presentation',
    'workshop paper',
    'survey review',
    'technical blog',
    'dataset release',
    'competition result',
    'scaling law',
    'emergent capability',
    'failure mode',
    'robustness test',
    'adversarial attack',
    'red teaming',
    'alignment technique',
    'interpretability method',
    'efficiency improvement',
    'deployment guide',
    'industry report',
  ],
};

// ---------------------------------------------------------------------------
// AI_INFRASTRUCTURE_MEGA — 50 entities × 20 contexts = 1,000 sources
// ---------------------------------------------------------------------------
const AI_INFRASTRUCTURE_MEGA: TopicMatrix = {
  prefix: 'aiinfra',
  category: 'AI/ML',
  tier: 3,
  region: 'global',
  entities: [
    'NVIDIA H100 GPU',
    'NVIDIA H200 GPU',
    'NVIDIA B100 Blackwell',
    'NVIDIA Grace Hopper',
    'AMD MI300X GPU',
    'AMD MI400 GPU',
    'Intel Gaudi accelerator',
    'Google TPU v5',
    'Amazon Trainium chip',
    'Microsoft Maia chip',
    'Cerebras WSE chip',
    'Graphcore IPU',
    'Tenstorrent RISC-V AI',
    'Groq LPU chip',
    'SambaNova DataScale',
    'Qualcomm Cloud AI',
    'Apple Neural Engine',
    'Arm Neoverse AI',
    'TSMC CoWoS packaging',
    'HBM memory AI',
    'GDDR7 AI memory',
    'NVLink interconnect',
    'InfiniBand AI cluster',
    'Ethernet AI networking',
    'Broadcom AI switch',
    'Arista AI network',
    'data center AI cooling',
    'liquid cooling AI',
    'nuclear power AI datacenter',
    'renewable energy AI',
    'AI cluster construction',
    'sovereign AI cloud',
    'GPU cloud marketplace',
    'CoreWeave AI cloud',
    'Lambda Labs GPU',
    'Coreweave GPU',
    'RunPod cloud',
    'Vast AI marketplace',
    'Together AI inference',
    'Fireworks AI serving',
    'Modal serverless GPU',
    'vLLM inference engine',
    'TensorRT optimization',
    'ONNX Runtime',
    'Triton Inference Server',
    'Ray Serve',
    'BentoML',
    'Seldon Core',
    'MLflow platform',
    'Kubeflow ML',
    'Weights Biases experiment',
  ],
  contexts: [
    'product launch',
    'benchmark performance',
    'supply shortage',
    'pricing update',
    'capacity expansion',
    'energy consumption',
    'cooling innovation',
    'cluster deployment',
    'inference optimization',
    'training efficiency',
    'cost reduction',
    'availability update',
    'technical specification',
    'competitive comparison',
    'customer deployment',
    'partnership deal',
    'manufacturing update',
    'next generation preview',
    'developer toolkit',
    'reference architecture',
  ],
};

// ---------------------------------------------------------------------------
// AI_APPLICATIONS_MEGA — 70 entities × 20 contexts = 1,400 sources
// ---------------------------------------------------------------------------
const AI_APPLICATIONS_MEGA: TopicMatrix = {
  prefix: 'aiapp',
  category: 'AI/ML',
  tier: 4,
  region: 'national',
  entities: [
    'AI customer service chatbot',
    'AI coding assistant',
    'AI writing assistant',
    'AI legal document review',
    'AI medical diagnosis',
    'AI radiology imaging',
    'AI pathology analysis',
    'AI drug interaction check',
    'AI clinical trial design',
    'AI surgical robot',
    'AI financial trading',
    'AI credit scoring',
    'AI fraud detection',
    'AI anti-money laundering',
    'AI insurance underwriting',
    'AI supply chain optimization',
    'AI demand forecasting',
    'AI warehouse robotics',
    'AI quality inspection',
    'AI predictive maintenance',
    'AI process optimization',
    'AI energy grid management',
    'AI building energy',
    'AI agriculture precision',
    'AI crop monitoring drone',
    'AI livestock management',
    'AI food safety inspection',
    'AI weather forecasting',
    'AI disaster response',
    'AI wildfire detection',
    'AI flood prediction',
    'AI earthquake early warning',
    'AI traffic management',
    'AI autonomous vehicle',
    'AI drone delivery',
    'AI air traffic control',
    'AI satellite imagery',
    'AI geospatial analysis',
    'AI urban planning',
    'AI real estate valuation',
    'AI construction safety',
    'AI architecture design',
    'AI materials design',
    'AI semiconductor design',
    'AI chip verification',
    'AI network optimization',
    'AI 5G management',
    'AI content moderation',
    'AI recommendation engine',
    'AI personalization',
    'AI advertising targeting',
    'AI search engine',
    'AI translation service',
    'AI voice assistant',
    'AI meeting transcription',
    'AI video editing',
    'AI photo enhancement',
    'AI music composition',
    'AI game development',
    'AI animation rendering',
    'AI fashion design',
    'AI retail inventory',
    'AI price optimization',
    'AI restaurant management',
    'AI hotel operations',
    'AI travel planning',
    'AI education tutoring',
    'AI grading assessment',
    'AI hiring screening',
    'AI employee engagement',
  ],
  contexts: [
    'market size',
    'adoption rate',
    'ROI analysis',
    'customer case study',
    'product comparison',
    'regulatory requirement',
    'ethical concern',
    'bias detection',
    'accuracy improvement',
    'deployment challenge',
    'integration guide',
    'vendor selection',
    'cost benefit analysis',
    'industry standard',
    'best practice',
    'failure case',
    'success story',
    'technology trend',
    'innovation award',
    'startup funding',
  ],
};

// ---------------------------------------------------------------------------
// AI_POLICY_MEGA — 40 entities × 20 contexts = 800 sources
// ---------------------------------------------------------------------------
const AI_POLICY_MEGA: TopicMatrix = {
  prefix: 'aipol',
  category: 'AI/ML',
  tier: 4,
  region: 'national',
  entities: [
    'EU AI Act regulation',
    'US AI executive order',
    'AI safety institute NIST',
    'AI bill of rights',
    'California AI legislation',
    'New York AI hiring law',
    'Illinois AI video interview',
    'China AI regulation',
    'UK AI safety summit',
    'G7 AI governance',
    'UN AI resolution',
    'OECD AI principles',
    'UNESCO AI ethics',
    'AI copyright lawsuit',
    'AI deepfake regulation',
    'AI surveillance ban',
    'facial recognition ban',
    'autonomous weapons treaty',
    'AI liability framework',
    'AI patent law',
    'AI trade secret',
    'algorithmic accountability',
    'AI transparency requirement',
    'AI audit standard',
    'AI risk assessment',
    'AI impact assessment',
    'AI procurement government',
    'AI defense ethics',
    'AI healthcare regulation',
    'FDA AI medical device',
    'AI financial regulation',
    'SEC AI disclosure',
    'AI insurance regulation',
    'AI employment law',
    'AI education policy',
    'AI environmental impact',
    'AI competition antitrust',
    'AI open source policy',
    'AI export control',
    'AI semiconductor policy',
  ],
  contexts: [
    'legislative proposal',
    'regulatory guidance',
    'enforcement action',
    'compliance deadline',
    'industry comment',
    'public hearing',
    'executive order',
    'agency report',
    'court ruling',
    'settlement agreement',
    'international agreement',
    'standard publication',
    'certification program',
    'audit requirement',
    'penalty assessment',
    'safe harbor provision',
    'exemption granted',
    'stakeholder meeting',
    'white paper release',
    'implementation timeline',
  ],
};

// ---------------------------------------------------------------------------
// Final export — total: 2,400 + 1,500 + 1,000 + 1,400 + 800 = 7,100 entries
// (Google News deduplicates by query so effective unique feed URLs vary)
// ---------------------------------------------------------------------------
export const AI_ML_MEGA_SOURCES: FeedSourceEntry[] = [
  ...expandMatrix(AI_COMPANIES_MEGA),
  ...expandMatrix(AI_RESEARCH_MEGA),
  ...expandMatrix(AI_INFRASTRUCTURE_MEGA),
  ...expandMatrix(AI_APPLICATIONS_MEGA),
  ...expandMatrix(AI_POLICY_MEGA),
];
