// src/lib/feeds/mega/biotech-pharma-sources.ts
// NXT//LINK Biotech & Pharma Mega-Registry — 7,100+ intelligence sources
// Matrices × cross-product expansion = 7,100 unique Google News RSS feeds

import type { FeedCategory } from '@/lib/agents/feed-agent';

type TopicMatrix = {
  prefix: string;
  category: FeedCategory;
  tier: 1 | 2 | 3 | 4;
  region?: 'el-paso' | 'texas' | 'national' | 'global';
  entities: string[];
  contexts: string[];
};

const GN = (q: string) =>
  `https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=en-US&gl=US&ceid=US:en`;

type FeedSourceEntry = {
  id: string;
  name: string;
  url: string;
  category: FeedCategory;
  tags: string[];
  tier: 1 | 2 | 3 | 4;
  region?: 'el-paso' | 'texas' | 'national' | 'global';
};

function expandMatrix(m: TopicMatrix): FeedSourceEntry[] {
  const results: FeedSourceEntry[] = [];
  for (const entity of m.entities) {
    for (const context of m.contexts) {
      const slug = `${entity} ${context}`
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .slice(0, 40);
      const id = `${m.prefix}-${slug}`;
      const query = `${entity} ${context}`;
      results.push({
        id,
        name: `GN: ${entity.slice(0, 18)} ${context.slice(0, 10)}`,
        url: GN(query),
        category: m.category,
        tags: query
          .toLowerCase()
          .split(/\s+/)
          .filter((w) => w.length > 2),
        tier: m.tier,
        region: m.region ?? 'national',
      });
    }
  }
  return results;
}

// ─── MATRIX 1: PHARMA COMPANIES MEGA ──────────────────────────────────────────
// 100 entities × 25 contexts = 2,500 entries
const PHARMA_COMPANIES_MEGA: TopicMatrix = {
  prefix: 'bio-phar',
  category: 'General',
  tier: 3,
  region: 'global',
  entities: [
    'Pfizer',
    'Moderna',
    'Roche',
    'Novartis',
    'AstraZeneca',
    'Merck',
    'Johnson & Johnson',
    'AbbVie',
    'Bristol-Myers Squibb',
    'Sanofi',
    'Eli Lilly',
    'Amgen',
    'Gilead Sciences',
    'Regeneron',
    'Vertex Pharmaceuticals',
    'BioNTech',
    'Genentech',
    'Takeda',
    'GSK',
    'Bayer',
    'Novo Nordisk',
    'CSL Behring',
    'Biogen',
    'Illumina',
    '10x Genomics',
    'CRISPR Therapeutics',
    'Intellia Therapeutics',
    'Editas Medicine',
    'Beam Therapeutics',
    'Arctus Biotherapeutics',
    'Alnylam Pharmaceuticals',
    'Ionis Pharmaceuticals',
    'Seagen',
    'Danaher',
    'Thermo Fisher Scientific',
    'Agilent Technologies',
    'Bio-Rad Laboratories',
    'Waters Corporation',
    'PerkinElmer',
    'Bruker',
    'Becton Dickinson',
    'Medtronic',
    'Abbott Laboratories',
    'Stryker',
    'Edwards Lifesciences',
    'Intuitive Surgical',
    'Boston Scientific',
    'Zimmer Biomet',
    'Hologic',
    'ResMed',
    'Siemens Healthineers',
    'GE Healthcare',
    'Philips Healthcare',
    'Varian Medical Systems',
    'Elekta',
    'Accuray',
    'ViewRay',
    'IBA Group',
    'Mevion Medical Systems',
    'ProTom International',
    'Hitachi Healthcare',
    'Canon Medical',
    'Samsung Medison',
    'Mindray',
    'Shenzhen New Industries Biomedical',
    'BGI Genomics',
    'WuXi AppTec',
    'WuXi Biologics',
    'Samsung Biologics',
    'Lonza',
    'Catalent',
    'Patheon',
    'Recipharm',
    'Siegfried',
    'Fareva',
    'Boehringer Ingelheim',
    'Teva Pharmaceutical',
    'Mylan',
    'Sandoz',
    'Hikma Pharmaceuticals',
    'Lupin',
    'Sun Pharma',
    'Dr Reddy Laboratories',
    'Cipla',
    'Aurobindo Pharma',
    'Glenmark Pharmaceuticals',
    'Torrent Pharmaceuticals',
    'Zydus Lifesciences',
    'Alkem Laboratories',
    'Biocon',
    'Jubilant Pharmova',
    'Divis Laboratories',
    'Laurus Labs',
    'Piramal Pharma',
    'Hetero Drugs',
    'Granules India',
    'Natco Pharma',
    'Strides Pharma',
    'Gland Pharma',
    'Suven Pharmaceuticals',
  ],
  contexts: [
    'contract',
    'FDA approval',
    'clinical trial',
    'patent',
    'acquisition',
    'partnership',
    'revenue',
    'stock',
    'layoff',
    'hiring',
    'research',
    'breakthrough',
    'pipeline',
    'Phase 3',
    'Phase 2',
    'IPO',
    'SPAC',
    'SEC filing',
    'earnings',
    'expansion',
    'manufacturing',
    'supply chain',
    'recall',
    'safety',
    'regulatory',
  ],
};

// ─── MATRIX 2: BIOTECH FIELDS MEGA ────────────────────────────────────────────
// 60 entities × 30 contexts = 1,800 entries
const BIOTECH_FIELDS_MEGA: TopicMatrix = {
  prefix: 'bio-field',
  category: 'General',
  tier: 4,
  region: 'global',
  entities: [
    'gene therapy',
    'CRISPR',
    'mRNA technology',
    'CAR-T therapy',
    'cell therapy',
    'synthetic biology',
    'protein engineering',
    'antibody drug conjugate',
    'bispecific antibody',
    'gene editing',
    'epigenetics',
    'proteomics',
    'metabolomics',
    'single-cell sequencing',
    'spatial transcriptomics',
    'organoid',
    'bioprinting',
    'nanomedicine',
    'immunotherapy',
    'checkpoint inhibitor',
    'adoptive cell therapy',
    'tumor-infiltrating lymphocyte',
    'oncolytic virus',
    'microbiome therapy',
    'phage therapy',
    'antisense oligonucleotide',
    'siRNA',
    'gene silencing',
    'optogenetics',
    'brain-computer interface',
    'neural interface',
    'digital therapeutics',
    'biomarker discovery',
    'companion diagnostics',
    'liquid biopsy',
    'circulating tumor DNA',
    'exosome diagnostics',
    'CRISPR diagnostics',
    'point-of-care testing',
    'lab-on-chip',
    'organ-on-chip',
    'xenotransplantation',
    '3D bioprinting organs',
    'artificial organs',
    'stem cell therapy',
    'iPSC',
    'mesenchymal stem cell',
    'hematopoietic stem cell',
    'tissue engineering',
    'regenerative medicine',
    'wound healing',
    'bone regeneration',
    'cartilage repair',
    'dental implant biology',
    'hair follicle regeneration',
    'anti-aging biology',
    'senolytic drugs',
    'telomere therapy',
    'longevity research',
    'caloric restriction mimetics',
  ],
  contexts: [
    'breakthrough',
    'clinical trial',
    'FDA',
    'patent filed',
    'research paper',
    'funding',
    'investment',
    'market size',
    'adoption',
    'regulation',
    'ethical debate',
    'manufacturing',
    'scale-up',
    'pricing',
    'competition',
    'startup',
    'university research',
    'government funding',
    'NIH grant',
    'DARPA project',
    'EU regulation',
    'China competition',
    'India growth',
    'partnership',
    'commercial launch',
    'Phase 1',
    'Phase 2',
    'Phase 3',
    'approval',
    'market entry',
  ],
};

// ─── MATRIX 3: MEDICAL DEVICES MEGA ───────────────────────────────────────────
// 50 entities × 20 contexts = 1,000 entries
const MEDICAL_DEVICES_MEGA: TopicMatrix = {
  prefix: 'bio-dev',
  category: 'General',
  tier: 3,
  region: 'national',
  entities: [
    'surgical robot',
    'MRI scanner',
    'CT scanner',
    'ultrasound system',
    'X-ray digital',
    'PET scanner',
    'endoscope',
    'laparoscopic device',
    'cardiac pacemaker',
    'defibrillator',
    'insulin pump',
    'continuous glucose monitor',
    'pulse oximeter',
    'ventilator',
    'infusion pump',
    'dialysis machine',
    'cochlear implant',
    'retinal implant',
    'prosthetic limb',
    'exoskeleton medical',
    'wearable health monitor',
    'smartwatch health',
    'blood pressure monitor',
    'sleep tracker',
    'ECG wearable',
    'hearing aid digital',
    'dental implant',
    'orthopedic implant',
    'spinal implant',
    'hip replacement',
    'knee replacement',
    'cardiac stent',
    'catheter',
    'biopsy needle',
    'surgical stapler',
    'wound closure device',
    'suture material',
    'hemostatic agent',
    'bone cement',
    'surgical mesh',
    'hernia repair device',
    'breast implant',
    'cosmetic laser device',
    'laser surgery system',
    'cryotherapy device',
    'radiofrequency ablation',
    'microwave ablation',
    'HIFU device',
    'lithotripter',
    'ophthalmic laser',
  ],
  contexts: [
    'FDA clearance',
    'patent',
    'recall',
    'market share',
    'revenue',
    'acquisition',
    'clinical study',
    'innovation',
    'pricing',
    'competition',
    'manufacturing',
    'regulation',
    'CE marking',
    'reimbursement',
    'hospital adoption',
    'training',
    'cybersecurity',
    'interoperability',
    'AI integration',
    'remote monitoring',
  ],
};

// ─── MATRIX 4: DRUG DISCOVERY MEGA ────────────────────────────────────────────
// 40 entities × 20 contexts = 800 entries
const DRUG_DISCOVERY_MEGA: TopicMatrix = {
  prefix: 'bio-disc',
  category: 'General',
  tier: 4,
  region: 'global',
  entities: [
    'AI drug discovery',
    'computational chemistry',
    'molecular dynamics simulation',
    'virtual screening',
    'high-throughput screening',
    'fragment-based drug design',
    'structure-based drug design',
    'pharmacophore modeling',
    'QSAR modeling',
    'ADMET prediction',
    'drug repurposing',
    'polypharmacology',
    'target identification',
    'target validation',
    'hit-to-lead optimization',
    'lead optimization chemistry',
    'preclinical development',
    'toxicology testing',
    'formulation development',
    'drug delivery system',
    'nanoparticle drug delivery',
    'liposomal delivery',
    'polymer drug conjugate',
    'prodrug design',
    'controlled release formulation',
    'sustained release',
    'transdermal delivery',
    'inhalation drug delivery',
    'ocular drug delivery',
    'intrathecal delivery',
    'subcutaneous delivery',
    'oral peptide delivery',
    'GLP-1 agonist',
    'SGLT2 inhibitor',
    'JAK inhibitor',
    'BTK inhibitor',
    'CDK inhibitor',
    'PARP inhibitor',
    'PD-1 inhibitor',
    'KRAS inhibitor',
  ],
  contexts: [
    'breakthrough',
    'startup',
    'funding',
    'partnership',
    'patent',
    'AI model',
    'clinical trial',
    'FDA',
    'approval',
    'market',
    'revenue',
    'competition',
    'acquisition',
    'research',
    'publication',
    'dataset',
    'algorithm',
    'prediction',
    'validation',
    'regulatory',
  ],
};

// ─── MATRIX 5: HEALTH SYSTEMS MEGA ────────────────────────────────────────────
// 50 entities × 20 contexts = 1,000 entries
const HEALTH_SYSTEMS_MEGA: TopicMatrix = {
  prefix: 'bio-sys',
  category: 'General',
  tier: 3,
  region: 'national',
  entities: [
    'electronic health record',
    'telemedicine',
    'remote patient monitoring',
    'hospital information system',
    'clinical decision support',
    'health data analytics',
    'population health management',
    'value-based care',
    'bundled payment',
    'accountable care organization',
    'health information exchange',
    'interoperability standard',
    'FHIR',
    'HL7',
    'DICOM',
    'ICD coding',
    'medical billing automation',
    'revenue cycle management',
    'prior authorization automation',
    'clinical trial management',
    'patient recruitment',
    'decentralized clinical trial',
    'real-world evidence',
    'health economics',
    'pharmacoeconomics',
    'outcomes research',
    'patient-reported outcomes',
    'digital health app',
    'mobile health',
    'health chatbot',
    'symptom checker',
    'mental health app',
    'addiction treatment app',
    'physical therapy app',
    'medication adherence',
    'pill reminder app',
    'pharmacy automation',
    'medication dispensing robot',
    'compounding pharmacy',
    'specialty pharmacy',
    'biosimilar',
    'generic drug',
    '340B program',
    'pharmacy benefit manager',
    'drug pricing',
    'insulin pricing',
    'orphan drug',
    'rare disease treatment',
    'precision medicine',
    'pharmacogenomics',
  ],
  contexts: [
    'implementation',
    'adoption',
    'regulation',
    'HIPAA',
    'breach',
    'investment',
    'startup',
    'acquisition',
    'market growth',
    'innovation',
    'policy',
    'CMS rule',
    'Medicaid',
    'Medicare',
    'insurance',
    'reimbursement',
    'AI integration',
    'automation',
    'cost reduction',
    'outcome improvement',
  ],
};

// ─── EXPORT ────────────────────────────────────────────────────────────────────

export const BIOTECH_PHARMA_MEGA_SOURCES: FeedSourceEntry[] = [
  ...expandMatrix(PHARMA_COMPANIES_MEGA),  // 100 × 25 = 2,500
  ...expandMatrix(BIOTECH_FIELDS_MEGA),    //  60 × 30 = 1,800
  ...expandMatrix(MEDICAL_DEVICES_MEGA),   //  50 × 20 = 1,000
  ...expandMatrix(DRUG_DISCOVERY_MEGA),    //  40 × 20 =   800
  ...expandMatrix(HEALTH_SYSTEMS_MEGA),    //  50 × 20 = 1,000
  // ─────────────────────────────────────────────────────────
  // TOTAL: 7,100 entries
];

export type { FeedSourceEntry };
