// src/lib/feeds/mega/crime-sources.ts
import type { FeedCategory } from '@/lib/agents/feed-agent';

type TopicMatrix = {
  prefix: string;
  category: FeedCategory;
  tier: 1 | 2 | 3 | 4;
  region?: 'el-paso' | 'texas' | 'national' | 'global';
  entities: string[];
  contexts: string[];
};

const GN = (q: string) =>
  `https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=en-US&gl=US&ceid=US:en`;

type FeedSourceEntry = {
  id: string;
  name: string;
  url: string;
  category: FeedCategory;
  tags: string[];
  tier: 1 | 2 | 3 | 4;
  region?: 'el-paso' | 'texas' | 'national' | 'global';
};

function expandMatrix(m: TopicMatrix): FeedSourceEntry[] {
  const results: FeedSourceEntry[] = [];
  for (const entity of m.entities) {
    for (const context of m.contexts) {
      const slug = `${entity} ${context}`.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40);
      const id = `${m.prefix}-${slug}`;
      const query = `${entity} ${context}`;
      results.push({
        id,
        name: `GN: ${entity.slice(0, 18)} ${context.slice(0, 10)}`,
        url: GN(query),
        category: m.category,
        tags: query.toLowerCase().split(/\s+/).filter(w => w.length > 2),
        tier: m.tier,
        region: m.region ?? 'national',
      });
    }
  }
  return results;
}

// ---------------------------------------------------------------------------
// CRIME_ELPASO_MEGA — 40 entities × 37 contexts = 1,480 sources
// ---------------------------------------------------------------------------
const CRIME_ELPASO_MEGA: TopicMatrix = {
  prefix: 'crm-ep',
  category: 'Crime',
  tier: 2,
  region: 'el-paso',
  entities: [
    'El Paso Texas',
    'Ciudad Juarez',
    'Northeast El Paso',
    'East El Paso',
    'Central El Paso',
    'West El Paso',
    'Lower Valley El Paso',
    'Upper Valley El Paso',
    'Mission Hills El Paso',
    'Kern Place El Paso',
    'Sunset Heights El Paso',
    'Segundo Barrio El Paso',
    'Chihuahuita El Paso',
    'Five Points El Paso',
    'Montecillo El Paso',
    'Westside El Paso',
    'Canutillo Texas',
    'Horizon City Texas',
    'Socorro Texas',
    'San Elizario Texas',
    'Clint Texas',
    'Fabens Texas',
    'Anthony Texas',
    'Sunland Park NM',
    'Las Cruces NM',
    'Dona Ana County NM',
    'Fort Bliss area',
    'UTEP campus area',
    'Cielo Vista El Paso',
    'Bassett Place area',
    'El Paso International Airport area',
    'Downtown El Paso',
    'Oregon Street El Paso',
    'Mesa Street El Paso',
    'Montana Avenue El Paso',
    'Dyer Street El Paso',
    'Alameda Avenue El Paso',
    'Gateway Boulevard El Paso',
    'Zaragoza Road El Paso',
    'Americas Avenue El Paso',
  ],
  contexts: [
    'shooting incident',
    'homicide investigation',
    'robbery arrest',
    'burglary report',
    'auto theft',
    'carjacking',
    'assault battery',
    'domestic violence',
    'drug arrest',
    'DWI DUI',
    'traffic fatality',
    'hit and run',
    'missing person',
    'kidnapping',
    'sexual assault',
    'arson fire',
    'vandalism',
    'gang activity',
    'police pursuit',
    'SWAT standoff',
    'officer-involved shooting',
    'border patrol incident',
    'immigration enforcement',
    'smuggling operation',
    'drug seizure',
    'fentanyl bust',
    'weapons trafficking',
    'human trafficking',
    'fraud scheme',
    'identity theft',
    'cybercrime',
    'organized crime',
    'cold case',
    'fugitive capture',
    'amber alert',
    'silver alert',
    'public safety alert',
  ],
};

// ---------------------------------------------------------------------------
// CRIME_BORDER_MEGA — 30 entities × 30 contexts = 900 sources
// ---------------------------------------------------------------------------
const CRIME_BORDER_MEGA: TopicMatrix = {
  prefix: 'crm-bdr',
  category: 'Crime',
  tier: 2,
  region: 'el-paso',
  entities: [
    'CBP Customs Border Protection',
    'Border Patrol El Paso Sector',
    'ICE Homeland Security',
    'DEA Drug Enforcement',
    'FBI El Paso',
    'ATF El Paso',
    'US Marshals Service',
    'El Paso Police Department',
    'El Paso County Sheriff',
    'Texas DPS Rangers',
    'New Mexico State Police',
    'Dona Ana County Sheriff',
    'Juarez Municipal Police',
    'Chihuahua State Police',
    'Mexican National Guard',
    'Mexican Army border',
    'Bridges International El Paso',
    'Paso del Norte bridge',
    'Stanton Street bridge',
    'Ysleta port of entry',
    'Santa Teresa port',
    'Columbus port of entry',
    'Bridge of the Americas',
    'Tornillo port of entry',
    'Fabens port of entry',
    'Chihuahua cartel',
    'Sinaloa cartel',
    'CJNG cartel',
    'La Linea organization',
    'Barrio Azteca gang',
  ],
  contexts: [
    'drug seizure',
    'fentanyl interdiction',
    'methamphetamine bust',
    'cocaine seizure',
    'heroin interdiction',
    'marijuana seizure',
    'human smuggling',
    'migrant rescue',
    'tunnel discovery',
    'smuggling vehicle',
    'stash house raid',
    'money laundering',
    'currency seizure',
    'weapons trafficking',
    'ammunition smuggling',
    'stolen vehicle recovery',
    'fugitive arrest',
    'extradition',
    'cartel violence',
    'murder rate',
    'kidnapping extortion',
    'body discovery',
    'mass grave',
    'corruption arrest',
    'officer indictment',
    'joint operation',
    'intelligence sharing',
    'surveillance technology',
    'border wall breach',
    'port of entry security',
  ],
};

// ---------------------------------------------------------------------------
// CRIME_TEXAS_MEGA — 50 entities × 20 contexts = 1,000 sources
// ---------------------------------------------------------------------------
const CRIME_TEXAS_MEGA: TopicMatrix = {
  prefix: 'crm-tx',
  category: 'Crime',
  tier: 3,
  region: 'texas',
  entities: [
    'Houston Texas crime',
    'Dallas Texas crime',
    'San Antonio Texas crime',
    'Austin Texas crime',
    'Fort Worth Texas crime',
    'Arlington Texas crime',
    'Corpus Christi crime',
    'Lubbock Texas crime',
    'Laredo Texas crime',
    'McAllen Texas crime',
    'Brownsville Texas crime',
    'Amarillo Texas crime',
    'Midland Odessa crime',
    'Beaumont Texas crime',
    'Waco Texas crime',
    'Abilene Texas crime',
    'Tyler Texas crime',
    'College Station crime',
    'Round Rock Texas crime',
    'Killeen Fort Hood crime',
    'Temple Texas crime',
    'San Marcos Texas crime',
    'New Braunfels crime',
    'Victoria Texas crime',
    'Longview Texas crime',
    'Texarkana Texas crime',
    'Lufkin Texas crime',
    'Del Rio Texas crime',
    'Eagle Pass Texas crime',
    'Presidio Texas crime',
    'Alpine Texas crime',
    'Pecos Texas crime',
    'Marfa Texas crime',
    'Van Horn Texas crime',
    'Sierra Blanca Texas crime',
    'Tornillo Texas crime',
    'Texas Rangers investigation',
    'Texas DPS operation',
    'Texas Highway Patrol',
    'TDCJ Texas prison',
    'Texas Juvenile Justice',
    'Houston DEA',
    'Dallas FBI',
    'San Antonio ATF',
    'Austin Police',
    'Harris County Sheriff',
    'Dallas County Sheriff',
    'Bexar County Sheriff',
    'Travis County Sheriff',
    'Tarrant County crime',
  ],
  contexts: [
    'shooting incident',
    'homicide rate',
    'robbery trend',
    'burglary ring',
    'auto theft ring',
    'drug trafficking',
    'gang indictment',
    'organized crime',
    'mass shooting',
    'school threat',
    'workplace violence',
    'domestic terrorism',
    'hate crime',
    'public corruption',
    'police misconduct',
    'officer killed',
    'cold case solved',
    'serial crime',
    'crime statistics',
    'crime prevention',
  ],
};

// ---------------------------------------------------------------------------
// CRIME_NATIONAL_MEGA — 64 entities × 20 contexts = 1,280 sources
// ---------------------------------------------------------------------------
const CRIME_NATIONAL_MEGA: TopicMatrix = {
  prefix: 'crm-nat',
  category: 'Crime',
  tier: 3,
  region: 'national',
  entities: [
    'FBI investigation',
    'DEA operation',
    'ATF enforcement',
    'US Marshals fugitive',
    'Secret Service',
    'DHS Homeland Security',
    'DOJ Department Justice',
    'US Attorney prosecution',
    'ICE enforcement',
    'CBP nationwide',
    'HSI investigation',
    'USPS inspection',
    'IRS criminal investigation',
    'CDC public health crime',
    'EPA environmental crime',
    'SEC financial crime',
    'CFTC enforcement',
    'FinCEN suspicious activity',
    'OFAC sanctions',
    'violent crime rate',
    'property crime rate',
    'drug overdose epidemic',
    'fentanyl crisis',
    'opioid trafficking',
    'methamphetamine production',
    'cocaine trafficking',
    'marijuana legalization',
    'synthetic drug',
    'dark web marketplace',
    'ransomware crime',
    'business email compromise',
    'romance scam',
    'elder fraud',
    'identity theft',
    'credit card fraud',
    'wire fraud',
    'money laundering',
    'terrorist financing',
    'domestic terrorism',
    'white supremacist',
    'mass shooting',
    'school shooting',
    'workplace violence',
    'hate crime',
    'human trafficking',
    'child exploitation',
    'CSAM enforcement',
    'missing persons',
    'cold case investigation',
    'wrongful conviction',
    'DNA forensics',
    'ballistic evidence',
    'digital forensics',
    'surveillance technology',
    'predictive policing',
    'body camera',
    'police reform',
    'qualified immunity',
    'bail reform',
    'sentencing reform',
    'prison reform',
    'juvenile justice',
    'gang task force',
    'RICO prosecution',
  ],
  contexts: [
    'arrest indictment',
    'conviction sentence',
    'investigation update',
    'task force operation',
    'seizure forfeiture',
    'victim notification',
    'press conference',
    'grand jury',
    'plea agreement',
    'trial verdict',
    'appeal ruling',
    'policy announcement',
    'statistics report',
    'trend analysis',
    'prevention program',
    'community outreach',
    'technology deployment',
    'funding allocation',
    'interagency cooperation',
    'international operation',
  ],
};

// ---------------------------------------------------------------------------
// CRIME_CYBERCRIME_MEGA — 50 entities × 25 contexts = 1,250 sources
// ---------------------------------------------------------------------------
const CRIME_CYBERCRIME_MEGA: TopicMatrix = {
  prefix: 'crm-cyber',
  category: 'Crime',
  tier: 3,
  region: 'national',
  entities: [
    'ransomware attack',
    'phishing campaign',
    'business email compromise',
    'identity theft ring',
    'credit card fraud',
    'cryptocurrency scam',
    'romance fraud',
    'investment fraud',
    'Ponzi scheme',
    'wire fraud',
    'bank fraud',
    'insurance fraud',
    'healthcare fraud',
    'tax fraud',
    'procurement fraud',
    'government contract fraud',
    'election fraud',
    'voter fraud',
    'intellectual property theft',
    'trade secret theft',
    'economic espionage',
    'insider threat',
    'corporate espionage',
    'social engineering attack',
    'vishing voice phishing',
    'smishing SMS phishing',
    'SIM swap fraud',
    'account takeover',
    'synthetic identity',
    'deepfake fraud',
    'pig butchering scam',
    'advance fee fraud',
    'lottery scam',
    'tech support scam',
    'IRS impersonation',
    'Social Security scam',
    'Medicare fraud',
    'student loan scam',
    'job scam',
    'rental scam',
    'shopping fraud',
    'auction fraud',
    'counterfeit goods',
    'dark web drug sales',
    'dark web weapons',
    'dark web services',
    'cryptocurrency mixing',
    'tumbling service',
    'DDoS for hire',
    'malware distribution',
  ],
  contexts: [
    'FBI warning',
    'IC3 report',
    'FTC alert',
    'Secret Service investigation',
    'DOJ indictment',
    'SEC action',
    'CFTC enforcement',
    'state AG prosecution',
    'international takedown',
    'Europol operation',
    'Interpol notice',
    'victim count',
    'financial loss estimate',
    'arrest warrant',
    'extradition request',
    'asset seizure',
    'plea deal',
    'sentencing hearing',
    'restitution order',
    'prevention advisory',
    'awareness campaign',
    'law enforcement training',
    'technology tool',
    'forensic analysis',
    'recovery effort',
  ],
};

// ---------------------------------------------------------------------------
// CRIME_INTERNATIONAL_MEGA — 42 entities × 20 contexts = 840 sources
// ---------------------------------------------------------------------------
const CRIME_INTERNATIONAL_MEGA: TopicMatrix = {
  prefix: 'crm-intl',
  category: 'Crime',
  tier: 4,
  region: 'global',
  entities: [
    'Mexican cartel organization',
    'Sinaloa cartel',
    'CJNG Jalisco cartel',
    'Gulf cartel',
    'Los Zetas',
    'Beltran Leyva',
    'Juarez cartel',
    'Tijuana cartel',
    'Caborca cartel',
    'Colombian guerrilla',
    'Venezuelan gang Tren de Aragua',
    'MS-13 gang',
    '18th Street gang',
    'Latin Kings',
    'Bloods Crips',
    'Italian Mafia Ndrangheta',
    'Russian organized crime',
    'Chinese triads',
    'Japanese Yakuza',
    'Nigerian fraud network',
    'West African crime',
    'Eastern European cybercrime',
    'Balkan organized crime',
    'Albanian mafia',
    'Irish organized crime',
    'Chechen crime',
    'Turkish organized crime',
    'Brazilian PCC',
    'Afghan opium',
    'Golden Triangle drugs',
    'Hezbollah financing',
    'Hamas financing',
    'ISIS financing',
    'Al Qaeda financing',
    'North Korea cyber theft',
    'Iran sanctions evasion',
    'Russian sanctions evasion',
    'China fentanyl precursor',
    'India pharma fraud',
    'dark web administration',
    'cryptocurrency laundering',
    'transnational criminal organization',
  ],
  contexts: [
    'cartel leader arrest',
    'extradition proceeding',
    'kingpin designation',
    'sanctions designation',
    'OFAC listing',
    'money seizure',
    'drug haul',
    'weapons cache',
    'tunnel network',
    'submarine seizure',
    'aircraft interception',
    'maritime interdiction',
    'land seizure',
    'asset forfeiture',
    'gang indictment',
    'RICO prosecution',
    'conspiracy charge',
    'murder charge',
    'witness protection',
    'intelligence report',
  ],
};

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------
export const CRIME_MEGA_SOURCES: FeedSourceEntry[] = [
  ...expandMatrix(CRIME_ELPASO_MEGA),
  ...expandMatrix(CRIME_BORDER_MEGA),
  ...expandMatrix(CRIME_TEXAS_MEGA),
  ...expandMatrix(CRIME_NATIONAL_MEGA),
  ...expandMatrix(CRIME_CYBERCRIME_MEGA),
  ...expandMatrix(CRIME_INTERNATIONAL_MEGA),
];
