// src/lib/feeds/mega/defense-sources.ts
// NXT//LINK Defense Mega-Registry — 10,000+ intelligence sources
// Matrices × cross-product expansion = 10,100+ unique Google News RSS feeds

import type { FeedCategory } from '@/lib/agents/feed-agent';

type TopicMatrix = {
  prefix: string;
  category: FeedCategory;
  tier: 1 | 2 | 3 | 4;
  region?: 'el-paso' | 'texas' | 'national' | 'global';
  entities: string[];
  contexts: string[];
};

const GN = (q: string) =>
  `https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=en-US&gl=US&ceid=US:en`;

type FeedSourceEntry = {
  id: string;
  name: string;
  url: string;
  category: FeedCategory;
  tags: string[];
  tier: 1 | 2 | 3 | 4;
  region?: 'el-paso' | 'texas' | 'national' | 'global';
};

function expandMatrix(m: TopicMatrix): FeedSourceEntry[] {
  const results: FeedSourceEntry[] = [];
  for (const entity of m.entities) {
    for (const context of m.contexts) {
      const slug = `${entity} ${context}`
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .slice(0, 40);
      const id = `${m.prefix}-${slug}`;
      const query = `${entity} ${context}`;
      results.push({
        id,
        name: `GN: ${entity.slice(0, 18)} ${context.slice(0, 10)}`,
        url: GN(query),
        category: m.category,
        tags: query
          .toLowerCase()
          .split(/\s+/)
          .filter((w) => w.length > 2),
        tier: m.tier,
        region: m.region ?? 'national',
      });
    }
  }
  return results;
}

// ─── MATRIX 1: DEFENSE CONTRACTORS MEGA ───────────────────────────────────────
// 80 entities × 20 contexts = 1,600 entries
const DEFENSE_CONTRACTORS_MEGA: TopicMatrix = {
  prefix: 'def-con',
  category: 'Defense',
  tier: 3,
  region: 'national',
  entities: [
    'Lockheed Martin',
    'RTX Raytheon',
    'Northrop Grumman',
    'Boeing Defense',
    'L3Harris Technologies',
    'General Dynamics',
    'BAE Systems',
    'SAIC',
    'Leidos',
    'Booz Allen Hamilton',
    'CACI International',
    'Peraton',
    'Amentum',
    'Textron Systems',
    'Kratos Defense',
    'Parsons Corp',
    'ManTech International',
    'Elbit Systems America',
    'Leonardo DRS',
    'Curtiss-Wright',
    'Mercury Systems',
    'Aerojet Rocketdyne',
    'Sierra Nevada Corporation',
    'V2X Inc',
    'KBR Defense',
    'Maxar Technologies',
    'Jacobs Engineering Defense',
    'DXC Technology Defense',
    'Anduril Industries',
    'Shield AI',
    'Palantir Defense',
    'AeroVironment',
    'Saab Defense US',
    'Thales Group USA',
    'Rheinmetall America',
    'Rafael Advanced Defense Systems',
    'Hanwha Defense USA',
    'Hyundai Rotem Defense',
    'ST Engineering America',
    'Israel Aerospace Industries',
    'Turkish Aerospace Industries',
    'Babcock International',
    'Rolls-Royce Defence',
    'MBDA Missile Systems',
    'Kongsberg Defence USA',
    'Diehl Defence',
    'HENSOLDT USA',
    'Indra Sistemas USA',
    'Navantia USA',
    'Fincantieri Marinette Marine',
    'Naval Group',
    'Dassault Aviation Defense',
    'Airbus Defence Space',
    'Safran Electronics Defense',
    'Chemring Group',
    'Ultra Electronics',
    'QinetiQ North America',
    'Cobham Advanced Electronic Systems',
    'Thales Australia',
    'CAE Defense Security',
    'BWX Technologies',
    'Dynetics Leidos',
    'Teledyne FLIR Defense',
    'Ball Aerospace',
    'Orbital ATK Northrop',
    'SpaceX Starshield',
    'Blue Origin Defense',
    'Rocket Lab Defense',
    'General Atomics Aeronautical',
    'Insitu Boeing Defense',
    'Textron Aviation Defense',
    'Bell Helicopter Textron',
    'Sikorsky Lockheed Martin',
    'Collins Aerospace RTX',
    'Pratt Whitney Military Engines',
    'GE Aerospace Military',
    'Vectrus V2X',
    'DLT Solutions',
    'Engility Leidos',
    'KEYW Jacobs',
  ],
  contexts: [
    'contract award',
    'Pentagon deal',
    'military deployment',
    'new technology',
    'quarterly earnings',
    'hiring expansion',
    'R&D investment',
    'joint venture',
    'acquisition merger',
    'subcontract award',
    'prototype test',
    'LRIP production',
    'full-rate production',
    'foreign military sale',
    'technology transfer',
    'cybersecurity upgrade',
    'AI integration',
    'autonomous systems',
    'supply chain resilience',
    'sustainment contract',
  ],
};

// ─── MATRIX 2: DEFENSE PROGRAMS MEGA ──────────────────────────────────────────
// 60 entities × 15 contexts = 900 entries
const DEFENSE_PROGRAMS_MEGA: TopicMatrix = {
  prefix: 'def-pgm',
  category: 'Defense',
  tier: 4,
  region: 'national',
  entities: [
    'JADC2 Joint All Domain Command',
    'Project Convergence Army',
    'IVAS Integrated Visual Augmentation',
    'ABMS Advanced Battle Management',
    'Project Overmatch Navy',
    'Replicator Initiative DoD',
    'NGAD Next Gen Air Dominance',
    'B-21 Raider bomber',
    'Sentinel ICBM LGM-35',
    'Columbia class submarine',
    'FLRAA Future Long Range Assault',
    'FARA Future Attack Reconnaissance',
    'Stryker IM-SHORAD modernization',
    'Bradley XM30 replacement',
    'Abrams M1E3 upgrade',
    'LTAMDS radar Raytheon',
    'IBCS Integrated Air Missile Defense',
    'Patriot PAC-3 upgrade',
    'THAAD Terminal High Altitude',
    'Iron Dome US deployment',
    'Aegis Ashore missile defense',
    'SM-6 Extended Range missile',
    'Tomahawk Block V upgrade',
    'JASSM-ER joint standoff',
    'LRASM anti-ship missile',
    'ARRW hypersonic boost glide',
    'Dark Eagle LRHW hypersonic',
    'Conventional Prompt Strike Navy',
    'MQ-25 Stingray tanker drone',
    'MQ-9B Reaper extended range',
    'RQ-180 stealth reconnaissance',
    'Collaborative Combat Aircraft CCA',
    'XQ-58 Valkyrie loyal wingman',
    'Skyborg autonomy system',
    'Golden Horde networked munitions',
    'ROGUE Fires capability',
    'HBTSS hypersonic tracking satellite',
    'SDA Space Development Agency satellites',
    'OPIR overhead persistent infrared',
    'GPS III next generation',
    'Wideband Global SATCOM WGS',
    'MUOS mobile user objective system',
    'AEHF Advanced Extremely High Freq',
    'Space Fence radar Kwajalein',
    'Ground Based Midcourse Defense',
    'Next Generation Interceptor NGI',
    'Glide Phase Interceptor GPI',
    'Counter-UAS Joint CUAS',
    'EWPMT electronic warfare planning',
    'MFEW multi-function electronic warfare',
    'TLS Electronic Attack system',
    'SEWIP Block III electronic warfare',
    'EMARSS Enhanced Medium Altitude',
    'DCGS Distributed Common Ground',
    'Army Cloud ACOE enterprise',
    'CJADC2 combined joint all domain',
    'TITAN Tactical Intelligence Targeting',
    'BREN board-level replacement',
    'Paladin howitzer upgrade PIM',
    'Excalibur precision round upgrade',
  ],
  contexts: [
    'test milestone achieved',
    'contract award announcement',
    'budget request FY2026',
    'deployment timeline update',
    'operational capability declaration',
    'technology demonstration event',
    'competitive bid solicitation',
    'cost overrun investigation',
    'schedule delay report',
    'Congressional hearing testimony',
    'GAO audit report',
    'program of record approval',
    'Milestone C decision',
    'Nunn-McCurdy breach notification',
    'technology insertion contract',
  ],
};

// ─── MATRIX 3: DEFENSE INSTALLATIONS MEGA ─────────────────────────────────────
// 50 entities × 15 contexts = 750 entries
const DEFENSE_INSTALLATIONS_MEGA: TopicMatrix = {
  prefix: 'def-inst',
  category: 'Defense',
  tier: 3,
  region: 'national',
  entities: [
    'Fort Bliss Texas',
    'White Sands Missile Range',
    'Holloman AFB New Mexico',
    'Fort Cavazos Texas',
    'Fort Sam Houston Texas',
    'Lackland AFB Joint Base',
    'Sandia National Laboratories',
    'Los Alamos National Laboratory',
    'Fort Liberty North Carolina',
    'Fort Moore Georgia',
    'Fort Eisenhower Georgia',
    'Fort Johnson Louisiana',
    'Camp Pendleton California',
    'Fort Irwin National Training Center',
    'Vandenberg Space Force Base',
    'Edwards AFB California',
    'Nellis AFB Nevada',
    'Hill AFB Utah',
    'Fort Sill Oklahoma',
    'Redstone Arsenal Alabama',
    'Aberdeen Proving Ground Maryland',
    'Picatinny Arsenal New Jersey',
    'Naval Station Norfolk Virginia',
    'Joint Base Pearl Harbor-Hickam',
    'Camp Lejeune North Carolina',
    'Fort Drum New York',
    'Joint Base Lewis-McChord Washington',
    'Fort Riley Kansas',
    'Fort Stewart Georgia',
    'NAS Patuxent River Maryland',
    'Wright-Patterson AFB Ohio',
    'Eglin AFB Florida',
    'Tyndall AFB Florida',
    'Patrick Space Force Base',
    'Cape Canaveral Space Force Station',
    'Kirtland AFB New Mexico',
    'Dugway Proving Ground Utah',
    'Yuma Proving Ground Arizona',
    'Naval Surface Warfare Center Dahlgren',
    'Army Research Laboratory ARL',
    'DARPA Arlington Virginia',
    'Pentagon Arlington Virginia',
    'Naval Postgraduate School Monterey',
    'West Point Military Academy',
    'Air Force Academy Colorado',
    'Naval Academy Annapolis',
    'Fort Wainwright Alaska',
    'Joint Base Elmendorf-Richardson',
    'USMC Twentynine Palms',
    'Naval War College Newport',
  ],
  contexts: [
    'technology modernization contract',
    'construction project award',
    'unit activation ceremony',
    'large-scale exercise',
    'contractor hiring initiative',
    'infrastructure upgrade program',
    'energy resilience project',
    'cybersecurity upgrade deployment',
    '5G private network deployment',
    'testing facility expansion',
    'environmental remediation contract',
    'BRAC realignment update',
    'housing privatization contract',
    'ISR mission expansion',
    'supply depot modernization',
  ],
};

// ─── MATRIX 4: DEFENSE TOPICS MEGA ────────────────────────────────────────────
// 60 entities × 20 contexts = 1,200 entries
const DEFENSE_TOPICS_MEGA: TopicMatrix = {
  prefix: 'def-top',
  category: 'Defense',
  tier: 4,
  region: 'national',
  entities: [
    'artificial intelligence military applications',
    'autonomous weapons systems lethal',
    'directed energy weapons laser',
    'hypersonic glide vehicle development',
    'quantum computing defense application',
    'space domain awareness warfare',
    'cyber warfare offensive defensive',
    'electronic warfare spectrum',
    'undersea warfare submarine',
    'amphibious assault operations technology',
    'urban warfare military technology',
    'counter-terrorism tactical technology',
    'border security technology sensor',
    'missile defense intercept technology',
    'air defense integrated systems',
    'naval mine warfare counter-mine',
    'anti-submarine warfare ASW',
    'special operations forces technology',
    'intelligence surveillance reconnaissance ISR',
    'signals intelligence SIGINT collection',
    'human intelligence HUMINT modernization',
    'open source intelligence OSINT tools',
    'geospatial intelligence GEOINT satellite',
    'measurement signatures intelligence MASINT',
    'counter-intelligence technology CI',
    'force protection active passive',
    'explosive ordnance disposal robot',
    'chemical biological radiological nuclear CBRN',
    'unmanned ground vehicle UGV',
    'unmanned surface vessel USV',
    'unmanned undersea vehicle UUV',
    'robotic combat vehicle RCV',
    'military exoskeleton powered armor',
    'augmented reality heads-up display',
    'synthetic training environment STE',
    'live virtual constructive training',
    'military 5G tactical network',
    'tactical edge computing battlefield',
    'satellite communications military LEO',
    'jam-resistant GPS resilient PNT',
    'resilient positioning navigation timing',
    'supply chain security defense industrial',
    'additive manufacturing 3D printing military',
    'predictive maintenance sustainment AI',
    'digital twin military platform',
    'model based systems engineering MBSE',
    'DevSecOps defense software factory',
    'zero trust architecture DoD',
    'cloud computing military JWCC',
    'microelectronics trusted foundry defense',
    'quantum sensing military navigation',
    'counter-drone anti-UAS technology',
    'swarm drone autonomous coordination',
    'directed energy counter-UAS',
    'hypersonic defense intercept',
    'space launch vehicle military',
    'secure communications encryption military',
    'biometric identification military',
    'soldier lethality program',
    'next generation squad weapon',
  ],
  contexts: [
    'technology breakthrough announcement',
    'contract opportunity solicitation',
    'program milestone achievement',
    'budget allocation request',
    'industry day event',
    'white paper publication',
    'RFI request for information',
    'RFP request for proposals',
    'source selection award',
    'bid protest filed',
    'SBIR Phase II award',
    'STTR research award',
    'OTA other transaction agreement',
    'DARPA research grant',
    'interoperability testing event',
    'operational test evaluation',
    'fielding deployment announcement',
    'Congressional appropriation approval',
    'GAO accountability report',
    'international partner cooperation',
  ],
};

// ─── MATRIX 5: DEFENSE GEOPOLITICS MEGA ───────────────────────────────────────
// 50 entities × 20 contexts = 1,000 entries
const DEFENSE_GEOPOLITICS_MEGA: TopicMatrix = {
  prefix: 'def-geo',
  category: 'Defense',
  tier: 4,
  region: 'global',
  entities: [
    'China PLA military modernization',
    'Russia military reform armament',
    'North Korea nuclear ballistic missile',
    'Iran military asymmetric capability',
    'Taiwan defense buildup self-reliance',
    'South China Sea territorial dispute',
    'Ukraine conflict weapons technology',
    'NATO integrated deterrence defense',
    'AUKUS submarine advanced capability',
    'India defense modernization Make-in-India',
    'Japan Self-Defense Force expansion',
    'South Korea defense industry export',
    'Saudi Arabia Vision 2030 defense',
    'UAE defense technology procurement',
    'Israel defense innovation IDF',
    'Poland military buildup NATO flank',
    'Germany Bundeswehr reform funding',
    'UK defense procurement review',
    'France military operations Africa',
    'Turkey defense industry export ASELSAN',
    'Australia defense industry sovereign',
    'Canada NORAD modernization Arctic',
    'Pacific Island security competition',
    'Arctic military operations sovereignty',
    'African security cooperation AFRICOM',
    'Central Asia security great power',
    'Middle East arms race balance',
    'Indo-Pacific strategy quadrilateral',
    'European defense integration PESCO',
    'Five Eyes intelligence sharing',
    'NATO cyber defense collective',
    'UN peacekeeping technology modernization',
    'arms control negotiations treaty',
    'nuclear deterrence modernization triad',
    'chemical weapons Syria accountability',
    'space debris military threat',
    'cyber norms international law',
    'maritime security Indo-Pacific freedom',
    'Red Sea Houthi threat shipping',
    'Baltic Sea NATO defense posture',
    'Finland Sweden NATO integration',
    'Romania Bulgaria NATO flank',
    'Georgia Ukraine NATO aspirations',
    'Philippines US basing agreement',
    'Japan US extended deterrence',
    'South Korea US alliance modernization',
    'Gulf Cooperation Council defense',
    'African Union peace operations',
    'Latin America US Southern Command',
    'Arctic Council security breakdown',
  ],
  contexts: [
    'arms deal agreement',
    'joint military exercise',
    'diplomatic summit outcome',
    'defense budget increase',
    'technology transfer restriction',
    'intelligence sharing agreement',
    'joint development program',
    'sanctions impact assessment',
    'strategic competition escalation',
    'alliance strengthening announcement',
    'threat assessment report',
    'capability gap analysis',
    'force structure reform',
    'procurement decision announcement',
    'defense export approval',
    'security assistance package',
    'military advisor deployment',
    'interoperability exercise result',
    'diplomatic incident response',
    'strategic deterrence signal',
  ],
};

// ─── MATRIX 6: DEFENSE BUDGET & ACQUISITION MEGA ──────────────────────────────
// 50 entities × 15 contexts = 750 entries
const DEFENSE_BUDGET_MEGA: TopicMatrix = {
  prefix: 'def-bud',
  category: 'Defense',
  tier: 4,
  region: 'national',
  entities: [
    'DoD defense budget FY2026',
    'DoD defense budget FY2027',
    'Pentagon continuing resolution',
    'defense appropriations House',
    'defense appropriations Senate',
    'NDAA National Defense Authorization',
    'Army budget request modernization',
    'Navy budget request shipbuilding',
    'Air Force budget request aircraft',
    'Space Force budget research',
    'Marine Corps budget modernization',
    'Special Operations Command budget',
    'Cyber Command budget operations',
    'Defense Intelligence Agency budget',
    'NSA budget signals intelligence',
    'DIA Defense Intelligence budget',
    'MDA Missile Defense Agency budget',
    'DARPA research budget frontier',
    'DIU Defense Innovation Unit budget',
    'AFWERX Air Force innovation budget',
    'Army Futures Command investment',
    'NavalX innovation funding',
    'Marine Corps Warfighting Lab',
    'DoD SBIR STTR funding',
    'OTA other transaction authority',
    'defense contract obligations growth',
    'Pentagon acquisition reform initiative',
    'defense industrial base investment',
    'DoD supply chain resilience fund',
    'strategic stockpile replenishment',
    'munitions production surge funding',
    'shipbuilding industrial base investment',
    'DoD workforce hiring STEM',
    'defense declassified technology spinoff',
    'Pentagon audit compliance progress',
    'DoD financial management reform',
    'cost-plus contract reform',
    'fixed-price incentive contract',
    'performance-based logistics contract',
    'DoD data analytics enterprise',
    'joint warfighting cloud capability',
    'defense health program budget',
    'military construction appropriations',
    'DoD real property modernization',
    'base operations support contract',
    'installation energy resilience fund',
    'DoD environmental remediation budget',
    'weapon system affordability review',
    'program executive office awards',
    'defense contract audit DCAA',
  ],
  contexts: [
    'budget justification released',
    'Congressional mark-up hearing',
    'continuing resolution impact',
    'rescission proposal announced',
    'supplemental request submitted',
    'omnibus package inclusion',
    'authorization bill passage',
    'appropriation signed law',
    'program increase requested',
    'program cut proposed',
    'reprogramming request filed',
    'audit finding published',
    'cost growth reported',
    'efficiency initiative launched',
    'reform legislation introduced',
  ],
};

// ─── MATRIX 7: DEFENSE TECHNOLOGY DOMAINS MEGA ────────────────────────────────
// 60 entities × 20 contexts = 1,200 entries
const DEFENSE_TECHNOLOGY_MEGA: TopicMatrix = {
  prefix: 'def-tech',
  category: 'Defense',
  tier: 3,
  region: 'national',
  entities: [
    'large language model military AI',
    'computer vision target recognition',
    'autonomous navigation battlefield',
    'reinforcement learning combat simulation',
    'federated learning classified data',
    'explainable AI military decision',
    'digital engineering model-based',
    'cloud-native defense software',
    'software defined radio tactical',
    'cognitive electronic warfare',
    'photonic radar LIDAR military',
    'quantum radar detection stealth',
    'multispectral infrared sensor',
    'hyperspectral imaging ISR',
    'synthetic aperture radar SAR satellite',
    'ground moving target indicator GMTI',
    'electro-optical infrared EO/IR seeker',
    'gallium nitride GaN radar power',
    'active electronically scanned array AESA',
    'low probability of intercept radar',
    'laser rangefinder designator military',
    'high energy laser weapon HEL',
    'high power microwave HPM weapon',
    'rail gun electromagnetic launch',
    'electric propulsion naval ship',
    'fuel cell silent watch military',
    'hybrid electric vehicle military',
    'advanced battery energy storage military',
    'solid-state battery military vehicle',
    'advanced materials composite armor',
    'reactive armor active protection',
    'hard kill active protection system',
    'soft kill countermeasure system',
    'electronic countermeasure jamming pod',
    'infrared countermeasure DIRCM towed',
    'chaff flare dispenser advanced',
    'passive radar bistatic military',
    'acoustic sensor array underwater',
    'magnetic anomaly detector submarine',
    'sonar towed array passive',
    'acoustic torpedo advanced',
    'supercavitating projectile underwater',
    'underwater vehicle glider autonomous',
    'persistent maritime surveillance',
    'over-the-horizon radar OTH',
    'ballistic missile early warning radar',
    'space situational awareness SSA',
    'cyber effects operation offensive',
    'zero-day exploit military use',
    'critical infrastructure protection OT',
    'quantum key distribution secure comm',
    'post-quantum cryptography transition',
    'blockchain supply chain defense',
    'digital thread manufacturing defense',
    'prognostics health management PHM',
    'condition-based maintenance CBM+',
    'additive manufacturing repair depot',
    'cold spray coating repair',
    'bioremediation environmental military',
    'non-lethal weapons crowd control',
  ],
  contexts: [
    'technology readiness level advance',
    'prototype demonstration success',
    'field test evaluation result',
    'DARPA program award announcement',
    'AFWERX challenge winner',
    'Army xTechSearch finalist',
    'DIU project agreement signed',
    'SBIR Phase I selection',
    'SBIR Phase II transition',
    'SBIR Phase III production',
    'OTA prototype agreement',
    'OTA follow-on production',
    'patent application filed',
    'patent granted DoD technology',
    'spin-off commercial application',
    'foreign adversary counter capability',
    'joint capability technology demonstration',
    'operational needs statement filed',
    'urgent materiel release',
    'fielding decision approved',
  ],
};

// ─── MATRIX 8: DEFENSE PERSONNEL & WORKFORCE MEGA ─────────────────────────────
// 50 entities × 15 contexts = 750 entries
const DEFENSE_PERSONNEL_MEGA: TopicMatrix = {
  prefix: 'def-pers',
  category: 'Defense',
  tier: 4,
  region: 'national',
  entities: [
    'Army recruiting retention crisis',
    'Navy recruiting bonus incentive',
    'Air Force pilot shortage retention',
    'Marine Corps force structure reduction',
    'Space Force guardians recruitment',
    'Special Forces Green Beret selection',
    'Navy SEAL BUD/S training',
    'Army Ranger school graduation',
    'Delta Force selection classified',
    'AFSOC special operations airmen',
    'Cyber Command workforce CISA',
    'DoD civilian workforce hiring',
    'defense contractor workforce shortage',
    'defense STEM pipeline initiative',
    'military spouse employment initiative',
    'veteran transition employment',
    'ROTC enrollment college military',
    'Service Academy class appointment',
    'Officer Candidate School commissioning',
    'Warrant Officer program aviation',
    'enlisted bonus critical MOS',
    'military housing BAH reform',
    'VA healthcare access reform',
    'military mental health suicide',
    'soldier fitness performance optimization',
    'DoD diversity equity inclusion',
    'military promotions selection board',
    'general officer flag officer nomination',
    'Senate Armed Services confirmation',
    'DoD political appointee nominee',
    'Joint Chiefs of Staff rotation',
    'CJCS Chairman nominee confirmation',
    'SECDEF Secretary Defense policy',
    'service secretary nomination',
    'Undersecretary Defense Acquisition',
    'Undersecretary Defense Research',
    'Undersecretary Defense Policy',
    'combatant command INDOPACOM leadership',
    'EUCOM commander transition',
    'CENTCOM operations Middle East',
    'NORTHCOM homeland defense',
    'SOUTHCOM Latin America operations',
    'AFRICOM Africa operations command',
    'TRANSCOM logistics command modernization',
    'STRATCOM nuclear deterrence posture',
    'CYBERCOM workforce expansion',
    'SOCOM special operations budget',
    'DLA Defense Logistics Agency',
    'defense attaché network intelligence',
    'JROTC high school program',
  ],
  contexts: [
    'recruitment shortfall announced',
    'retention bonus program',
    'force structure change',
    'leadership confirmation hearing',
    'policy guidance published',
    'whistleblower complaint filed',
    'misconduct investigation opened',
    'innovation program launched',
    'diversity initiative announced',
    'education benefit expanded',
    'training modernization contract',
    'fitness standard revision',
    'mental health program expanded',
    'housing allowance increased',
    'deployment extension announced',
  ],
};

// ─── MATRIX 9: DEFENSE ACQUISITION POLICY MEGA ────────────────────────────────
// 60 entities × 20 contexts = 1,200 entries
const DEFENSE_ACQUISITION_MEGA: TopicMatrix = {
  prefix: 'def-acq',
  category: 'Defense',
  tier: 3,
  region: 'national',
  entities: [
    'FAR Federal Acquisition Regulation',
    'DFARS defense supplement regulation',
    'SAM.gov contract opportunity',
    'beta.SAM.gov solicitation',
    'USASpending.gov defense award',
    'FPDS contract data system',
    'PIEE procurement procurement system',
    'Army Contracting Command',
    'Navy NAVSEA contracting',
    'Air Force Life Cycle Management',
    'AFLCMC Wright-Patterson procurement',
    'DLA Defense Logistics Agency procurement',
    'GSA federal supply schedule',
    'GSA MAS multiple award schedule',
    'SEWC strategic enterprise wide contract',
    'ITES-SW IT enterprise solutions',
    'OASIS+ professional services',
    'Alliant 3 IT services',
    'SEWP NASA NITAAC contract',
    'CIO-SP4 NIH IT contract',
    'DISA ENCORE IT services',
    'Army ITES enterprise IT',
    'Navy NGEN desktop services',
    'Air Force NETCENTS network services',
    'DEOS defense enterprise office',
    'milCloud 2.0 DoD infrastructure',
    'JWCC Joint Warfighting Cloud',
    'DoD C3 Competitive Cloud',
    'Army ACOE cloud enterprise',
    'NIPRNet SIPRNet modernization',
    'DODIN Department Defense Info Network',
    'CMMC 2.0 cybersecurity maturity',
    'NIST 800-171 compliance DoD',
    'FedRAMP cloud security authorization',
    'DoD IL4 IL5 IL6 cloud',
    'controlled unclassified information CUI',
    'ITAR export control defense',
    'EAR Export Administration Regulations',
    'DSP-5 export license technology',
    'section 889 Huawei ban DoD',
    'FOCI foreign ownership control',
    'CFIUS national security review',
    'industrial security clearance FSO',
    'facility clearance DoD contractor',
    'small business set-aside 8a',
    'HUBZone small business contract',
    'SDVOSB veteran-owned set-aside',
    'WOSB woman-owned set-aside',
    'AbilityOne mandatory source',
    'defense mentor-protege program',
    'rapid acquisition authority DoD',
    'undefinitized contract action UCA',
    'special access program SAP acquisition',
    'black budget classified procurement',
    'commercial solutions opening CSO',
    'innovative contracting mechanisms',
    'value engineering change proposal',
    'earned value management EVM',
    'should-cost analysis DoD review',
    'independent cost estimate ICE',
  ],
  contexts: [
    'regulation update published',
    'policy deviation approved',
    'solicitation released SAM.gov',
    'award notice announced',
    'protest filed GAO',
    'protest sustained overturned',
    'Congressional direction enacted',
    'audit finding issued',
    'compliance requirement added',
    'small business rule change',
    'cybersecurity mandate expanded',
    'export control update',
    'waiver approved granted',
    'new vehicle established',
    'task order competed awarded',
    'indefinite delivery contract',
    'multiple award selection',
    'cost reimbursement terms',
    'fixed price competition',
    'performance metric revised',
  ],
};

// ─── MATRIX 10: DEFENSE BORDER & SOUTHWEST MEGA ───────────────────────────────
// 50 entities × 15 contexts = 750 entries
const DEFENSE_BORDER_SOUTHWEST_MEGA: TopicMatrix = {
  prefix: 'def-sw',
  category: 'Defense',
  tier: 2,
  region: 'texas',
  entities: [
    'Fort Bliss 1st Armored Division',
    'Fort Bliss Air Defense Artillery',
    'Fort Bliss William Beaumont Army Medical',
    'Fort Bliss Biggs Army Airfield',
    'White Sands Missile Range testing',
    'White Sands hypersonic test corridor',
    'Holloman AFB F-16 training',
    'Holloman AFB German Air Force',
    'New Mexico National Guard deployment',
    'Texas National Guard border mission',
    'El Paso defense contractor hub',
    'El Paso Joint Processing Center',
    'CBP El Paso Sector technology',
    'Border Patrol El Paso surveillance',
    'Tornillo Guadalupe Port of Entry',
    'Paso del Norte defense logistics',
    'Operation Lone Star Texas',
    'Operation Guardian Support border',
    'Southwest Border Task Force',
    'NORTHCOM border support mission',
    'USNORTHCOM homeland defense Texas',
    'Customs Border Protection technology',
    'CBP Air Marine Operations Southwest',
    'ICE enforcement El Paso Texas',
    'DEA Southwest Border operation',
    'FBI El Paso field office counterterrorism',
    'HSI Homeland Security El Paso',
    'Joint Intelligence Operations Center',
    'USBP surveillance tower system',
    'integrated fixed tower IFT Southwest',
    'remote video surveillance system',
    'Autonomous Surveillance Towers AST',
    'P-3 Orion CBP maritime patrol',
    'UH-60 Black Hawk border patrol',
    'unmanned aerial systems CBP border',
    'ground sensor seismic acoustic border',
    'aerostat radar TARS surveillance',
    'forward operating base FOB border',
    'El Paso Intelligence Center EPIC',
    'FinCEN financial crime border',
    'cartel surveillance counternarcotic',
    'drug tunnel detection technology',
    'fentanyl precursor detection CBP',
    'human trafficking detection border',
    'biometric entry exit border',
    'e-Passport RFID border crossing',
    'NEXUS SENTRI trusted traveler',
    'ACE Automated Commercial Environment',
    'USMCA cargo inspection technology',
    'non-intrusive inspection NII scanner',
  ],
  contexts: [
    'technology deployment contract',
    'sensor system upgrade',
    'personnel deployment order',
    'operational exercise completed',
    'contract award announcement',
    'drug seizure technology success',
    'infrastructure construction awarded',
    'federal grant funding received',
    'inter-agency cooperation agreement',
    'Congressional field hearing',
    'DHS oversight report',
    'GAO review published',
    'court injunction legal challenge',
    'budget supplemental request',
    'new technology field test',
  ],
};

// ─── EXPORT ────────────────────────────────────────────────────────────────────

export const DEFENSE_MEGA_SOURCES: FeedSourceEntry[] = [
  ...expandMatrix(DEFENSE_CONTRACTORS_MEGA),   // 80 × 20 = 1,600
  ...expandMatrix(DEFENSE_PROGRAMS_MEGA),       // 60 × 15 =   900
  ...expandMatrix(DEFENSE_INSTALLATIONS_MEGA),  // 50 × 15 =   750
  ...expandMatrix(DEFENSE_TOPICS_MEGA),         // 60 × 20 = 1,200
  ...expandMatrix(DEFENSE_GEOPOLITICS_MEGA),    // 50 × 20 = 1,000
  ...expandMatrix(DEFENSE_BUDGET_MEGA),         // 50 × 15 =   750
  ...expandMatrix(DEFENSE_TECHNOLOGY_MEGA),     // 60 × 20 = 1,200
  ...expandMatrix(DEFENSE_PERSONNEL_MEGA),      // 50 × 15 =   750
  ...expandMatrix(DEFENSE_ACQUISITION_MEGA),    // 60 × 20 = 1,200
  ...expandMatrix(DEFENSE_BORDER_SOUTHWEST_MEGA), // 50 × 15 = 750
  // ─────────────────────────────────────────────────────────
  // TOTAL: 10,100 entries
];

export type { FeedSourceEntry };
