// src/lib/feeds/mega/energy-sources.ts
import type { FeedCategory } from '@/lib/agents/feed-agent';

type TopicMatrix = {
  prefix: string;
  category: FeedCategory;
  tier: 1 | 2 | 3 | 4;
  region?: 'el-paso' | 'texas' | 'national' | 'global';
  entities: string[];
  contexts: string[];
};

const GN = (q: string) =>
  `https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=en-US&gl=US&ceid=US:en`;

type FeedSourceEntry = {
  id: string;
  name: string;
  url: string;
  category: FeedCategory;
  tags: string[];
  tier: 1 | 2 | 3 | 4;
  region?: 'el-paso' | 'texas' | 'national' | 'global';
};

function expandMatrix(m: TopicMatrix): FeedSourceEntry[] {
  const results: FeedSourceEntry[] = [];
  for (const entity of m.entities) {
    for (const context of m.contexts) {
      const slug = `${entity} ${context}`.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40);
      const id = `${m.prefix}-${slug}`;
      const query = `${entity} ${context}`;
      results.push({
        id,
        name: `GN: ${entity.slice(0, 18)} ${context.slice(0, 10)}`,
        url: GN(query),
        category: m.category,
        tags: query.toLowerCase().split(/\s+/).filter(w => w.length > 2),
        tier: m.tier,
        region: m.region ?? 'national',
      });
    }
  }
  return results;
}

// ---------------------------------------------------------------------------
// ENERGY_OIL_GAS_MEGA — 70 entities × 20 contexts = 1,400 sources
// ---------------------------------------------------------------------------
const ENERGY_OIL_GAS_MEGA: TopicMatrix = {
  prefix: 'oilgas',
  category: 'Energy',
  tier: 3,
  region: 'global',
  entities: [
    'ExxonMobil',
    'Chevron',
    'ConocoPhillips',
    'Pioneer Natural Resources',
    'Devon Energy',
    'Diamondback Energy',
    'EOG Resources',
    'Marathon Petroleum',
    'Valero Energy',
    'Phillips 66',
    'HF Sinclair',
    'Par Pacific',
    'CVR Energy',
    'PBF Energy',
    'Shell plc',
    'BP plc',
    'TotalEnergies',
    'Eni',
    'Equinor',
    'Repsol',
    'Petrobras',
    'Saudi Aramco',
    'ADNOC',
    'QatarEnergy',
    'Kuwait Petroleum',
    'CNOOC China',
    'PetroChina',
    'Sinopec',
    'ONGC India',
    'Reliance Industries',
    'Schlumberger SLB',
    'Halliburton',
    'Baker Hughes',
    'NOV National Oilwell',
    'TechnipFMC',
    'Weatherford',
    'ChampionX',
    'Cactus Inc',
    'ProPetro',
    'Liberty Energy',
    'Patterson-UTI',
    'Helmerich Payne',
    'Nabors Industries',
    'Precision Drilling',
    'Core Labs',
    'RPC Inc',
    'Archrock compressor',
    'USA Compression',
    'Targa Resources',
    'Enterprise Products',
    'Plains All American',
    'MPLX pipeline',
    'Energy Transfer',
    'Williams Companies',
    'Kinder Morgan',
    'ONEOK pipeline',
    'Western Midstream',
    'Crestwood Equity',
    'DT Midstream',
    'Cheniere Energy',
    'Sempra Infrastructure',
    'Tellurian LNG',
    'NextDecade LNG',
    'Venture Global LNG',
    'Freeport LNG',
    'Cameron LNG',
    'Sabine Pass LNG',
    'Corpus Christi LNG',
    'Golden Pass LNG',
    'Permian Basin operator',
  ],
  contexts: [
    'quarterly earnings',
    'production update',
    'exploration discovery',
    'drilling program',
    'pipeline construction',
    'LNG export',
    'refinery operations',
    'merger acquisition',
    'dividend increase',
    'capital expenditure',
    'technology deployment',
    'carbon capture',
    'methane reduction',
    'ESG reporting',
    'regulatory filing',
    'OPEC decision',
    'price forecast',
    'reserve estimate',
    'well completion',
    'hydraulic fracturing',
  ],
};

// ---------------------------------------------------------------------------
// ENERGY_RENEWABLES_MEGA — 72 entities × 20 contexts = 1,440 sources
// ---------------------------------------------------------------------------
const ENERGY_RENEWABLES_MEGA: TopicMatrix = {
  prefix: 'renew',
  category: 'Energy',
  tier: 3,
  region: 'global',
  entities: [
    'NextEra Energy',
    'Duke Energy',
    'Southern Company',
    'Dominion Energy',
    'AES Corporation',
    'Enel Green Power',
    'Iberdrola',
    'Orsted wind',
    'Vestas Wind',
    'Siemens Gamesa',
    'GE Vernova wind',
    'Nordex wind',
    'Goldwind China',
    'Envision Energy',
    'TPI Composites',
    'First Solar',
    'Canadian Solar',
    'JinkoSolar',
    'JA Solar',
    'LONGi Green Energy',
    'Trina Solar',
    'Risen Energy',
    'Maxeon Solar',
    'SunPower',
    'Enphase Energy',
    'SolarEdge Technology',
    'Array Technologies',
    'Nextracker solar',
    'Shoals Technologies',
    'Sunnova Energy',
    'Sunrun residential',
    'Vivint Solar',
    'Freedom Forever',
    'Palmetto solar',
    'Tesla Energy',
    'Bloom Energy fuel cell',
    'Plug Power hydrogen',
    'Ballard Power hydrogen',
    'FuelCell Energy',
    'Cummins hydrogen',
    'Air Liquide hydrogen',
    'Linde hydrogen',
    'Nel ASA electrolyzer',
    'ITM Power electrolyzer',
    'Hyzon Motors hydrogen',
    'Nikola hydrogen truck',
    'Fluence Energy storage',
    'Tesla Megapack',
    'BYD energy storage',
    'CATL energy storage',
    'LG Energy Solution',
    'Samsung SDI',
    'SK Innovation',
    'Panasonic Energy',
    'QuantumScape solid state',
    'Solid Power battery',
    'Form Energy iron-air',
    'ESS Inc iron flow',
    'EOS Energy zinc',
    'Ambri liquid metal',
    'Malta Inc thermal',
    'Stem Inc storage',
    'Wartsila grid',
    'GE Grid Solutions',
    'Hitachi Energy',
    'Siemens Energy grid',
    'ABB power grid',
    'Schneider Electric grid',
    'SMA Solar inverter',
    'Fronius inverter',
    'Power Electronics',
    'Avangrid renewables',
  ],
  contexts: [
    'project announcement',
    'capacity milestone',
    'technology breakthrough',
    'quarterly earnings',
    'government incentive',
    'tax credit',
    'PPA agreement',
    'grid connection',
    'permitting approval',
    'construction start',
    'commercial operation',
    'repowering project',
    'offshore development',
    'community solar',
    'virtual power plant',
    'battery deployment',
    'green hydrogen',
    'electrolysis production',
    'fuel cell deployment',
    'storage integration',
  ],
};

// ---------------------------------------------------------------------------
// ENERGY_NUCLEAR_MEGA — 42 entities × 25 contexts = 1,050 sources
// ---------------------------------------------------------------------------
const ENERGY_NUCLEAR_MEGA: TopicMatrix = {
  prefix: 'nuclear',
  category: 'Energy',
  tier: 3,
  region: 'global',
  entities: [
    'NuScale Power',
    'Oklo nuclear',
    'X-energy reactor',
    'TerraPower',
    'Kairos Power',
    'Terrestrial Energy',
    'GE Hitachi Nuclear',
    'Westinghouse Electric',
    'Framatome nuclear',
    'EDF nuclear',
    'KHNP Korea Hydro',
    'Rosatom Russia',
    'CGN China General Nuclear',
    'CNNC China National Nuclear',
    'Holtec International',
    'BWX Technologies',
    'Centrus Energy',
    'URENCO enrichment',
    'Cameco uranium',
    'Kazatomprom uranium',
    'Energy Fuels',
    'Uranium Energy Corp',
    'Denison Mines',
    'NexGen Energy',
    'Fission Uranium',
    'Sprott Physical Uranium',
    'Yellow Cake uranium',
    'Deep Isolation waste',
    'Orano nuclear',
    'GE Vernova nuclear',
    'Rolls-Royce SMR',
    'Ultra Safe Nuclear',
    'Moltex Energy',
    'Seaborg Technologies',
    'ThorCon Power',
    'ARC Clean Technology',
    'Commonwealth Fusion',
    'Helion Energy fusion',
    'TAE Technologies fusion',
    'General Fusion',
    'Zap Energy fusion',
    'Type One Energy fusion',
  ],
  contexts: [
    'NRC license application',
    'design certification',
    'site permit',
    'construction permit',
    'first criticality',
    'commercial operation date',
    'fuel loading',
    'refueling outage',
    'life extension',
    'decommissioning',
    'SMR deployment',
    'microreactor',
    'fusion milestone',
    'plasma achievement',
    'net energy gain',
    'tritium production',
    'uranium enrichment',
    'fuel fabrication',
    'waste disposal',
    'repository development',
    'regulatory review',
    'safety analysis',
    'environmental impact',
    'community engagement',
    'workforce training',
  ],
};

// ---------------------------------------------------------------------------
// ENERGY_EV_MEGA — 61 entities × 20 contexts = 1,220 sources
// ---------------------------------------------------------------------------
const ENERGY_EV_MEGA: TopicMatrix = {
  prefix: 'ev',
  category: 'Energy',
  tier: 3,
  region: 'global',
  entities: [
    'Tesla Motors',
    'BYD Auto',
    'Rivian',
    'Lucid Motors',
    'NIO electric',
    'XPeng Motors',
    'Li Auto',
    'Fisker Inc',
    'VinFast',
    'Polestar',
    'Volvo Electric',
    'BMW electric',
    'Mercedes EQ',
    'Audi e-tron',
    'Porsche Taycan',
    'Hyundai Ioniq',
    'Kia EV',
    'Genesis electric',
    'Toyota bZ',
    'Honda Prologue',
    'Nissan Ariya',
    'Subaru Solterra',
    'Chevrolet Equinox EV',
    'Ford electric',
    'GM Ultium',
    'Stellantis electric',
    'Volkswagen ID',
    'Renault electric',
    'Geely Auto',
    'Great Wall Motors',
    'ChargePoint',
    'EVgo',
    'Blink Charging',
    'Electrify America',
    'Tesla Supercharger',
    'IONITY Europe',
    'Shell Recharge',
    'BP Pulse',
    'Enel X Way',
    'Wallbox charger',
    'Tritium charger',
    'ABB E-mobility',
    'Siemens eMobility',
    'Delta Electronics EV',
    'Schneider EV',
    'Kempower charger',
    'FreeWire Technologies',
    'EV Connect',
    'Noodoe EV',
    'Ampol charging',
    'Gridserve EV',
    'Proterra electric bus',
    'BYD electric bus',
    'NFI electric bus',
    'Lion Electric',
    'Lightning eMotors',
    'Xos Trucks',
    'Daimler eTruck',
    'Volvo electric truck',
    'PACCAR electric',
    'Arrival electric van',
  ],
  contexts: [
    'vehicle launch',
    'sales report',
    'production milestone',
    'battery technology',
    'range improvement',
    'charging speed',
    'infrastructure expansion',
    'government incentive',
    'fleet electrification',
    'autonomous driving',
    'vehicle recall',
    'pricing strategy',
    'market share',
    'supply chain',
    'labor union',
    'factory construction',
    'earnings report',
    'partnership deal',
    'regulatory standard',
    'consumer adoption',
  ],
};

// ---------------------------------------------------------------------------
// ENERGY_GRID_MEGA — 51 entities × 20 contexts = 1,020 sources
// ---------------------------------------------------------------------------
const ENERGY_GRID_MEGA: TopicMatrix = {
  prefix: 'grid',
  category: 'Energy',
  tier: 4,
  region: 'national',
  entities: [
    'ERCOT Texas grid',
    'PJM Interconnection',
    'MISO energy',
    'CAISO California',
    'NYISO New York',
    'ISO New England',
    'SPP Southwest Power Pool',
    'WECC Western',
    'SERC Reliability',
    'NRC Nuclear Regulatory',
    'FERC regulation',
    'DOE Department Energy',
    'ARPA-E research',
    'national laboratory energy',
    'Pacific Northwest Lab',
    'Argonne National Lab',
    'Oak Ridge National Lab',
    'National Renewable Energy Lab',
    'Sandia energy research',
    'Idaho National Lab',
    'smart grid technology',
    'advanced metering infrastructure',
    'demand response program',
    'virtual power plant',
    'distributed energy resource',
    'microgrid technology',
    'energy storage grid',
    'vehicle to grid V2G',
    'building electrification',
    'heat pump technology',
    'geothermal energy',
    'tidal wave energy',
    'biomass energy',
    'biogas renewable',
    'sustainable aviation fuel',
    'green ammonia shipping',
    'carbon capture storage',
    'direct air capture',
    'enhanced geothermal',
    'community choice aggregation',
    'rooftop solar program',
    'net metering policy',
    'interconnection queue',
    'transmission line construction',
    'HVDC transmission',
    'grid-scale battery',
    'pumped hydro storage',
    'compressed air storage',
    'flywheel energy storage',
    'thermal energy storage',
    'long duration energy storage',
  ],
  contexts: [
    'rate case filing',
    'infrastructure investment',
    'reliability standard',
    'blackout prevention',
    'storm response',
    'wildfire mitigation',
    'grid modernization',
    'interconnection reform',
    'transmission planning',
    'generation retirement',
    'capacity auction',
    'energy price',
    'wholesale market',
    'retail market',
    'regulatory decision',
    'policy proposal',
    'incentive program',
    'pilot project',
    'technology demonstration',
    'research funding',
  ],
};

// ---------------------------------------------------------------------------
// ENERGY_EL_PASO_MEGA — El Paso / West Texas energy ecosystem
// 30 entities × 20 contexts = 600 sources
// ---------------------------------------------------------------------------
const ENERGY_EL_PASO_MEGA: TopicMatrix = {
  prefix: 'ep-energy',
  category: 'Energy',
  tier: 2,
  region: 'el-paso',
  entities: [
    'El Paso Electric',
    'El Paso Electric capex',
    'El Paso Electric rate case',
    'El Paso Natural Gas',
    'Western Refining El Paso',
    'NextEra West Texas',
    'Sempra El Paso',
    'SunPower El Paso',
    'Tesla solar El Paso',
    'EP Energy',
    'Permian Basin El Paso',
    'West Texas solar farm',
    'West Texas wind farm',
    'ERCOT West Texas',
    'El Paso solar installation',
    'El Paso battery storage',
    'El Paso microgrid',
    'El Paso EV charging',
    'El Paso Water Utilities energy',
    'UTEP energy research',
    'Texas Tech energy El Paso',
    'Fort Bliss energy resilience',
    'Fort Bliss microgrid',
    'Fort Bliss solar',
    'El Paso green hydrogen',
    'Juarez power grid',
    'Mexico CFE El Paso',
    'US Mexico energy trade',
    'Texas New Mexico border energy',
    'El Paso climate plan',
  ],
  contexts: [
    'rate case filing',
    'capital expenditure',
    'solar deployment',
    'wind capacity',
    'battery storage',
    'grid reliability',
    'renewable energy',
    'project announcement',
    'regulatory approval',
    'community benefit',
    'workforce development',
    'contract award',
    'research funding',
    'technology pilot',
    'efficiency program',
    'carbon reduction',
    'federal grant',
    'DOE funding',
    'partnership agreement',
    'construction milestone',
  ],
};

// ---------------------------------------------------------------------------
// ENERGY_TEXAS_MEGA — Texas-wide energy policy & market
// 35 entities × 20 contexts = 700 sources
// ---------------------------------------------------------------------------
const ENERGY_TEXAS_MEGA: TopicMatrix = {
  prefix: 'tx-energy',
  category: 'Energy',
  tier: 2,
  region: 'texas',
  entities: [
    'Texas energy grid',
    'Texas electricity market',
    'Texas renewable energy',
    'Texas wind energy',
    'Texas solar energy',
    'Texas battery storage',
    'Texas natural gas',
    'Texas LNG export',
    'Texas oil production',
    'Texas refinery',
    'Texas pipeline',
    'Texas ERCOT',
    'Texas PUC utility commission',
    'Texas Railroad Commission',
    'Texas Legislature energy',
    'Texas Governor energy',
    'Texas energy poverty',
    'Texas grid resilience',
    'Texas winter storm energy',
    'Texas hydrogen hub',
    'Texas carbon capture',
    'Texas geothermal',
    'Texas biomass',
    'Texas offshore wind',
    'Texas nuclear energy',
    'Permian Basin production',
    'Eagle Ford Shale',
    'Barnett Shale',
    'Haynesville Shale',
    'Gulf Coast energy',
    'Houston Ship Channel energy',
    'Corpus Christi LNG Texas',
    'Freeport LNG Texas',
    'Sabine Pass LNG Texas',
    'Texas clean energy jobs',
  ],
  contexts: [
    'capacity expansion',
    'market reform',
    'legislative session',
    'regulatory ruling',
    'investment announcement',
    'production record',
    'export milestone',
    'price volatility',
    'grid emergency',
    'weather event',
    'permit approval',
    'environmental review',
    'federal funding',
    'state incentive',
    'workforce training',
    'technology innovation',
    'economic impact',
    'supply chain',
    'contract award',
    'quarterly report',
  ],
};

// ---------------------------------------------------------------------------
// ENERGY_POLICY_MEGA — US energy policy, DOE programs, federal incentives
// 40 entities × 15 contexts = 600 sources
// ---------------------------------------------------------------------------
const ENERGY_POLICY_MEGA: TopicMatrix = {
  prefix: 'policy',
  category: 'Energy',
  tier: 4,
  region: 'national',
  entities: [
    'DOE loan program',
    'DOE hydrogen hub',
    'DOE grid modernization',
    'DOE critical materials',
    'DOE nuclear energy',
    'DOE fossil energy',
    'DOE Office of Science',
    'ARPA-E award',
    'Inflation Reduction Act energy',
    'Infrastructure Investment Jobs Act energy',
    'Investment Tax Credit solar',
    'Production Tax Credit wind',
    'Advanced Manufacturing Tax Credit',
    'Clean Vehicle Tax Credit',
    'Hydrogen Tax Credit',
    'Carbon Capture Tax Credit',
    'Nuclear Tax Credit',
    'EPA Clean Power Plan',
    'EPA methane rule',
    'EPA air quality energy',
    'FERC Order 2023',
    'FERC transmission policy',
    'FERC storage rule',
    'FERC demand response',
    'BLM solar lease',
    'BLM wind lease',
    'offshore wind lease BOEM',
    'national energy strategy',
    'clean energy standard',
    'renewable portfolio standard',
    'carbon border adjustment',
    'clean electricity standard',
    'energy efficiency standard',
    'appliance efficiency rule',
    'building energy code',
    'EV charging standard',
    'hydrogen safety standard',
    'nuclear waste policy',
    'strategic petroleum reserve',
    'critical mineral supply chain',
  ],
  contexts: [
    'rulemaking proposed',
    'final rule published',
    'funding announcement',
    'grant award',
    'loan guarantee',
    'congressional hearing',
    'executive order',
    'agency guidance',
    'comment period',
    'court challenge',
    'industry response',
    'state implementation',
    'international agreement',
    'budget proposal',
    'program evaluation',
  ],
};

// ---------------------------------------------------------------------------
// ENERGY_MINING_MEGA — Critical minerals, lithium, rare earths
// 35 entities × 20 contexts = 700 sources
// ---------------------------------------------------------------------------
const ENERGY_MINING_MEGA: TopicMatrix = {
  prefix: 'mining',
  category: 'Energy',
  tier: 3,
  region: 'global',
  entities: [
    'Albemarle lithium',
    'Livent lithium',
    'Allkem lithium',
    'Sociedad Quimica lithium',
    'Ganfeng Lithium',
    'Tianqi Lithium',
    'Pilbara Minerals',
    'Core Lithium',
    'Liontown Resources',
    'Patriot Battery Metals',
    'Standard Lithium',
    'Lithium Americas',
    'ioneer lithium',
    'Piedmont Lithium',
    'Cypress Development',
    'MP Materials rare earth',
    'Energy Fuels rare earth',
    'Lynas Rare Earths',
    'Vital Metals',
    'Arafura Rare Earths',
    'Medallion Financial rare earth',
    'Torchlight Energy cobalt',
    'Jervois cobalt',
    'Glencore cobalt',
    'Freeport-McMoRan copper',
    'Southern Copper',
    'BHP copper',
    'Rio Tinto copper',
    'Antofagasta copper',
    'First Quantum copper',
    'Vale nickel',
    'Norilsk Nickel',
    'Wyloo Metals nickel',
    'Australian Strategic Materials',
    'NioCorp Developments niobium',
  ],
  contexts: [
    'mine development',
    'production update',
    'resource estimate',
    'feasibility study',
    'environmental permit',
    'community agreement',
    'offtake agreement',
    'financing secured',
    'IPO listing',
    'acquisition deal',
    'processing plant',
    'refinery construction',
    'battery material supply',
    'DOE critical mineral',
    'supply chain security',
    'recycling program',
    'exploration drill result',
    'quarterly earnings',
    'government partnership',
    'technology innovation',
  ],
};

// ---------------------------------------------------------------------------
// ENERGY_CLEANTECH_MEGA — Emerging cleantech, startups, VC-funded
// 40 entities × 20 contexts = 800 sources
// ---------------------------------------------------------------------------
const ENERGY_CLEANTECH_MEGA: TopicMatrix = {
  prefix: 'cleantech',
  category: 'Energy',
  tier: 3,
  region: 'global',
  entities: [
    'Redwood Materials battery recycling',
    'Li-Cycle battery recycling',
    'Battery Resources recycling',
    'Ascend Elements recycling',
    'Retriev Technologies recycling',
    'Northvolt battery',
    'Factorial Energy battery',
    'Sila Nanotechnologies',
    'Group14 Technologies',
    'Enovix Corporation',
    'Amprius Technologies',
    'SES AI battery',
    'Lyten battery',
    'Our Next Energy',
    'Natron Energy',
    'C4V battery',
    'Moxion Power mobile storage',
    'Aggreko portable power',
    'Briggs Stratton generator',
    'Generac Holdings',
    'Kohler power',
    'Cummins generator',
    'Caterpillar power',
    'Atlas Copco power',
    'Aggreko energy services',
    'Ameresco energy services',
    'Willdan Group energy',
    'Eaton electrical',
    'Vertiv power',
    'Legrand electrical',
    'nVent Electric',
    'Roper Technologies energy',
    'Watts Water energy',
    'Xylem water energy',
    'Evoqua water energy',
    'Veolia energy services',
    'SUEZ energy services',
    'Enviva biomass',
    'Drax Group biomass',
    'Pacific Bioenergy',
  ],
  contexts: [
    'Series A funding',
    'Series B funding',
    'Series C funding',
    'IPO announcement',
    'SPAC merger',
    'DOE grant award',
    'pilot project launch',
    'commercial scale up',
    'technology demonstration',
    'partnership agreement',
    'customer deployment',
    'manufacturing facility',
    'patent granted',
    'record performance',
    'cost reduction',
    'product launch',
    'market expansion',
    'acquisition target',
    'revenue milestone',
    'industry award',
  ],
};

// ---------------------------------------------------------------------------
// Export all matrices combined
// ---------------------------------------------------------------------------
export const ENERGY_MEGA_SOURCES: FeedSourceEntry[] = [
  ...expandMatrix(ENERGY_OIL_GAS_MEGA),
  ...expandMatrix(ENERGY_RENEWABLES_MEGA),
  ...expandMatrix(ENERGY_NUCLEAR_MEGA),
  ...expandMatrix(ENERGY_EV_MEGA),
  ...expandMatrix(ENERGY_GRID_MEGA),
  ...expandMatrix(ENERGY_EL_PASO_MEGA),
  ...expandMatrix(ENERGY_TEXAS_MEGA),
  ...expandMatrix(ENERGY_POLICY_MEGA),
  ...expandMatrix(ENERGY_MINING_MEGA),
  ...expandMatrix(ENERGY_CLEANTECH_MEGA),
];
