// src/lib/feeds/mega/enterprise-sources.ts
import type { FeedCategory } from '@/lib/agents/feed-agent';

type TopicMatrix = {
  prefix: string;
  category: FeedCategory;
  tier: 1 | 2 | 3 | 4;
  region?: 'el-paso' | 'texas' | 'national' | 'global';
  entities: string[];
  contexts: string[];
};

const GN = (q: string) =>
  `https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=en-US&gl=US&ceid=US:en`;

type FeedSourceEntry = {
  id: string;
  name: string;
  url: string;
  category: FeedCategory;
  tags: string[];
  tier: 1 | 2 | 3 | 4;
  region?: 'el-paso' | 'texas' | 'national' | 'global';
};

function expandMatrix(m: TopicMatrix): FeedSourceEntry[] {
  const results: FeedSourceEntry[] = [];
  for (const entity of m.entities) {
    for (const context of m.contexts) {
      const slug = `${entity} ${context}`.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40);
      const id = `${m.prefix}-${slug}`;
      const query = `${entity} ${context}`;
      results.push({
        id,
        name: `GN: ${entity.slice(0, 18)} ${context.slice(0, 10)}`,
        url: GN(query),
        category: m.category,
        tags: query.toLowerCase().split(/\s+/).filter(w => w.length > 2),
        tier: m.tier,
        region: m.region ?? 'national',
      });
    }
  }
  return results;
}

// ---------------------------------------------------------------------------
// ENTERPRISE_SAAS_MEGA
// 100 entities × 20 contexts = 2,000 entries
// ---------------------------------------------------------------------------
const ENTERPRISE_SAAS_MEGA: TopicMatrix = {
  prefix: 'saas',
  category: 'Enterprise',
  tier: 3,
  region: 'global',
  entities: [
    'Salesforce',
    'ServiceNow',
    'Workday',
    'SAP',
    'Oracle Cloud',
    'Snowflake',
    'Datadog',
    'Splunk',
    'MongoDB',
    'Confluent',
    'HashiCorp',
    'Elastic',
    'Twilio',
    'Atlassian',
    'HubSpot',
    'Zendesk',
    'Okta',
    'DocuSign',
    'Zoom Video',
    'Slack',
    'Notion',
    'Airtable',
    'Monday.com',
    'Asana',
    'Figma',
    'Vercel',
    'Netlify',
    'Supabase',
    'PlanetScale',
    'Neon Database',
    'Retool',
    'Appsmith',
    'UiPath',
    'Automation Anywhere',
    'Pegasystems',
    'Appian',
    'Coupa Software',
    'Verint Systems',
    'NICE Systems',
    'Five9',
    'RingCentral',
    'Genesys',
    'Freshworks',
    'Zoho',
    'Pipedrive',
    'Copper CRM',
    'Braze',
    'Klaviyo',
    'Iterable',
    'Customer.io',
    'Amplitude',
    'Mixpanel',
    'Heap Analytics',
    'PostHog',
    'Segment Twilio',
    'mParticle',
    'Rudderstack',
    'Fivetran',
    'Airbyte',
    'dbt Labs',
    'Stitch Data',
    'Matillion',
    'Informatica Cloud',
    'Talend',
    'MuleSoft',
    'Boomi',
    'Workato',
    'Tray.io',
    'Celigo',
    'SnapLogic',
    'Jitterbit',
    'Kong API',
    'Postman API',
    'Apigee Google',
    'AWS API Gateway',
    'Stripe Payments',
    'Adyen',
    'Braintree',
    'Square Block',
    'Shopify',
    'BigCommerce',
    'Magento Adobe',
    'WooCommerce',
    'Contentful',
    'Sanity CMS',
    'Strapi',
    'Prismic',
    'Sitecore',
    'Adobe Experience',
    'Optimizely',
    'LaunchDarkly',
    'Split.io',
    'Harness',
    'CircleCI',
    'GitHub Actions',
    'GitLab CI',
    'Jenkins',
    'Argo CD',
    'Flux CD',
    'Terraform Cloud',
    'Pulumi',
    'Crossplane',
    'Backstage Spotify',
    'Port DevPortal',
    'Cortex Internal',
    'OpsLevel',
  ],
  contexts: [
    'product launch',
    'quarterly earnings',
    'enterprise deal',
    'acquisition merger',
    'API update',
    'pricing change',
    'integration announcement',
    'developer conference',
    'customer expansion',
    'market analysis',
    'competitive positioning',
    'funding round',
    'IPO preparation',
    'layoff restructuring',
    'hiring expansion',
    'partnership deal',
    'government contract',
    'security incident',
    'compliance certification',
    'platform migration',
  ],
};

// ---------------------------------------------------------------------------
// ENTERPRISE_CLOUD_MEGA
// 50 entities × 25 contexts = 1,250 entries
// ---------------------------------------------------------------------------
const ENTERPRISE_CLOUD_MEGA: TopicMatrix = {
  prefix: 'cloud',
  category: 'Enterprise',
  tier: 3,
  region: 'global',
  entities: [
    'AWS Amazon Web Services',
    'Microsoft Azure',
    'Google Cloud Platform',
    'Oracle Cloud Infrastructure',
    'IBM Cloud',
    'Alibaba Cloud',
    'Tencent Cloud',
    'DigitalOcean',
    'Linode Akamai',
    'Vultr cloud',
    'Hetzner Cloud',
    'OVHcloud',
    'Scaleway',
    'Equinix colocation',
    'CoreSite datacenter',
    'CyrusOne',
    'QTS Realty',
    'Digital Realty',
    'Rackspace Technology',
    'Cloudflare Workers',
    'Fastly Compute',
    'Deno Deploy',
    'Fly.io',
    'Railway cloud',
    'Render platform',
    'AWS Lambda serverless',
    'Azure Functions',
    'Google Cloud Run',
    'Kubernetes managed',
    'Amazon EKS',
    'Azure AKS',
    'Google GKE',
    'Red Hat OpenShift',
    'Rancher SUSE',
    'VMware Tanzu',
    'Docker containers',
    'Podman containers',
    'Istio service mesh',
    'Linkerd mesh',
    'Cilium eBPF',
    'Envoy proxy',
    'Traefik proxy',
    'Nginx ingress',
    'Apache Kafka',
    'RabbitMQ',
    'Redis cloud',
    'Memcached',
    'CockroachDB',
    'TiDB distributed',
    'YugabyteDB',
    'Vitess MySQL',
  ],
  contexts: [
    'service launch',
    'pricing reduction',
    'region expansion',
    'outage incident',
    'security patch',
    'compliance certification',
    'partnership deal',
    'migration tool',
    'benchmark result',
    'cost optimization',
    'reserved capacity',
    'spot pricing',
    'sustainability initiative',
    'carbon footprint',
    'renewable energy',
    'data sovereignty',
    'multi-cloud strategy',
    'hybrid cloud',
    'edge computing',
    'serverless adoption',
    'container adoption',
    'microservices architecture',
    'infrastructure as code',
    'GitOps deployment',
    'observability platform',
  ],
};

// ---------------------------------------------------------------------------
// ENTERPRISE_DATA_MEGA
// 60 entities × 20 contexts = 1,200 entries
// ---------------------------------------------------------------------------
const ENTERPRISE_DATA_MEGA: TopicMatrix = {
  prefix: 'data',
  category: 'Enterprise',
  tier: 4,
  region: 'global',
  entities: [
    'Snowflake data cloud',
    'Databricks lakehouse',
    'BigQuery Google',
    'Redshift AWS',
    'Synapse Azure',
    'Teradata cloud',
    'Vertica OpenText',
    'ClickHouse analytics',
    'DuckDB embedded',
    'Apache Spark',
    'Apache Flink',
    'Apache Beam',
    'Trino Presto',
    'Apache Druid',
    'Apache Pinot',
    'StarRocks analytics',
    'Firebolt analytics',
    'Materialize streaming',
    'Rockset real-time',
    'MotherDuck DuckDB',
    'Dremio data lakehouse',
    'Starburst Trino',
    'Tabular Apache Iceberg',
    'Delta Lake Databricks',
    'Apache Hudi',
    'Parquet format',
    'Arrow format',
    'Avro format',
    'dbt data transform',
    'Coalesce data',
    'Matillion ETL',
    'Fivetran ELT',
    'Airbyte open source',
    'Census reverse ETL',
    'Hightouch reverse ETL',
    'Monte Carlo data observability',
    'Atlan data catalog',
    'Alation data catalog',
    'Collibra data governance',
    'Informatica data quality',
    'Great Expectations',
    'Soda data quality',
    'Apache Atlas governance',
    'Unity Catalog Databricks',
    'AWS Glue catalog',
    'Purview Microsoft',
    'DataHub LinkedIn',
    'Amundsen data discovery',
    'OpenMetadata',
    'Datahub observability',
    'Bigeye data monitoring',
    'Anomalo data quality',
    'Lightdash BI',
    'Metabase BI',
    'Apache Superset',
    'Looker Google',
    'Tableau Salesforce',
    'Power BI Microsoft',
    'Qlik analytics',
    'ThoughtSpot search',
  ],
  contexts: [
    'product release',
    'benchmark comparison',
    'migration guide',
    'cost analysis',
    'performance tuning',
    'architecture pattern',
    'customer case study',
    'data lakehouse trend',
    'real-time analytics',
    'streaming pipeline',
    'data mesh architecture',
    'data fabric strategy',
    'data governance mandate',
    'data quality initiative',
    'MLOps integration',
    'reverse ETL trend',
    'semantic layer',
    'metrics layer',
    'headless BI',
    'embedded analytics',
  ],
};

// ---------------------------------------------------------------------------
// ENTERPRISE_DEVTOOLS_MEGA
// 60 entities × 20 contexts = 1,200 entries
// ---------------------------------------------------------------------------
const ENTERPRISE_DEVTOOLS_MEGA: TopicMatrix = {
  prefix: 'devtools',
  category: 'Enterprise',
  tier: 4,
  region: 'global',
  entities: [
    'GitHub Copilot',
    'Cursor AI editor',
    'Windsurf AI',
    'Tabnine AI',
    'Amazon CodeWhisperer',
    'Google Gemini Code',
    'Sourcegraph Cody',
    'JetBrains AI',
    'Visual Studio IntelliCode',
    'Replit AI',
    'Gitpod workspace',
    'Codespaces GitHub',
    'StackBlitz web IDE',
    'CodeSandbox',
    'Snyk security',
    'Sonar code quality',
    'Semgrep SAST',
    'Checkmarx security',
    'Veracode security',
    'Black Duck SCA',
    'Jfrog Artifactory',
    'Nexus Sonatype',
    'Docker Hub',
    'GitHub Container Registry',
    'AWS ECR',
    'Harbor registry',
    'Grafana observability',
    'Prometheus monitoring',
    'New Relic observability',
    'Dynatrace monitoring',
    'AppDynamics Cisco',
    'Lightstep ServiceNow',
    'Honeycomb observability',
    'Chronosphere monitoring',
    'VictoriaMetrics',
    'Thanos Prometheus',
    'Mimir Grafana',
    'Loki logging',
    'Fluentd logging',
    'Vector logging',
    'OpenTelemetry standard',
    'Jaeger tracing',
    'Zipkin tracing',
    'Sentry error tracking',
    'Bugsnag errors',
    'Rollbar errors',
    'PagerDuty incident',
    'Opsgenie Atlassian',
    'Incident.io',
    'FireHydrant incident',
    'Blameless SRE',
    'Gremlin chaos',
    'LitmusChaos',
    'Steadybit',
    'LaunchDarkly feature',
    'Split.io feature',
    'Flagsmith feature',
    'Unleash feature',
    'ConfigCat',
    'Optimizely experiment',
  ],
  contexts: [
    'product update',
    'developer adoption',
    'enterprise deployment',
    'pricing model',
    'open source contribution',
    'community growth',
    'integration ecosystem',
    'competitive analysis',
    'developer experience',
    'productivity study',
    'security enhancement',
    'compliance feature',
    'AI coding impact',
    'code review automation',
    'CI CD improvement',
    'testing automation',
    'deployment frequency',
    'incident reduction',
    'mean time recovery',
    'platform engineering',
  ],
};

// ---------------------------------------------------------------------------
// ENTERPRISE_VERTICAL_MEGA
// 60 entities × 20 contexts = 1,200 entries
// ---------------------------------------------------------------------------
const ENTERPRISE_VERTICAL_MEGA: TopicMatrix = {
  prefix: 'vertical',
  category: 'Enterprise',
  tier: 4,
  region: 'global',
  entities: [
    'Veeva Systems pharma',
    'Epic Systems healthcare',
    'Cerner Oracle health',
    'Procore construction',
    'Autodesk BIM',
    'Bentley Systems infrastructure',
    'PTC CAD PLM',
    'Siemens Teamcenter',
    'Dassault 3DEXPERIENCE',
    'ANSYS simulation',
    'MathWorks MATLAB',
    'Rockwell Automation',
    'Siemens Digital Industries',
    'ABB Ability',
    'Honeywell Forge',
    'Emerson DeltaV',
    'Yokogawa OpreX',
    'Schneider EcoStruxure',
    'GE Vernova digital',
    'OSIsoft PI System',
    'Infor CloudSuite',
    'Tyler Technologies government',
    'Palantir Foundry',
    'Esri ArcGIS',
    'Trimble geospatial',
    'Hexagon geospatial',
    'Descartes logistics',
    'Manhattan Associates',
    'Blue Yonder supply chain',
    'Kinaxis supply chain',
    'o9 Solutions planning',
    'Coupa procurement',
    'Jaggaer procurement',
    'SAP Ariba',
    'GEP procurement',
    'Ivalua procurement',
    'Anaplan planning',
    'Vena Solutions',
    'Pigment planning',
    'Jedox planning',
    'Board International',
    'Planful FP&A',
    'Workiva reporting',
    'BlackLine accounting',
    'FloQast accounting',
    'Trintech reconciliation',
    'Costar real estate',
    'Yardi property',
    'RealPage multifamily',
    'MRI Software',
    'Buildium property',
    'AppFolio property',
    'Toast restaurant',
    'Lightspeed POS',
    'NCR Voyix',
    'Oracle MICROS',
    'Agilysys hospitality',
    'Cloudbeds hotel',
    'Mews hotel',
    'Guesty vacation rental',
  ],
  contexts: [
    'product launch',
    'vertical expansion',
    'customer win',
    'regulatory compliance',
    'partnership announcement',
    'acquisition deal',
    'integration update',
    'market leadership',
    'customer conference',
    'industry award',
    'digital transformation',
    'cloud migration',
    'AI feature launch',
    'mobile platform',
    'data analytics',
    'operational efficiency',
    'cost reduction',
    'user experience',
    'implementation success',
    'competitive displacement',
  ],
};

// ---------------------------------------------------------------------------
// Final export — all matrices expanded
// ENTERPRISE_SAAS_MEGA:    104 × 20 = 2,080
// ENTERPRISE_CLOUD_MEGA:    51 × 25 = 1,275
// ENTERPRISE_DATA_MEGA:     60 × 20 = 1,200
// ENTERPRISE_DEVTOOLS_MEGA: 60 × 20 = 1,200
// ENTERPRISE_VERTICAL_MEGA: 60 × 20 = 1,200
// TOTAL:                              6,955 (all unique entity×context combinations)
// With deduplication guards removed each combination is unique — total >= 6,955
// ---------------------------------------------------------------------------
export const ENTERPRISE_MEGA_SOURCES: FeedSourceEntry[] = [
  ...expandMatrix(ENTERPRISE_SAAS_MEGA),
  ...expandMatrix(ENTERPRISE_CLOUD_MEGA),
  ...expandMatrix(ENTERPRISE_DATA_MEGA),
  ...expandMatrix(ENTERPRISE_DEVTOOLS_MEGA),
  ...expandMatrix(ENTERPRISE_VERTICAL_MEGA),
];
