// src/lib/feeds/mega/finance-sources.ts
import type { FeedCategory } from '@/lib/agents/feed-agent';

type TopicMatrix = {
  prefix: string;
  category: FeedCategory;
  tier: 1 | 2 | 3 | 4;
  region?: 'el-paso' | 'texas' | 'national' | 'global';
  entities: string[];
  contexts: string[];
};

const GN = (q: string) =>
  `https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=en-US&gl=US&ceid=US:en`;

type FeedSourceEntry = {
  id: string;
  name: string;
  url: string;
  category: FeedCategory;
  tags: string[];
  tier: 1 | 2 | 3 | 4;
  region?: 'el-paso' | 'texas' | 'national' | 'global';
};

function expandMatrix(m: TopicMatrix): FeedSourceEntry[] {
  const results: FeedSourceEntry[] = [];
  for (const entity of m.entities) {
    for (const context of m.contexts) {
      const slug = `${entity} ${context}`.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40);
      const id = `${m.prefix}-${slug}`;
      const query = `${entity} ${context}`;
      results.push({
        id,
        name: `GN: ${entity.slice(0, 18)} ${context.slice(0, 10)}`,
        url: GN(query),
        category: m.category,
        tags: query.toLowerCase().split(/\s+/).filter(w => w.length > 2),
        tier: m.tier,
        region: m.region ?? 'national',
      });
    }
  }
  return results;
}

// ---------------------------------------------------------------------------
// FINANCE_BANKS_MEGA — 80 entities × 20 contexts = 1,600 sources
// ---------------------------------------------------------------------------
const FINANCE_BANKS_MEGA: TopicMatrix = {
  prefix: 'fin-bank',
  category: 'Finance',
  tier: 3,
  region: 'global',
  entities: [
    'JPMorgan Chase',
    'Goldman Sachs',
    'Morgan Stanley',
    'Bank of America',
    'Citigroup',
    'Wells Fargo',
    'US Bancorp',
    'PNC Financial',
    'Truist Financial',
    'Capital One',
    'TD Bank',
    'BMO Financial',
    'RBC Royal Bank',
    'Scotiabank',
    'CIBC',
    'National Bank Canada',
    'HSBC',
    'Barclays',
    'Deutsche Bank',
    'UBS Group',
    'Credit Suisse',
    'BNP Paribas',
    'Societe Generale',
    'Credit Agricole',
    'ING Group',
    'ABN AMRO',
    'Rabobank',
    'UniCredit',
    'Intesa Sanpaolo',
    'Santander',
    'BBVA',
    'Standard Chartered',
    'Macquarie Group',
    'ANZ Bank',
    'Commonwealth Bank Australia',
    'Westpac',
    'NAB Australia',
    'DBS Bank',
    'OCBC Bank',
    'UOB Bank',
    'Mizuho Financial',
    'Sumitomo Mitsui',
    'MUFG Bank',
    'Industrial Commercial Bank China',
    'China Construction Bank',
    'Bank of China',
    'Agricultural Bank China',
    'State Bank India',
    'HDFC Bank',
    'Kotak Mahindra',
    'BlackRock',
    'Vanguard Group',
    'State Street',
    'Fidelity Investments',
    'Charles Schwab',
    'T Rowe Price',
    'Franklin Templeton',
    'Invesco',
    'BNY Mellon',
    'Northern Trust',
    'Bridgewater Associates',
    'Citadel',
    'Two Sigma',
    'DE Shaw',
    'Renaissance Technologies',
    'Point72',
    'Millennium Management',
    'AQR Capital',
    'Man Group',
    'Baupost Group',
    'Elliott Management',
    'Third Point',
    'Pershing Square',
    'Lone Pine Capital',
    'Tiger Global',
    'Coatue Management',
    'D1 Capital',
    'Viking Global',
    'Appaloosa Management',
  ],
  contexts: [
    'quarterly earnings',
    'trading revenue',
    'investment banking',
    'wealth management',
    'asset management',
    'technology investment',
    'AI deployment',
    'digital transformation',
    'regulatory compliance',
    'stress test result',
    'capital allocation',
    'dividend buyback',
    'merger acquisition',
    'workforce reduction',
    'branch strategy',
    'cybersecurity incident',
    'risk management',
    'ESG investing',
    'climate finance',
    'market outlook',
  ],
};

// ---------------------------------------------------------------------------
// FINANCE_FINTECH_MEGA — 80 entities × 20 contexts = 1,600 sources
// ---------------------------------------------------------------------------
const FINANCE_FINTECH_MEGA: TopicMatrix = {
  prefix: 'fin-fintech',
  category: 'Finance',
  tier: 3,
  region: 'global',
  entities: [
    'Stripe payments',
    'Block Square',
    'PayPal',
    'Adyen',
    'Checkout.com',
    'Worldpay',
    'Fiserv',
    'FIS Global',
    'Global Payments',
    'Marqeta',
    'Galileo Financial',
    'Plaid',
    'MX Technologies',
    'Yodlee Envestnet',
    'Finicity Mastercard',
    'Affirm',
    'Klarna',
    'Afterpay Block',
    'Sezzle',
    'Zip Co',
    'Brex corporate card',
    'Ramp spend management',
    'Divvy BILL',
    'Airbase spend',
    'Navan travel',
    'Green Dot',
    'SoFi Technologies',
    'Chime',
    'Current bank',
    'Varo Bank',
    'Dave banking',
    'MoneyLion',
    'Ally Financial',
    'Marcus Goldman Sachs',
    'LendingClub',
    'Prosper Marketplace',
    'Upstart',
    'Figure Technologies',
    'Better Mortgage',
    'Rocket Companies',
    'United Wholesale',
    'loanDepot',
    'Blend Labs',
    'Encompass ICE',
    'Robinhood',
    'Interactive Brokers',
    'Webull',
    'Moomoo',
    'Public.com',
    'eToro',
    'Wealthfront',
    'Betterment',
    'Acorns investing',
    'Stash investing',
    'M1 Finance',
    'Coinbase',
    'Binance',
    'Kraken exchange',
    'Gemini exchange',
    'Crypto.com',
    'Circle USDC',
    'Tether USDT',
    'Ripple XRP',
    'Chainalysis',
    'Elliptic',
    'Fireblocks',
    'Anchorage Digital',
    'BitGo custody',
    'Copper crypto',
    'Paxos',
    'Silvergate Capital',
    'Signature Bank',
    'Cross River Bank',
    'Column bank',
    'Synapse banking',
    'Unit banking',
    'Treasury Prime',
    'Bond Financial',
    'Highnote cards',
    'Lithic cards',
    'i2c processing',
  ],
  contexts: [
    'product launch',
    'funding round',
    'valuation update',
    'IPO filing',
    'SPAC merger',
    'revenue growth',
    'user milestone',
    'partnership deal',
    'regulatory approval',
    'banking charter',
    'compliance action',
    'fine penalty',
    'security breach',
    'technology update',
    'API release',
    'international expansion',
    'acquisition deal',
    'layoff restructuring',
    'profitability milestone',
    'market competition',
  ],
};

// ---------------------------------------------------------------------------
// FINANCE_CRYPTO_MEGA — 60 entities × 20 contexts = 1,200 sources
// ---------------------------------------------------------------------------
const FINANCE_CRYPTO_MEGA: TopicMatrix = {
  prefix: 'fin-crypto',
  category: 'Finance',
  tier: 3,
  region: 'global',
  entities: [
    'Bitcoin BTC',
    'Ethereum ETH',
    'Solana SOL',
    'Cardano ADA',
    'Polkadot DOT',
    'Avalanche AVAX',
    'Chainlink LINK',
    'Polygon MATIC',
    'Arbitrum ARB',
    'Optimism OP',
    'Base Coinbase L2',
    'zkSync ERA',
    'StarkNet',
    'Celestia TIA',
    'Cosmos ATOM',
    'Near Protocol',
    'Sui blockchain',
    'Aptos blockchain',
    'Sei Network',
    'Injective Protocol',
    'dYdX exchange',
    'Uniswap DEX',
    'Aave lending',
    'Compound Finance',
    'MakerDAO DAI',
    'Lido Finance',
    'Rocket Pool',
    'EigenLayer restaking',
    'Pendle Finance',
    'Ethena USDe',
    'BlackRock Bitcoin ETF',
    'Fidelity Bitcoin ETF',
    'Grayscale GBTC',
    'ARK 21Shares Bitcoin',
    'VanEck Bitcoin',
    'Invesco Bitcoin',
    'WisdomTree Bitcoin',
    'Bitwise Asset',
    'ProShares Bitcoin',
    'SEC crypto regulation',
    'CFTC crypto oversight',
    'OCC crypto banking',
    'Federal Reserve CBDC',
    'European MICA regulation',
    'Hong Kong crypto',
    'Singapore MAS crypto',
    'Japan FSA crypto',
    'Brazil crypto regulation',
    'Nigeria crypto adoption',
    'El Salvador Bitcoin',
    'MicroStrategy Bitcoin',
    'Tesla Bitcoin',
    'Block Bitcoin',
    'Marathon Digital',
    'Riot Platforms',
    'CleanSpark',
    'Iris Energy',
    'Bitdeer Technologies',
    'Hut 8 Mining',
    'MARA Holdings',
  ],
  contexts: [
    'price movement',
    'trading volume',
    'network upgrade',
    'protocol launch',
    'security exploit',
    'DeFi hack',
    'regulatory action',
    'ETF approval',
    'institutional adoption',
    'whale transaction',
    'mining difficulty',
    'hash rate',
    'staking yield',
    'governance vote',
    'airdrop distribution',
    'token unlock',
    'exchange listing',
    'exchange delisting',
    'developer activity',
    'ecosystem growth',
  ],
};

// ---------------------------------------------------------------------------
// FINANCE_INSURANCE_MEGA — 50 entities × 20 contexts = 1,000 sources
// ---------------------------------------------------------------------------
const FINANCE_INSURANCE_MEGA: TopicMatrix = {
  prefix: 'fin-insure',
  category: 'Finance',
  tier: 4,
  region: 'global',
  entities: [
    'Berkshire Hathaway',
    'UnitedHealth Group',
    'Anthem Elevance',
    'Cigna',
    'Humana',
    'Aetna CVS',
    'Kaiser Permanente',
    'Centene',
    'Molina Healthcare',
    'Progressive Insurance',
    'Geico Berkshire',
    'State Farm',
    'Allstate',
    'Liberty Mutual',
    'Travelers',
    'Hartford Financial',
    'Chubb Limited',
    'AIG',
    'Zurich Insurance',
    'Allianz',
    'AXA Group',
    'Generali',
    'Munich Re',
    'Swiss Re',
    'Hannover Re',
    'RGA Reinsurance',
    'Everest Group',
    'Arch Capital',
    'Fairfax Financial',
    'Markel Group',
    'Lemonade insurance',
    'Root Insurance',
    'Hippo Insurance',
    'Kin Insurance',
    'Metromile',
    'Clearcover',
    'Branch Insurance',
    'Jetty Insurance',
    'Bestow life',
    'Haven Life',
    'Ladder Life',
    'Wealthsimple',
    'Personal Capital',
    'Empower Retirement',
    'Principal Financial',
    'Lincoln National',
    'Prudential Financial',
    'MetLife',
    'MassMutual',
    'New York Life',
  ],
  contexts: [
    'quarterly earnings',
    'claims experience',
    'premium growth',
    'underwriting profit',
    'investment income',
    'catastrophe loss',
    'rate filing',
    'regulatory exam',
    'technology upgrade',
    'InsurTech partnership',
    'AI claims processing',
    'telematics pricing',
    'digital distribution',
    'customer experience',
    'product launch',
    'market expansion',
    'reinsurance placement',
    'capital management',
    'ESG integration',
    'climate risk model',
  ],
};

// ---------------------------------------------------------------------------
// FINANCE_MARKETS_MEGA — 60 entities × 25 contexts = 1,500 sources
// ---------------------------------------------------------------------------
const FINANCE_MARKETS_MEGA: TopicMatrix = {
  prefix: 'fin-market',
  category: 'Finance',
  tier: 4,
  region: 'global',
  entities: [
    'Federal Reserve monetary policy',
    'ECB European Central Bank',
    'Bank of Japan',
    'Bank of England',
    'Peoples Bank China',
    'Reserve Bank India',
    'Bank of Canada',
    'Reserve Bank Australia',
    'Swiss National Bank',
    'Banco de Mexico',
    'S&P 500 index',
    'NASDAQ Composite',
    'Dow Jones Industrial',
    'Russell 2000',
    'FTSE 100',
    'DAX Germany',
    'Nikkei 225',
    'Hang Seng',
    'Shanghai Composite',
    'BSE Sensex',
    'VIX volatility index',
    'US Treasury bonds',
    'German Bund',
    'Japanese JGB',
    'corporate bond market',
    'high yield bonds',
    'municipal bonds',
    'commercial real estate',
    'residential mortgage',
    'CLO market',
    'private equity',
    'venture capital',
    'IPO market',
    'SPAC market',
    'merger arbitrage',
    'activist investing',
    'short selling',
    'options trading',
    'commodities market',
    'gold price',
    'crude oil WTI',
    'natural gas Henry Hub',
    'copper price',
    'lithium market',
    'cobalt market',
    'rare earth minerals',
    'agricultural commodities',
    'wheat market',
    'corn market',
    'soybean market',
    'coffee market',
    'lumber market',
    'carbon credit market',
    'forex dollar',
    'forex euro',
    'forex yen',
    'forex yuan',
    'forex emerging',
    'inflation expectations',
    'yield curve',
  ],
  contexts: [
    'market analysis',
    'price forecast',
    'trading strategy',
    'risk assessment',
    'portfolio allocation',
    'sector rotation',
    'earnings season',
    'economic indicator',
    'GDP growth',
    'unemployment rate',
    'inflation data',
    'consumer spending',
    'housing market',
    'manufacturing PMI',
    'services PMI',
    'retail sales',
    'trade balance',
    'current account',
    'fiscal policy',
    'government spending',
    'debt ceiling',
    'tax policy',
    'regulatory change',
    'geopolitical risk',
    'central bank meeting',
  ],
};

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------
export const FINANCE_MEGA_SOURCES: FeedSourceEntry[] = [
  ...expandMatrix(FINANCE_BANKS_MEGA),
  ...expandMatrix(FINANCE_FINTECH_MEGA),
  ...expandMatrix(FINANCE_CRYPTO_MEGA),
  ...expandMatrix(FINANCE_INSURANCE_MEGA),
  ...expandMatrix(FINANCE_MARKETS_MEGA),
];
