// src/lib/feeds/mega/fintech-banking-sources.ts
// NXT//LINK Fintech & Banking Mega-Registry
// Matrices × cross-product expansion = ~6,900 unique Google News RSS feeds

import type { FeedCategory } from '@/lib/agents/feed-agent';

type TopicMatrix = {
  prefix: string;
  category: FeedCategory;
  tier: 1 | 2 | 3 | 4;
  region?: 'el-paso' | 'texas' | 'national' | 'global';
  entities: string[];
  contexts: string[];
};

const GN = (q: string) =>
  `https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=en-US&gl=US&ceid=US:en`;

type FeedSourceEntry = {
  id: string;
  name: string;
  url: string;
  category: FeedCategory;
  tags: string[];
  tier: 1 | 2 | 3 | 4;
  region?: 'el-paso' | 'texas' | 'national' | 'global';
};

function expandMatrix(m: TopicMatrix): FeedSourceEntry[] {
  const results: FeedSourceEntry[] = [];
  for (const entity of m.entities) {
    for (const context of m.contexts) {
      const slug = `${entity} ${context}`
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .slice(0, 40);
      const id = `${m.prefix}-${slug}`;
      const query = `${entity} ${context}`;
      results.push({
        id,
        name: `GN: ${entity.slice(0, 18)} ${context.slice(0, 10)}`,
        url: GN(query),
        category: m.category,
        tags: query
          .toLowerCase()
          .split(/\s+/)
          .filter((w) => w.length > 2),
        tier: m.tier,
        region: m.region ?? 'national',
      });
    }
  }
  return results;
}

// ─── MATRIX 1: FINTECH COMPANIES MEGA ─────────────────────────────────────────
// 80 entities × 25 contexts = 2,000 entries
const FINTECH_COMPANIES_MEGA: TopicMatrix = {
  prefix: 'fin-co',
  category: 'Finance',
  tier: 3,
  region: 'global',
  entities: [
    'Stripe',
    'Square Block',
    'PayPal',
    'Adyen',
    'Klarna',
    'Affirm',
    'Brex',
    'Ramp',
    'Divvy',
    'Mercury',
    'Plaid',
    'MX Technologies',
    'Yodlee',
    'Finicity',
    'Marqeta',
    'Galileo Financial',
    'i2c Inc',
    'Lithic',
    'Synapse Financial',
    'Unit Finance',
    'Treasury Prime',
    'Bond Financial',
    'Column Bank',
    'Lead Bank',
    'Cross River Bank',
    'Evolve Bank Trust',
    'Green Dot Corporation',
    'Chime',
    'Current',
    'Varo Bank',
    'Dave Financial',
    'MoneyLion',
    'Albert Financial',
    'Brigit',
    'Earnin',
    'Even Financial',
    'Branch Financial',
    'DailyPay',
    'Payactiv',
    'FlexWage',
    'Gusto',
    'Rippling',
    'Deel',
    'Remote.com',
    'Oyster HR',
    'Papaya Global',
    'Multiplier',
    'Pilot.com',
    'Bench Accounting',
    'Wave Financial',
    'FreshBooks',
    'Xero',
    'QuickBooks Intuit',
    'Sage Group',
    'NetSuite Oracle',
    'Bill.com',
    'Tipalti',
    'Airwallex',
    'Wise',
    'Remitly',
    'WorldRemit',
    'Nium',
    'Thunes',
    'dLocal',
    'Flywire',
    'Payoneer',
    'Checkout.com',
    'Mollie',
    'GoCardless',
    'TrueLayer',
    'Tink',
    'Yapily',
    'Token.io',
    'Bud Financial',
    'Railsr',
    'Thought Machine',
    'Temenos',
    'Finastra',
    'FIS Global',
  ],
  contexts: [
    'revenue',
    'funding',
    'IPO',
    'SPAC',
    'acquisition',
    'partnership',
    'product launch',
    'expansion',
    'regulation',
    'layoff',
    'hiring',
    'valuation',
    'profitability',
    'market share',
    'competition',
    'technology',
    'AI',
    'blockchain',
    'API',
    'banking-as-a-service',
    'embedded finance',
    'open banking',
    'compliance',
    'security',
    'fraud',
  ],
};

// ─── MATRIX 2: CRYPTO & BLOCKCHAIN MEGA ───────────────────────────────────────
// 60 entities × 25 contexts = 1,500 entries
const CRYPTO_BLOCKCHAIN_MEGA: TopicMatrix = {
  prefix: 'fin-crypto',
  category: 'Finance',
  tier: 3,
  region: 'global',
  entities: [
    'Bitcoin',
    'Ethereum',
    'Solana',
    'Avalanche',
    'Polygon',
    'Arbitrum',
    'Optimism',
    'Base Coinbase',
    'Cosmos',
    'Polkadot',
    'Cardano',
    'Tezos',
    'Near Protocol',
    'Sui',
    'Aptos',
    'Sei Network',
    'Celestia',
    'Starknet',
    'zkSync',
    'Mina Protocol',
    'Aleo',
    'Filecoin',
    'Arweave',
    'Chainlink',
    'The Graph',
    'Uniswap',
    'Aave',
    'Compound Finance',
    'MakerDAO',
    'Lido Finance',
    'Rocket Pool',
    'Curve Finance',
    'Balancer',
    'dYdX',
    'GMX',
    'Synthetix',
    'OpenSea',
    'Blur NFT',
    'LooksRare',
    'Rarible',
    'Circle',
    'Tether',
    'Paxos',
    'Coinbase',
    'Binance',
    'Kraken',
    'Gemini',
    'OKX',
    'Bybit',
    'Bitget',
    'Robinhood Crypto',
    'eToro',
    'Interactive Brokers',
    'Fidelity Digital Assets',
    'BlackRock Digital Assets',
    'Galaxy Digital',
    'Grayscale',
    '21Shares',
    'Bitwise Asset Management',
    'VanEck Digital Assets',
  ],
  contexts: [
    'price',
    'market cap',
    'ETF',
    'regulation',
    'SEC',
    'CFTC',
    'legislation',
    'stablecoin',
    'DeFi',
    'NFT',
    'tokenization',
    'real world assets',
    'institutional',
    'custody',
    'hack',
    'exploit',
    'audit',
    'partnership',
    'integration',
    'technology',
    'upgrade',
    'fork',
    'governance',
    'staking',
    'mining',
  ],
};

// ─── MATRIX 3: INSURANCE TECH MEGA ────────────────────────────────────────────
// 40 entities × 20 contexts = 800 entries
const INSURANCE_TECH_MEGA: TopicMatrix = {
  prefix: 'fin-ins',
  category: 'Finance',
  tier: 3,
  region: 'national',
  entities: [
    'Lemonade Insurance',
    'Root Insurance',
    'Hippo Insurance',
    'Kin Insurance',
    'Openly Insurance',
    'Branch Insurance',
    'Clearcover',
    'Jerry Insurance',
    'Bestow Life Insurance',
    'Ladder Life Insurance',
    'Haven Life',
    'Ethos Life',
    'Policygenius',
    'SelectQuote',
    'GoHealth',
    'eHealth Insurance',
    'Oscar Health',
    'Clover Health',
    'Bright Health',
    'Alignment Healthcare',
    'Devoted Health',
    'Centene Corporation',
    'Molina Healthcare',
    'Humana',
    'UnitedHealth Group',
    'Anthem BCBS',
    'Aetna CVS',
    'Cigna',
    'MetLife',
    'Prudential Financial',
    'AIG',
    'Chubb',
    'Travelers',
    'Progressive',
    'Allstate',
    'State Farm',
    'Geico',
    'USAA',
    'Liberty Mutual',
    'Nationwide',
  ],
  contexts: [
    'premium',
    'claims',
    'technology',
    'AI',
    'telematics',
    'parametric',
    'embedded',
    'partnership',
    'regulation',
    'IPO',
    'revenue',
    'acquisition',
    'market share',
    'fraud detection',
    'underwriting',
    'actuarial',
    'reinsurance',
    'catastrophe',
    'climate risk',
    'cyber insurance',
  ],
};

// ─── MATRIX 4: BANKING INFRASTRUCTURE MEGA ────────────────────────────────────
// 40 entities × 20 contexts = 800 entries
const BANKING_INFRASTRUCTURE_MEGA: TopicMatrix = {
  prefix: 'fin-bank',
  category: 'Finance',
  tier: 3,
  region: 'global',
  entities: [
    'JPMorgan Chase',
    'Bank of America',
    'Wells Fargo',
    'Citigroup',
    'Goldman Sachs',
    'Morgan Stanley',
    'US Bancorp',
    'PNC Financial',
    'Truist Financial',
    'Capital One',
    'TD Bank',
    'Citizens Financial',
    'M&T Bank',
    'Regions Financial',
    'KeyCorp',
    'Huntington Bancshares',
    'Zions Bancorporation',
    'Comerica',
    'Fifth Third Bancorp',
    'First Citizens BancShares SVB',
    'First Republic JPMorgan',
    'New York Community Bancorp Signature',
    'HSBC',
    'Barclays',
    'Deutsche Bank',
    'UBS',
    'Credit Suisse UBS',
    'BNP Paribas',
    'Societe Generale',
    'ING Group',
    'ABN AMRO',
    'Santander',
    'BBVA',
    'UniCredit',
    'Intesa Sanpaolo',
    'Commerzbank',
    'Standard Chartered',
    'ANZ Banking Group',
    'Westpac',
    'National Australia Bank',
  ],
  contexts: [
    'earnings',
    'technology',
    'digital banking',
    'mobile app',
    'API',
    'cloud migration',
    'AI',
    'cybersecurity',
    'regulation',
    'Fed',
    'OCC',
    'FDIC',
    'capital',
    'lending',
    'mortgage',
    'credit card',
    'wealth management',
    'trading',
    'custody',
    'ESG',
  ],
};

// ─── MATRIX 5: WEALTH & PAYMENTS MEGA ─────────────────────────────────────────
// 45 entities × 20 contexts = 900 entries
const WEALTH_PAYMENTS_MEGA: TopicMatrix = {
  prefix: 'fin-wlt',
  category: 'Finance',
  tier: 3,
  region: 'global',
  entities: [
    'Wealthfront',
    'Betterment',
    'Personal Capital Empower',
    'SoFi Invest',
    'Acorns',
    'Stash Financial',
    'Public.com',
    'Webull',
    'moomoo Futu',
    'eToro',
    'Freetrade',
    'Trading 212',
    'Revolut',
    'N26',
    'Monzo',
    'Starling Bank',
    'Atom Bank',
    'OakNorth',
    'Tandem Bank',
    'Zopa',
    'Funding Circle',
    'LendingClub',
    'Prosper Marketplace',
    'Upstart',
    'Figure Technologies',
    'SoFi',
    'LoanDepot',
    'Better.com',
    'Rocket Companies',
    'United Wholesale Mortgage',
    'Blend Labs',
    'Snapdocs',
    'Qualia',
    'States Title Doma',
    'Notarize',
    'Visa',
    'Mastercard',
    'American Express',
    'Discover Financial',
    'JCB',
    'UnionPay',
    'Alipay Ant Group',
    'WeChat Pay Tencent',
    'GrabPay',
    'GoPay Indonesia',
  ],
  contexts: [
    'AUM',
    'revenue',
    'users',
    'funding',
    'acquisition',
    'technology',
    'robo-advisor',
    'ESG investing',
    'fractional shares',
    'options',
    'crypto trading',
    'international expansion',
    'regulation',
    'IPO',
    'SPAC',
    'partnership',
    'product launch',
    'competition',
    'AI',
    'personalization',
  ],
};

// ─── EXPORT ────────────────────────────────────────────────────────────────────

export const FINTECH_BANKING_MEGA_SOURCES: FeedSourceEntry[] = [
  ...expandMatrix(FINTECH_COMPANIES_MEGA),      // 80 × 25 = 2,000
  ...expandMatrix(CRYPTO_BLOCKCHAIN_MEGA),      // 60 × 25 = 1,500
  ...expandMatrix(INSURANCE_TECH_MEGA),         // 40 × 20 =   800
  ...expandMatrix(BANKING_INFRASTRUCTURE_MEGA), // 40 × 20 =   800
  ...expandMatrix(WEALTH_PAYMENTS_MEGA),        // 45 × 20 =   900
  // ─────────────────────────────────────────────────────────
  // TOTAL: ~6,000 entries
];

export type { FeedSourceEntry };
