// src/lib/feeds/mega/general-sources.ts
import type { FeedCategory } from '@/lib/agents/feed-agent';

type TopicMatrix = {
  prefix: string;
  category: FeedCategory;
  tier: 1 | 2 | 3 | 4;
  region?: 'el-paso' | 'texas' | 'national' | 'global';
  entities: string[];
  contexts: string[];
};

const GN = (q: string) =>
  `https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=en-US&gl=US&ceid=US:en`;

type FeedSourceEntry = {
  id: string;
  name: string;
  url: string;
  category: FeedCategory;
  tags: string[];
  tier: 1 | 2 | 3 | 4;
  region?: 'el-paso' | 'texas' | 'national' | 'global';
};

function expandMatrix(m: TopicMatrix): FeedSourceEntry[] {
  const results: FeedSourceEntry[] = [];
  for (const entity of m.entities) {
    for (const context of m.contexts) {
      const slug = `${entity} ${context}`.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40);
      const id = `${m.prefix}-${slug}`;
      const query = `${entity} ${context}`;
      results.push({
        id,
        name: `GN: ${entity.slice(0, 18)} ${context.slice(0, 10)}`,
        url: GN(query),
        category: m.category,
        tags: query.toLowerCase().split(/\s+/).filter(w => w.length > 2),
        tier: m.tier,
        region: m.region ?? 'national',
      });
    }
  }
  return results;
}

// ---------------------------------------------------------------------------
// ELPASO_MEGA — tier 2, region el-paso
// 50 entities × 30 contexts = 1,500 entries
// ---------------------------------------------------------------------------
const ELPASO_MEGA: TopicMatrix = {
  prefix: 'ep-mega',
  category: 'General',
  tier: 2,
  region: 'el-paso',
  entities: [
    'City of El Paso',
    'El Paso County',
    'Borderplex Alliance',
    'El Paso Chamber Commerce',
    'UTEP University Texas El Paso',
    'El Paso Community College',
    'Texas Tech Health El Paso',
    'Burrell College Medicine',
    'El Paso Electric',
    'EPWU El Paso Water',
    'Sun Metro Transit',
    'El Paso International Airport',
    'El Paso Children Hospital',
    'University Medical Center',
    'Las Palmas Del Sol Healthcare',
    'Sierra Providence Health',
    'William Beaumont Army Medical',
    'Fort Bliss garrison',
    'El Paso ISD',
    'Ysleta ISD',
    'Socorro ISD',
    'Canutillo ISD',
    'Clint ISD',
    'Fabens ISD',
    'San Elizario ISD',
    'El Paso Hispanic Chamber',
    'El Paso Black Chamber',
    'Junior Achievement El Paso',
    'GECU Credit Union',
    'WestStar Bank',
    'El Paso Natural Gas',
    'Helen of Troy El Paso',
    'Western Refining El Paso',
    'Prudential El Paso',
    'Kleen-Tex El Paso',
    'Delphi El Paso',
    'Foxconn El Paso',
    'Schneider Electric El Paso',
    'Raytheon El Paso',
    'Boeing El Paso',
    'Lockheed Martin El Paso',
    'General Dynamics El Paso',
    'El Paso Zoo',
    'El Paso Museum',
    'El Paso Symphony',
    'El Paso Locomotive FC',
    'El Paso Chihuahuas',
    'UTEP Miners',
    'El Paso Innovation Hub',
    'Borderplex Economic Alliance',
  ],
  contexts: [
    'economic development',
    'business expansion',
    'hiring announcement',
    'construction project',
    'federal grant',
    'state funding',
    'technology investment',
    'innovation hub',
    'startup incubator',
    'workforce training',
    'education program',
    'healthcare initiative',
    'infrastructure project',
    'transportation upgrade',
    'housing development',
    'retail opening',
    'restaurant opening',
    'real estate development',
    'public safety initiative',
    'community event',
    'cultural program',
    'tourism initiative',
    'environmental project',
    'sustainability initiative',
    'trade partnership',
    'manufacturing deal',
    'military contract',
    'research grant',
    'public health',
    'budget decision',
  ],
};

// ---------------------------------------------------------------------------
// TEXAS_MEGA — tier 3, region texas
// 50 entities × 20 contexts = 1,000 entries
// ---------------------------------------------------------------------------
const TEXAS_MEGA: TopicMatrix = {
  prefix: 'tx-mega',
  category: 'General',
  tier: 3,
  region: 'texas',
  entities: [
    'State of Texas',
    'Texas Governor',
    'Texas Legislature',
    'Texas Economic Development',
    'Texas Workforce Commission',
    'Texas A&M University',
    'University of Texas Austin',
    'Rice University',
    'Texas Tech University',
    'University of Houston',
    'Baylor University',
    'SMU Dallas',
    'TCU Fort Worth',
    'UT Dallas',
    'UT San Antonio',
    'UT Arlington',
    'UT El Paso',
    'Texas State University',
    'Texas Instruments',
    'Dell Technologies',
    'Oracle Austin',
    'Tesla Texas',
    'SpaceX Starbase',
    'Samsung Texas',
    'Toyota Texas',
    'AT&T Dallas',
    'American Airlines',
    'Southwest Airlines',
    'USAA San Antonio',
    'Charles Schwab Westlake',
    'Tenet Healthcare',
    'HCA Healthcare Texas',
    'H-E-B grocery',
    'Buc-ees',
    'Whataburger',
    'Texas Roadhouse',
    'Kendra Scott',
    'Academy Sports',
    'Waste Management Houston',
    'Sysco Houston',
    'Halliburton Houston',
    'Phillips 66',
    'Valero San Antonio',
    'Marathon Petroleum',
    'Chevron Permian',
    'Pioneer Permian',
    'ConocoPhillips Houston',
    'NRG Energy',
    'CenterPoint Energy',
    'Oncor Electric',
  ],
  contexts: [
    'business relocation',
    'headquarters move',
    'factory opening',
    'campus expansion',
    'economic impact',
    'workforce growth',
    'technology hub',
    'innovation center',
    'venture investment',
    'IPO filing',
    'earnings report',
    'regulatory change',
    'tax incentive',
    'infrastructure spending',
    'education funding',
    'healthcare expansion',
    'energy development',
    'real estate boom',
    'population growth',
    'cultural shift',
  ],
};

// ---------------------------------------------------------------------------
// HEALTHCARE_MEGA — tier 3, national
// 80 entities × 20 contexts = 1,600 entries
// ---------------------------------------------------------------------------
const HEALTHCARE_MEGA: TopicMatrix = {
  prefix: 'hc-mega',
  category: 'General',
  tier: 3,
  region: 'national',
  entities: [
    'UnitedHealth Group',
    'CVS Health',
    'Cigna Group',
    'Anthem Elevance',
    'Humana',
    'Centene Corp',
    'Molina Healthcare',
    'Kaiser Permanente',
    'HCA Healthcare',
    'CommonSpirit Health',
    'Ascension Health',
    'Providence Health',
    'Trinity Health',
    'Advocate Aurora',
    'Atrium Health',
    'Intermountain Health',
    'Mayo Clinic',
    'Cleveland Clinic',
    'Johns Hopkins',
    'Mass General Brigham',
    'NYU Langone',
    'Mount Sinai',
    'UCSF Health',
    'Stanford Health Care',
    'UCLA Health',
    'Duke Health',
    'Penn Medicine',
    'MD Anderson',
    'Memorial Sloan Kettering',
    'St Jude Children',
    'Pfizer',
    'Johnson Johnson',
    'AbbVie',
    'Merck',
    'Eli Lilly',
    'Bristol Myers Squibb',
    'Roche',
    'Novartis',
    'AstraZeneca',
    'Sanofi',
    'GSK',
    'Amgen',
    'Gilead Sciences',
    'Regeneron',
    'Moderna',
    'BioNTech',
    'Vertex Pharmaceuticals',
    'Biogen',
    'Illumina genomics',
    'Thermo Fisher Scientific',
    'Danaher Corporation',
    'Abbott Laboratories',
    'Medtronic',
    'Stryker',
    'Intuitive Surgical',
    'Edwards Lifesciences',
    'Boston Scientific',
    'Zimmer Biomet',
    'Baxter International',
    'Becton Dickinson',
    'Henry Schein',
    'McKesson',
    'AmerisourceBergen',
    'Cardinal Health',
    'Teladoc Health',
    'Amwell',
    'Doximity',
    'Veeva Systems',
    'Health Catalyst',
    'Tempus AI',
    'PathAI',
    'Butterfly Network',
    'Viz AI',
    'Aidoc',
    'Arterys',
    'Caption Health',
    'Paige AI',
    'Flatiron Health',
    'Komodo Health',
    'Datavant',
    'Truveta',
  ],
  contexts: [
    'FDA approval',
    'clinical trial',
    'drug launch',
    'earnings report',
    'acquisition deal',
    'partnership announcement',
    'technology deployment',
    'AI application',
    'digital health',
    'telemedicine expansion',
    'hospital construction',
    'workforce shortage',
    'pricing controversy',
    'patent litigation',
    'regulatory action',
    'public health alert',
    'disease outbreak',
    'treatment guideline',
    'medical device recall',
    'research breakthrough',
  ],
};

// ---------------------------------------------------------------------------
// EDUCATION_MEGA — tier 4, national
// 50 entities × 20 contexts = 1,000 entries
// ---------------------------------------------------------------------------
const EDUCATION_MEGA: TopicMatrix = {
  prefix: 'edu-mega',
  category: 'General',
  tier: 4,
  region: 'national',
  entities: [
    'Harvard University',
    'MIT',
    'Stanford University',
    'CalTech',
    'Princeton',
    'Yale',
    'Columbia',
    'University of Chicago',
    'Duke University',
    'Northwestern',
    'Johns Hopkins University',
    'University of Pennsylvania',
    'Cornell University',
    'Brown University',
    'Dartmouth College',
    'Carnegie Mellon',
    'Georgia Tech',
    'University of Michigan',
    'University of Virginia',
    'UC Berkeley',
    'UCLA',
    'USC',
    'University of Washington',
    'University of Wisconsin',
    'Ohio State University',
    'Penn State',
    'University of Illinois',
    'Purdue University',
    'University of Minnesota',
    'University of Colorado',
    'Arizona State University',
    'University of Florida',
    'University of North Carolina',
    'University of Texas system',
    'Texas A&M system',
    'California State system',
    'SUNY system',
    'community college system',
    'K-12 education technology',
    'online learning platform',
    'Coursera',
    'Udemy',
    'edX',
    'Khan Academy',
    'Chegg',
    'Duolingo',
    "Byju's",
    'Quizlet',
    'Canvas LMS',
    'Blackboard',
  ],
  contexts: [
    'enrollment trend',
    'tuition change',
    'research funding',
    'faculty hiring',
    'campus construction',
    'technology investment',
    'AI in education',
    'online program',
    'degree innovation',
    'student outcomes',
    'accreditation',
    'ranking change',
    'endowment performance',
    'alumni giving',
    'international students',
    'diversity initiative',
    'free speech debate',
    'athletics program',
    'transfer policy',
    'workforce alignment',
  ],
};

// ---------------------------------------------------------------------------
// GOVERNMENT_MEGA — tier 3, national
// 50 entities × 25 contexts = 1,250 entries
// ---------------------------------------------------------------------------
const GOVERNMENT_MEGA: TopicMatrix = {
  prefix: 'gov-mega',
  category: 'General',
  tier: 3,
  region: 'national',
  entities: [
    'White House administration',
    'US Congress',
    'US Senate',
    'US House Representatives',
    'Department of Defense',
    'Department of State',
    'Department of Homeland Security',
    'Department of Justice',
    'Department of Energy',
    'Department of Commerce',
    'Department of Treasury',
    'Department of Labor',
    'Department of Education',
    'Department of Health Human Services',
    'Department of Agriculture',
    'Department of Interior',
    'Department of Transportation',
    'Department of Housing',
    'Department of Veterans Affairs',
    'EPA Environmental Protection',
    'NASA',
    'NSF National Science Foundation',
    'NIH National Institutes Health',
    'CDC Centers Disease Control',
    'FEMA',
    'SBA Small Business Administration',
    'GSA General Services',
    'USDA',
    'FAA Federal Aviation',
    'FCC Federal Communications',
    'FTC Federal Trade',
    'SEC Securities Exchange',
    'CISA Cybersecurity',
    'NIST Standards',
    'DARPA',
    'IARPA',
    'NGA National Geospatial',
    'NRO National Reconnaissance',
    'NSA National Security Agency',
    'CIA Central Intelligence',
    'DIA Defense Intelligence',
    'FBI Federal Bureau',
    'ATF Alcohol Tobacco',
    'DEA Drug Enforcement',
    'US Marshals',
    'CBP Customs Border',
    'ICE Immigration Customs',
    'TSA Transportation Security',
    'Coast Guard',
    'Space Force',
  ],
  contexts: [
    'budget request',
    'appropriations bill',
    'executive order',
    'regulatory rulemaking',
    'policy announcement',
    'technology procurement',
    'contract award',
    'SBIR grant',
    'research program',
    'workforce initiative',
    'infrastructure investment',
    'cybersecurity directive',
    'AI strategy',
    'data governance',
    'cloud migration',
    'zero trust mandate',
    'sustainability goal',
    'environmental regulation',
    'trade policy',
    'international cooperation',
    'inspection audit',
    'GAO report',
    'IG investigation',
    'whistleblower',
    'reorganization plan',
  ],
};

// ---------------------------------------------------------------------------
// REAL_ESTATE_MEGA — tier 4, national
// 50 entities × 20 contexts = 1,000 entries
// ---------------------------------------------------------------------------
const REAL_ESTATE_MEGA: TopicMatrix = {
  prefix: 're-mega',
  category: 'General',
  tier: 4,
  region: 'national',
  entities: [
    'Prologis industrial',
    'Equinix data center',
    'Digital Realty',
    'American Tower',
    'Crown Castle',
    'SBA Communications',
    'Public Storage',
    'Extra Space Storage',
    'Invitation Homes',
    'American Homes 4 Rent',
    'CBRE Group',
    'JLL Jones Lang LaSalle',
    'Cushman Wakefield',
    'Colliers International',
    'Newmark Group',
    'Marcus Millichap',
    'Eastdil Secured',
    'Brookfield Asset',
    'Blackstone Real Estate',
    'Starwood Capital',
    'KKR Real Estate',
    'Apollo Real Estate',
    'Hines Development',
    'Related Companies',
    'Tishman Speyer',
    'Boston Properties',
    'SL Green Realty',
    'Vornado Realty',
    'Kilroy Realty',
    'Alexandria Real Estate',
    'BioMed Realty',
    'Ventas Healthcare',
    'Welltower Senior',
    'Medical Properties Trust',
    'Simon Property Group',
    'Macerich',
    'Brookfield Property',
    'Federal Realty',
    'Regency Centers',
    'Kimco Realty',
    'AvalonBay Communities',
    'Equity Residential',
    'Essex Property',
    'Camden Property',
    'Mid-America Apartment',
    'El Paso real estate market',
    'Juarez industrial park',
    'Santa Teresa industrial',
    'Borderplex development',
    'data center construction',
  ],
  contexts: [
    'development project',
    'construction start',
    'lease signing',
    'acquisition deal',
    'REIT earnings',
    'occupancy rate',
    'rent growth',
    'cap rate',
    'development pipeline',
    'zoning approval',
    'environmental review',
    'financing arrangement',
    'joint venture',
    'fund raising',
    'property sale',
    'market analysis',
    'vacancy trend',
    'absorption rate',
    'new supply',
    'demand driver',
  ],
};

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------
export const GENERAL_MEGA_SOURCES: FeedSourceEntry[] = [
  ...expandMatrix(ELPASO_MEGA),
  ...expandMatrix(TEXAS_MEGA),
  ...expandMatrix(HEALTHCARE_MEGA),
  ...expandMatrix(EDUCATION_MEGA),
  ...expandMatrix(GOVERNMENT_MEGA),
  ...expandMatrix(REAL_ESTATE_MEGA),
];
