// src/lib/feeds/mega/supply-chain-sources.ts
import type { FeedCategory } from '@/lib/agents/feed-agent';

type TopicMatrix = {
  prefix: string;
  category: FeedCategory;
  tier: 1 | 2 | 3 | 4;
  region?: 'el-paso' | 'texas' | 'national' | 'global';
  entities: string[];
  contexts: string[];
};

const GN = (q: string) =>
  `https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=en-US&gl=US&ceid=US:en`;

type FeedSourceEntry = {
  id: string;
  name: string;
  url: string;
  category: FeedCategory;
  tags: string[];
  tier: 1 | 2 | 3 | 4;
  region?: 'el-paso' | 'texas' | 'national' | 'global';
};

function expandMatrix(m: TopicMatrix): FeedSourceEntry[] {
  const results: FeedSourceEntry[] = [];
  for (const entity of m.entities) {
    for (const context of m.contexts) {
      const slug = `${entity} ${context}`.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40);
      const id = `${m.prefix}-${slug}`;
      const query = `${entity} ${context}`;
      results.push({
        id,
        name: `GN: ${entity.slice(0, 18)} ${context.slice(0, 10)}`,
        url: GN(query),
        category: m.category,
        tags: query.toLowerCase().split(/\s+/).filter(w => w.length > 2),
        tier: m.tier,
        region: m.region ?? 'national',
      });
    }
  }
  return results;
}

// ---------------------------------------------------------------------------
// LOGISTICS_COMPANIES_MEGA
// 80 entities × 20 contexts = 1,600 sources
// ---------------------------------------------------------------------------
const LOGISTICS_COMPANIES_MEGA: TopicMatrix = {
  prefix: 'sc-log',
  category: 'Supply Chain',
  tier: 3,
  region: 'global',
  entities: [
    'Maersk',
    'MSC Mediterranean',
    'CMA CGM',
    'COSCO Shipping',
    'Hapag-Lloyd',
    'ONE Ocean Network',
    'Evergreen Marine',
    'Yang Ming',
    'HMM Hyundai',
    'ZIM Shipping',
    'FedEx',
    'UPS',
    'DHL',
    'Amazon Logistics',
    'XPO Logistics',
    'J.B. Hunt',
    'C.H. Robinson',
    'Kuehne Nagel',
    'DB Schenker',
    'DSV Panalpina',
    'Nippon Express',
    'Expeditors International',
    'Ceva Logistics',
    'Ryder System',
    'Werner Enterprises',
    'Old Dominion Freight',
    'SAIA trucking',
    'TFI International',
    'Schneider National',
    'Landstar System',
    'Knight-Swift',
    'Heartland Express',
    'USA Truck',
    'Marten Transport',
    'Arcbest Corporation',
    'Estes Express',
    'R+L Carriers',
    'Southeastern Freight',
    'Forward Air',
    'Echo Global Logistics',
    'Coyote Logistics',
    'Total Quality Logistics',
    'Nolan Transportation',
    'GlobalTranz',
    'Transplace',
    'Uber Freight',
    'Convoy trucking',
    'Flexport',
    'project44',
    'FourKites',
    'Descartes Systems',
    'Manhattan Associates',
    'Blue Yonder',
    'Kinaxis supply chain',
    'o9 Solutions',
    'E2open',
    'Coupa supply chain',
    'SAP Integrated Business Planning',
    'Oracle Supply Chain',
    'Infor Nexus',
    'GEP supply chain',
    'Llamasoft LLamasoft',
    'RELEX Solutions',
    'Anaplan supply',
    'Locus Robotics',
    '6 River Systems',
    'Fetch Robotics',
    'AutoStore warehouse',
    'Ocado Technology',
    'Symbotic warehouse',
    'Berkshire Grey',
    'RightHand Robotics',
    'Dematic automation',
    'Honeywell Intelligrated',
    'Vanderlande',
    'KION Group',
    'KNAPP',
    'SSI Schaefer',
    'Swisslog',
    'TGW Logistics',
  ],
  contexts: [
    'quarterly earnings',
    'route expansion',
    'capacity update',
    'technology upgrade',
    'pricing change',
    'labor dispute',
    'acquisition merger',
    'partnership deal',
    'sustainability initiative',
    'fleet modernization',
    'warehouse opening',
    'automation deployment',
    'AI optimization',
    'drone delivery',
    'autonomous trucking',
    'electric vehicle fleet',
    'cold chain expansion',
    'last mile innovation',
    'cross-border operations',
    'regulatory compliance',
  ],
};

// ---------------------------------------------------------------------------
// SEMICONDUCTOR_MEGA
// 60 entities × 20 contexts = 1,200 sources
// ---------------------------------------------------------------------------
const SEMICONDUCTOR_MEGA: TopicMatrix = {
  prefix: 'sc-semi',
  category: 'Supply Chain',
  tier: 3,
  region: 'global',
  entities: [
    'TSMC',
    'Samsung Foundry',
    'Intel Foundry Services',
    'GlobalFoundries',
    'UMC United Micro',
    'SMIC China',
    'Qualcomm',
    'Broadcom',
    'Texas Instruments',
    'NXP Semiconductors',
    'ON Semiconductor',
    'Infineon Technologies',
    'STMicroelectronics',
    'Renesas Electronics',
    'Microchip Technology',
    'Analog Devices',
    'Marvell Technology',
    'Skyworks Solutions',
    'Qorvo RF',
    'II-VI Coherent',
    'Lattice Semiconductor',
    'Maxlinear',
    'Silicon Labs',
    'Wolfspeed SiC',
    'Cree LED',
    'NVIDIA chips',
    'AMD processors',
    'Intel processors',
    'Arm Holdings',
    'RISC-V International',
    'SiFive RISC-V',
    'Applied Materials',
    'Lam Research',
    'KLA Corporation',
    'ASML lithography',
    'Tokyo Electron',
    'Screen Holdings',
    'Entegris materials',
    'Cabot Microelectronics',
    'Air Liquide electronics',
    'Shin-Etsu Chemical',
    'Sumco wafer',
    'Disco Corporation',
    'Advantest testing',
    'Teradyne testing',
    'Cohu testing',
    'Amkor packaging',
    'ASE Technology',
    'JCET packaging',
    'Micron Technology',
    'SK Hynix',
    'Samsung Memory',
    'Western Digital',
    'Kioxia flash',
    'Seagate Technology',
    'Nanya Technology',
    'Winbond Electronics',
    'Phison Electronics',
    'Silicon Motion',
  ],
  contexts: [
    'fab construction',
    'capacity expansion',
    'technology node',
    'chip shortage',
    'yield improvement',
    'design win',
    'earnings report',
    'export control',
    'government subsidy',
    'CHIPS Act funding',
    'research breakthrough',
    'partnership deal',
    'product launch',
    'pricing update',
    'inventory buildup',
    'demand forecast',
    'foundry allocation',
    'advanced packaging',
    'heterogeneous integration',
    'supply chain resilience',
  ],
};

// ---------------------------------------------------------------------------
// MANUFACTURING_MEGA
// 60 entities × 20 contexts = 1,200 sources
// ---------------------------------------------------------------------------
const MANUFACTURING_MEGA: TopicMatrix = {
  prefix: 'sc-mfg',
  category: 'Supply Chain',
  tier: 3,
  region: 'global',
  entities: [
    'Caterpillar',
    'John Deere',
    'AGCO Corporation',
    'CNH Industrial',
    'Komatsu',
    'Volvo Construction',
    'Hitachi Construction',
    'Liebherr',
    'JCB equipment',
    'Manitou',
    'Terex Corporation',
    'Doosan Infracore',
    'Hyundai Construction',
    'XCMG China',
    'Sany Heavy',
    'Zoomlion Heavy',
    'Putzmeister',
    'Wirtgen Group',
    'Atlas Copco',
    'Sandvik Mining',
    'Metso Outotec',
    'Epiroc drilling',
    'Parker Hannifin',
    'Eaton Corporation',
    'Emerson Electric',
    'Illinois Tool Works',
    'Dover Corporation',
    'Roper Technologies',
    'Fortive Corporation',
    'Danaher Corporation',
    'Honeywell Process',
    'ABB Industrial',
    'Siemens Industry',
    'Fanuc robotics',
    'Yaskawa Electric',
    'KUKA Robotics',
    'Universal Robots',
    'Omron Automation',
    'Keyence sensors',
    'Cognex vision',
    'Rockwell Automation',
    'Schneider Electric',
    'Mitsubishi Electric',
    'Bosch Rexroth',
    'Festo automation',
    'SMC Corporation',
    'Beckhoff Automation',
    'B&R Automation',
    'Phoenix Contact',
    'Weidmuller',
    'Turck sensors',
    'ifm electronic',
    'Balluff sensors',
    'Sick AG sensors',
    'Banner Engineering',
    'Zebra Technologies',
    'Honeywell Scanning',
    'Datalogic scanning',
    'Cognex barcode',
    'Brother Industries',
  ],
  contexts: [
    'factory opening',
    'production ramp',
    'automation upgrade',
    'robotics deployment',
    'AI quality control',
    'digital twin implementation',
    'predictive maintenance',
    'Industry 4.0',
    'smart factory',
    'IoT sensor deployment',
    'supply chain disruption',
    'reshoring initiative',
    'nearshoring Mexico',
    'quarterly earnings',
    'workforce training',
    'safety improvement',
    'sustainability target',
    'energy efficiency',
    'additive manufacturing',
    'material innovation',
  ],
};

// ---------------------------------------------------------------------------
// TRADE_ROUTES_MEGA
// 50 entities × 20 contexts = 1,000 sources
// ---------------------------------------------------------------------------
const TRADE_ROUTES_MEGA: TopicMatrix = {
  prefix: 'sc-trade',
  category: 'Supply Chain',
  tier: 4,
  region: 'global',
  entities: [
    'Port of Los Angeles',
    'Port of Long Beach',
    'Port of New York Newark',
    'Port of Savannah',
    'Port of Houston',
    'Port of Charleston',
    'Port of Virginia',
    'Port of Oakland',
    'Port of Seattle Tacoma',
    'Port of Laredo Texas',
    'Port of El Paso Texas',
    'Port of Nogales Arizona',
    'Port of San Diego',
    'Port of Detroit',
    'Port of Buffalo',
    'Panama Canal',
    'Suez Canal',
    'Strait of Malacca',
    'Strait of Hormuz',
    'Bab el-Mandeb strait',
    'Cape of Good Hope route',
    'Northern Sea Route Arctic',
    'Trans-Pacific route',
    'Trans-Atlantic route',
    'Asia-Europe trade lane',
    'US-Mexico trade corridor',
    'US-Canada trade corridor',
    'USMCA trade',
    'China-US trade',
    'EU-US trade',
    'India trade route',
    'Vietnam manufacturing hub',
    'Bangladesh garment hub',
    'Indonesia commodity route',
    'Brazil agricultural trade',
    'Chile copper route',
    'Colombia coffee trade',
    'Middle East oil route',
    'LNG shipping global',
    'grain shipping Black Sea',
    'container shipping market',
    'bulk carrier market',
    'tanker shipping market',
    'air cargo global',
    'rail freight intermodal',
    'cross-border trucking',
    'free trade zone',
    'bonded warehouse',
    'customs brokerage',
    'foreign trade zone',
  ],
  contexts: [
    'congestion update',
    'throughput volume',
    'vessel delay',
    'labor negotiation',
    'infrastructure investment',
    'tariff change',
    'trade policy',
    'sanctions impact',
    'geopolitical disruption',
    'weather disruption',
    'capacity constraint',
    'rate increase',
    'rate decrease',
    'new service launch',
    'alliance restructuring',
    'environmental regulation',
    'emission standard',
    'digitization initiative',
    'blockchain tracking',
    'customs modernization',
  ],
};

// ---------------------------------------------------------------------------
// SUPPLY_TECH_MEGA
// 60 entities × 20 contexts = 1,200 sources
// ---------------------------------------------------------------------------
const SUPPLY_TECH_MEGA: TopicMatrix = {
  prefix: 'sc-tech',
  category: 'Supply Chain',
  tier: 4,
  region: 'global',
  entities: [
    'warehouse management system WMS',
    'transportation management system TMS',
    'order management system OMS',
    'yard management system',
    'labor management system',
    'inventory optimization software',
    'demand planning software',
    'supply planning software',
    'sales operations planning S&OP',
    'integrated business planning IBP',
    'control tower supply chain',
    'supply chain visibility platform',
    'track and trace solution',
    'real-time location system RTLS',
    'RFID supply chain',
    'barcode scanning warehouse',
    'pick-to-light system',
    'voice picking technology',
    'goods-to-person system',
    'autonomous mobile robot AMR',
    'automated guided vehicle AGV',
    'automated storage retrieval ASRS',
    'shuttle system warehouse',
    'conveyor system automation',
    'sortation system logistics',
    'palletizing robot',
    'depalletizing robot',
    'packing robot',
    'drone inventory counting',
    'computer vision warehouse',
    'digital twin supply chain',
    'blockchain supply chain',
    'IoT supply chain sensor',
    'temperature monitoring cold chain',
    'humidity monitoring warehouse',
    'predictive analytics logistics',
    'machine learning demand forecast',
    'AI route optimization',
    'autonomous truck technology',
    'platooning truck convoy',
    'electric delivery van',
    'cargo electric bicycle',
    'delivery drone UAV',
    'sidewalk delivery robot',
    'smart locker parcel',
    'micro fulfillment center',
    'dark store last mile',
    'crowdsourced delivery',
    'gig economy logistics',
    '3PL technology platform',
    '4PL orchestration platform',
    'freight marketplace',
    'load matching technology',
    'dynamic pricing freight',
    'spot rate prediction',
    'container tracking device',
    'electronic logging device',
    'fleet telematics platform',
    'fuel management system',
    'carbon tracking logistics',
  ],
  contexts: [
    'product launch',
    'customer deployment',
    'ROI case study',
    'market analysis',
    'technology comparison',
    'vendor evaluation',
    'implementation guide',
    'integration update',
    'pricing model',
    'startup funding',
    'acquisition deal',
    'partnership announcement',
    'pilot program',
    'scaling deployment',
    'industry award',
    'analyst report',
    'benchmark study',
    'regulation impact',
    'sustainability feature',
    'innovation showcase',
  ],
};

// ---------------------------------------------------------------------------
// Combined export — 5 matrices, 6,200+ entries total
// LOGISTICS  80 × 20 = 1,600
// SEMI       59 × 20 = 1,180
// MFG        60 × 20 = 1,200
// TRADE      50 × 20 = 1,000
// TECH       60 × 20 = 1,200
// ---------------------------------------------------------------------------
export const SUPPLY_CHAIN_MEGA_SOURCES: FeedSourceEntry[] = [
  ...expandMatrix(LOGISTICS_COMPANIES_MEGA),
  ...expandMatrix(SEMICONDUCTOR_MEGA),
  ...expandMatrix(MANUFACTURING_MEGA),
  ...expandMatrix(TRADE_ROUTES_MEGA),
  ...expandMatrix(SUPPLY_TECH_MEGA),
];
