// src/app/api/intel-curation/route.ts
//
// NXT LINK Intelligence Curation Department API
// Returns curated, organized, enriched intelligence brief
// generated by the multi-agent Gemini department.

import { NextResponse } from 'next/server';
import { checkRateLimit } from '@/lib/http/rate-limit';
import { getClientIp } from '@/lib/http/request-context';
import { getCachedBrief, runIntelCurationAgent } from '@/lib/agents/agents/intel-curation-agent';
import { getCachedIntelDiscovery, runIntelDiscoveryAgent } from '@/lib/agents/agents/intel-discovery-agent';

export const dynamic = 'force-dynamic';

export async function GET(request: Request): Promise<NextResponse> {
  const ip = getClientIp(request.headers);
  const rl = checkRateLimit({ key: `intel-curation:${ip}`, maxRequests: 20, windowMs: 60_000 });
  if (!rl.allowed) {
    return NextResponse.json({ ok: false, message: 'Rate limit exceeded.' }, { status: 429 });
  }

  // Return cached brief immediately if available
  const cached = getCachedBrief();
  if (cached) {
    return NextResponse.json(
      { ok: true, brief: cached, source: 'cache' },
      { headers: { 'Cache-Control': 'public, s-maxage=300, stale-while-revalidate=600' } },
    );
  }

  // Get signals from discovery agent (use cache if available, else run)
  let signals = getCachedIntelDiscovery()?.signals ?? [];
  if (signals.length === 0) {
    try {
      const store = await runIntelDiscoveryAgent();
      signals = store.signals;
    } catch {
      return NextResponse.json(
        { ok: false, message: 'No signals available — discovery agent not warmed.' },
        { status: 503 },
      );
    }
  }

  if (signals.length === 0) {
    return NextResponse.json(
      { ok: true, brief: null, message: 'No signals to curate yet.', source: 'empty' },
    );
  }

  try {
    const brief = await runIntelCurationAgent(signals);
    return NextResponse.json(
      { ok: true, brief, source: 'generated' },
      { headers: { 'Cache-Control': 'public, s-maxage=600, stale-while-revalidate=1200' } },
    );
  } catch (err) {
    return NextResponse.json(
      {
        ok: false,
        message: err instanceof Error ? err.message : 'Curation failed.',
        source: 'error',
      },
      { status: 500 },
    );
  }
}
